Repository zendeskgarden/react-components, pull requests merged in 2019-06, with the labels that each got.

#353 chore(lerna): update versioning flow
  .gitignore
  CHANGELOG.md
  lerna.json
  package.json
  packages/.template/CHANGELOG.md
  packages/autocomplete/CHANGELOG.md
  packages/avatars/CHANGELOG.md
  packages/breadcrumbs/CHANGELOG.md
  packages/buttons/CHANGELOG.md
  packages/checkboxes/CHANGELOG.md
  packages/chrome/CHANGELOG.md
  packages/dropdowns/CHANGELOG.md
  packages/forms/CHANGELOG.md
  packages/grid/CHANGELOG.md
  packages/loaders/CHANGELOG.md
  packages/menus/CHANGELOG.md
  packages/modals/CHANGELOG.md
  packages/notifications/CHANGELOG.md
  packages/pagination/CHANGELOG.md
  packages/radios/CHANGELOG.md
  packages/ranges/CHANGELOG.md
  packages/select/CHANGELOG.md
  packages/selection/CHANGELOG.md
  packages/tables/CHANGELOG.md
  packages/tabs/CHANGELOG.md
  packages/tags/CHANGELOG.md
  packages/textfields/CHANGELOG.md
  packages/theming/CHANGELOG.md
  packages/toggles/CHANGELOG.md
  packages/tooltips/CHANGELOG.md
  packages/typography/CHANGELOG.md
  packages/utilities/CHANGELOG.md
  renovate.json
  utils/scripts/github-release.js
  utils/scripts/update-changelog.js
  utils/scripts/version.sh
  utils/styleguide/TableOfContentsRenderer/index.js
  yarn.lock
Labels: PR: Internal :seedling:

#356 fix(publish): all version flow to push changelog correctly
  CHANGELOG.md
  utils/scripts/version.sh
Labels: PR: Internal :seedling:

#358 fix(pagination): update peerDependencies to match other packages
  packages/pagination/package.json
Labels: PR: Bug Fix :bug:

#359 chore(lint): ensure that no unsafe lifecycle events are used
  .eslintrc.json
Labels: PR: Internal :seedling:

#357 chore(docs): add create-react-app codesandbox example
  .github/ISSUE_TEMPLATE.md
  README.md
  examples/codesandbox/garden-create-react-app/.env
  examples/codesandbox/garden-create-react-app/.gitignore
  examples/codesandbox/garden-create-react-app/.prettierrc
  examples/codesandbox/garden-create-react-app/package.json
  examples/codesandbox/garden-create-react-app/public/favicon.ico
  examples/codesandbox/garden-create-react-app/public/index.html
  examples/codesandbox/garden-create-react-app/public/manifest.json
  examples/codesandbox/garden-create-react-app/src/components/ExampleWrapper.js
  examples/codesandbox/garden-create-react-app/src/examples/Example.js
  examples/codesandbox/garden-create-react-app/src/global-styling.js
  examples/codesandbox/garden-create-react-app/src/index.js
  examples/codesandbox/garden-create-react-app/yarn.lock
Labels: PR: Docs :memo:

#360 fix(tables): adjust paginated example cell width to accommodate small-sized avatar
  packages/tables/src/examples/paginated-table.md
Labels: PR: Docs :memo:

#361 fix(build): add tag fetching to process
  utils/scripts/version.sh
Labels: PR: Bug Fix :bug:

#362 chore: add versioning documentation
  .github/API.md
  .github/CONTRIBUTING.md
  .github/DEVELOPMENT.md
  .github/ISSUE_TEMPLATE.md
  API.md
  DEVELOPMENT.md
  VERSIONING.md
  package.json
Labels: PR: Docs :memo:

#364 chore(demo): add `react-containers` link + deprecated packages section
  demo/index.html
  demo/index.svg
Labels: PR: Docs :memo:

#363 fix(avatars): update avatar CSS for badge animation
  packages/avatars/package.json
  packages/avatars/src/Avatar.example.md
  packages/avatars/src/Avatar.js
  packages/avatars/src/Avatar.spec.js
  packages/avatars/src/styled.js
  packages/avatars/src/styled.spec.js
Labels: PR: Bug Fix :bug:

#366 fix(buttons): Pass className to <Icon />
  packages/buttons/src/views/icon-button/Icon.js
  packages/buttons/src/views/icon-button/Icon.spec.js
Labels: PR: Bug Fix :bug:
