Repository zendeskgarden/react-components, pull requests merged in 2019-12, with the labels that each got.

#545 feat(grid): CSS-in-JS refactor
  BREAKING_CHANGES.md
  packages/grid/README.md
  packages/grid/examples/advanced.md
  packages/grid/examples/basic.md
  packages/grid/package.json
  packages/grid/src/elements/Col.spec.tsx
  packages/grid/src/elements/Col.tsx
  packages/grid/src/elements/Grid.spec.tsx
  packages/grid/src/elements/Grid.tsx
  packages/grid/src/elements/Row.spec.tsx
  packages/grid/src/elements/Row.tsx
  packages/grid/src/styled/StyledCol.spec.tsx
  packages/grid/src/styled/StyledCol.ts
  packages/grid/src/styled/StyledGrid.spec.tsx
  packages/grid/src/styled/StyledGrid.ts
  packages/grid/src/styled/StyledRow.spec.tsx
  packages/grid/src/styled/StyledRow.ts
  packages/grid/src/utils/types.ts
  packages/grid/src/utils/useGridContext.spec.tsx
  packages/grid/src/utils/useGridContext.ts
  packages/grid/styleguide.config.js
  packages/theming/examples/default-theme.md
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
  utils/build/declarations.d.ts
  utils/build/styled.d.ts
Labels: PR: Breaking Change :boom:

#549 chore: apply garden logo to demo pages
  demo/index.html
  demo/index.svg
  package.json
  utils/styleguide/LogoRenderer/index.js
  yarn.lock
Labels: PR: Internal :seedling:

#552 fix(all): update ID prefixes to reflect deprecated status
  .gitignore
  packages/autocomplete/src/containers/AutocompleteContainer.js
  packages/buttons/src/containers/ButtonGroupContainer.js
  packages/chrome/src/containers/AccordionContainer.js
  packages/datepickers/src/Datepicker/Datepicker.tsx
  packages/dropdowns/src/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/Multiselect/Multiselect.tsx
  packages/dropdowns/src/Select/Select.tsx
  packages/menus/src/containers/MenuContainer.js
  packages/modals/src/containers/ModalContainer.js
  packages/pagination/src/containers/PaginationContainer.js
  packages/select/src/containers/SelectContainer.js
  packages/selection/src/containers/FieldContainer.js
  packages/selection/src/containers/SelectionContainer.js
  packages/tabs/src/containers/TabsContainer.js
  packages/tooltips/src/containers/TooltipContainer.js
Labels: PR: Bug Fix :bug:

#553 chore: update next with master branch commits
  CHANGELOG.md
  demo/index.html
  demo/index.svg
  package.json
  packages/modals/src/elements/Modal.js
  packages/modals/src/elements/Modal.spec.js
  utils/styleguide/LogoRenderer/index.js
  yarn.lock
Labels: PR: Internal :seedling:

#557 fix: access foreground/background directly via theme
  packages/tags/src/styled/StyledTag.spec.tsx
  packages/tags/src/styled/StyledTag.ts
Labels: PR: Bug Fix :bug:

#558 chore: remove `react-selection` package
  BREAKING_CHANGES.md
  demo/index.html
  packages/selection/README.md
  packages/selection/package.json
  packages/selection/src/constants/KEY_CODES.js
  packages/selection/src/containers/FieldContainer.example.md
  packages/selection/src/containers/FieldContainer.js
  packages/selection/src/containers/FieldContainer.spec.js
  packages/selection/src/containers/KeyboardFocusContainer.example.md
  packages/selection/src/containers/KeyboardFocusContainer.js
  packages/selection/src/containers/KeyboardFocusContainer.spec.js
  packages/selection/src/containers/SelectionContainer.example.md
  packages/selection/src/containers/SelectionContainer.js
  packages/selection/src/containers/SelectionContainer.spec.js
  packages/selection/src/index.js
  packages/selection/src/index.spec.js
  packages/selection/src/utils/ControlledComponent.example.md
  packages/selection/src/utils/ControlledComponent.js
  packages/selection/src/utils/IdManager.js
  packages/selection/src/utils/IdManager.spec.js
  packages/selection/src/utils/SingleSelectionModel.js
  packages/selection/src/utils/SingleSelectionModel.spec.js
  packages/selection/src/utils/composeEventHandlers.js
  packages/selection/src/utils/composeEventHandlers.spec.js
  packages/selection/styleguide.config.js
  utils/build/declarations.d.ts
Labels: PR: Breaking Change :boom:

#559 fix: update to use theme `iconSizes.md` for paddle SVGs
  packages/datepickers/src/styled/StyledHeaderPaddle.ts
Labels: PR: Bug Fix :bug:
