Repository zendeskgarden/react-components, pull requests merged in 2019-11, with the labels that each got.

#510 fix(buttons): remove invalid disabled prop from Anchor
  .gitignore
  packages/buttons/src/views/Anchor.js
  packages/buttons/src/views/Anchor.spec.js
Labels: PR: Bug Fix :bug:

#511 feat(dropdowns): add inputRef prop to Autocomplete and Multiselect
  packages/dropdowns/src/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/Multiselect/Multiselect.tsx
Labels: PR: New Feature :rocket:

#512 fix(dropdowns): allow inline style to override Menu width
  packages/dropdowns/src/Menu/Menu.tsx
Labels: PR: Bug Fix :bug:

#513 fix(build): correct TS usages of react-popper
  packages/datepickers/src/Datepicker/Datepicker.tsx
  packages/dropdowns/src/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/Multiselect/Multiselect.tsx
  packages/dropdowns/src/Select/Select.tsx
Labels: PR: Bug Fix :bug:

#518 chore(docs): remove invalid prop from table docs
  packages/tables/src/examples/overflow-menu.md
Labels: PR: Docs :memo:

#517 fix(datepickers): allow controlled value to update internal state
  bundlesize.config.js
  packages/datepickers/package.json
  packages/datepickers/src/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/Datepicker/Datepicker.tsx
  packages/datepickers/src/Datepicker/utils/datepicker-reducer.ts
Labels: PR: Bug Fix :bug:

#520 fix(avatars): img scaling and move `components` to `elements`
  packages/avatars/src/elements/Avatar.spec.tsx
  packages/avatars/src/elements/Avatar.tsx
  packages/avatars/src/index.ts
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/styleguide.config.js
Labels: PR: Bug Fix :bug:

#521 fix(tags): use `isBoolean` prop naming and add missing prop types
  BREAKING_CHANGES.md
  packages/tags/examples/advanced.md
  packages/tags/examples/basic.md
  packages/tags/src/elements/Close.spec.tsx
  packages/tags/src/elements/Close.tsx
  packages/tags/src/elements/Tag.spec.tsx
  packages/tags/src/elements/Tag.tsx
  packages/tags/src/index.ts
  packages/tags/src/styled/StyledTag.spec.tsx
  packages/tags/src/styled/StyledTag.ts
  packages/tags/styleguide.config.js
Labels: PR: Breaking Change :boom:

#522 fix(typography): rename `isMonospace` prop and add missing prop types
  BREAKING_CHANGES.md
  packages/typography/examples/typography.md
  packages/typography/package.json
  packages/typography/src/elements/Code.spec.tsx
  packages/typography/src/elements/Code.tsx
  packages/typography/src/elements/Ellipsis.spec.tsx
  packages/typography/src/elements/Ellipsis.tsx
  packages/typography/src/elements/LG.spec.tsx
  packages/typography/src/elements/LG.tsx
  packages/typography/src/elements/MD.spec.tsx
  packages/typography/src/elements/MD.tsx
  packages/typography/src/elements/SM.spec.tsx
  packages/typography/src/elements/SM.tsx
  packages/typography/src/elements/XL.spec.tsx
  packages/typography/src/elements/XL.tsx
  packages/typography/src/elements/XXL.spec.tsx
  packages/typography/src/elements/XXL.tsx
  packages/typography/src/elements/XXXL.spec.tsx
  packages/typography/src/elements/XXXL.tsx
  packages/typography/src/elements/lists/OrderedList.spec.tsx
  packages/typography/src/elements/lists/OrderedList.tsx
  packages/typography/src/elements/lists/OrderedListItem.spec.js
  packages/typography/src/elements/lists/OrderedListItem.tsx
  packages/typography/src/elements/lists/UnorderedList.spec.js
  packages/typography/src/elements/lists/UnorderedList.tsx
  packages/typography/src/elements/lists/UnorderedListItem.spec.js
  packages/typography/src/elements/lists/UnorderedListItem.tsx
  packages/typography/src/index.ts
  packages/typography/src/styled/StyledCode.ts
  packages/typography/src/styled/StyledFont.spec.js
  packages/typography/src/styled/StyledFont.tsx
  packages/typography/src/styled/StyledListItem.ts
  packages/typography/src/utils/useOrderedListContext.spec.tsx
  packages/typography/src/utils/useUnorderedListContext.spec.tsx
  packages/typography/styleguide.config.js
Labels: PR: Breaking Change :boom:

#523 chore(theming): use consistent `elements` directory for exports
  packages/theming/examples/default-theme.md
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.spec.ts
  packages/theming/src/elements/palette/index.ts
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.spec.ts
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/index.ts
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
  packages/theming/src/utils/withTheme.spec.tsx
  packages/theming/src/utils/withTheme.ts
  packages/theming/styleguide.config.js
Labels: PR: Docs :memo:

#519 fix(buttons): apply `isBoolean` prop updates and knob-style examples
  BREAKING_CHANGES.md
  packages/buttons/examples/advanced.md
  packages/buttons/examples/anchor.md
  packages/buttons/examples/basic.md
  packages/buttons/examples/button-group.md
  packages/buttons/examples/button.md
  packages/buttons/examples/icon-button.md
  packages/buttons/examples/split-button.md
  packages/buttons/package.json
  packages/buttons/src/elements/Anchor.spec.tsx
  packages/buttons/src/elements/Anchor.tsx
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/ButtonGroup.spec.tsx
  packages/buttons/src/elements/ButtonGroup.tsx
  packages/buttons/src/elements/ChevronButton.spec.tsx
  packages/buttons/src/elements/ChevronButton.tsx
  packages/buttons/src/elements/IconButton.spec.tsx
  packages/buttons/src/elements/IconButton.tsx
  packages/buttons/src/elements/SplitButton.spec.tsx
  packages/buttons/src/elements/SplitButton.tsx
  packages/buttons/src/index.ts
  packages/buttons/src/styled/StyledAnchor.spec.tsx
  packages/buttons/src/styled/StyledAnchor.ts
  packages/buttons/src/styled/StyledButton.spec.tsx
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledExternalIcon.ts
  packages/buttons/src/styled/StyledIcon.spec.tsx
  packages/buttons/src/styled/StyledIcon.ts
  packages/buttons/src/styled/StyledIconButton.ts
  packages/buttons/styleguide.config.js
  packages/loaders/examples/skeleton.md
  packages/theming/examples/default-theme.md
  utils/styleguide/TableOfContentsRenderer/index.js
Labels: PR: Breaking Change :boom:

#525 fix(tags): use controlled components in tags example
  packages/tags/examples/advanced.md
  packages/tags/examples/basic.md
Labels: PR: Bug Fix :bug:

#528 feat(grid): migrate to TS and update API
  BREAKING_CHANGES.md
  packages/grid/examples/basic.md
  packages/grid/package.json
  packages/grid/src/elements/Col.spec.tsx
  packages/grid/src/elements/Col.tsx
  packages/grid/src/elements/Grid.spec.tsx
  packages/grid/src/elements/Grid.tsx
  packages/grid/src/elements/Row.spec.tsx
  packages/grid/src/elements/Row.tsx
  packages/grid/src/index.spec.js
  packages/grid/src/index.ts
  packages/grid/src/styled/StyledCol.spec.tsx
  packages/grid/src/styled/StyledCol.ts
  packages/grid/src/styled/StyledGrid.spec.tsx
  packages/grid/src/styled/StyledGrid.ts
  packages/grid/src/styled/StyledRow.spec.tsx
  packages/grid/src/styled/StyledRow.ts
  packages/grid/src/styled/index.ts
  packages/grid/src/views/Col.spec.js
  packages/grid/src/views/Row.spec.js
  packages/grid/styleguide.config.js
  packages/grid/tsconfig.build.json
  utils/build/declarations.d.ts
Labels: PR: Breaking Change :boom:

#547 Allow the portal container to be passed in as a prop
  packages/modals/src/elements/Modal.js
  packages/modals/src/elements/Modal.spec.js
Labels: PR: New Feature :rocket:
