Repository zendeskgarden/react-components, pull requests merged in 2019-09, with the labels that each got.

#437 fix(test): mock scrollTo dom-helper utility in tests
  __mocks__/dom-helpers/util/scrollTo.js
Labels: PR: Internal :seedling:

#432 feat(theming): upgrade Theming to use TypeScript
  .travis.yml
  lint-staged.config.js
  packages/datepickers/src/Datepicker/Datepicker.tsx
  packages/dropdowns/src/Dropdown/Dropdown.tsx
  packages/dropdowns/src/Menu/Menu.tsx
  packages/theming/package.json
  packages/theming/src/ThemeProvider.js
  packages/theming/src/ThemeProvider.tsx
  packages/theming/src/index.ts
  packages/theming/src/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/palette/index.spec.ts
  packages/theming/src/palette/index.ts
  packages/theming/src/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/theme/index.spec.ts
  packages/theming/src/theme/index.ts
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
  packages/theming/src/utils/getDocument.spec.ts
  packages/theming/src/utils/getDocument.ts
  packages/theming/src/utils/isRtl.spec.ts
  packages/theming/src/utils/isRtl.ts
  packages/theming/src/utils/retrieveComponentStyles.spec.ts
  packages/theming/src/utils/retrieveComponentStyles.ts
  packages/theming/src/utils/withTheme.example.md
  packages/theming/src/utils/withTheme.spec.tsx
  packages/theming/src/utils/withTheme.ts
  packages/theming/styleguide.config.js
  packages/theming/tsconfig.build.json
  tsconfig.json
  utils/build/declarations.d.ts
  utils/build/styled.d.ts
Labels: PR: New Feature :rocket:

#443 feat(tags): migrate react-tags to TypeScript
  packages/tags/package.json
  packages/tags/src/components/Close.spec.tsx
  packages/tags/src/components/Close.tsx
  packages/tags/src/components/Tag.js
  packages/tags/src/components/Tag.spec.tsx
  packages/tags/src/components/Tag.tsx
  packages/tags/src/index.ts
  packages/tags/src/styled/StyledAvatar.spec.tsx
  packages/tags/src/styled/StyledAvatar.ts
  packages/tags/src/styled/StyledClose.spec.tsx
  packages/tags/src/styled/StyledClose.ts
  packages/tags/src/styled/StyledTag.spec.tsx
  packages/tags/src/styled/StyledTag.ts
  packages/tags/src/styled/index.ts
  packages/tags/styleguide.config.js
  packages/tags/tsconfig.build.json
Labels: PR: New Feature :rocket:

#447 fix(dropdowns): Fix invalid ARIA role
  packages/dropdowns/src/examples/autocomplete.md
Labels: PR: Docs :memo:

#444 feat(breadcrumbs): deprecate BreadcrumbContainer and migrate to useBreadcrumb() container
  packages/breadcrumbs/package.json
  packages/breadcrumbs/src/containers/BreadcrumbContainer.example.md
  packages/breadcrumbs/src/containers/BreadcrumbContainer.js
  packages/breadcrumbs/src/elements/Breadcrumb.js
Labels: PR: New Feature :rocket:, v7 :evergreen_tree:

#449 chore(build): add bundleSize check to all packages
  .travis.yml
  bundlesize.config.js
  package.json
  packages/autocomplete/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/checkboxes/package.json
  packages/chrome/package.json
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/menus/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/radios/package.json
  packages/ranges/package.json
  packages/select/package.json
  packages/selection/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/textfields/package.json
  packages/theming/package.json
  packages/toggles/package.json
  packages/tooltips/package.json
  packages/typography/package.json
  packages/utilities/package.json
  yarn.lock
Labels: PR: Internal :seedling:

#448 feat(tabs): deprecate TabsContainer component
  packages/.template/package.json
  packages/breadcrumbs/src/containers/BreadcrumbContainer.example.md
  packages/breadcrumbs/src/containers/BreadcrumbContainer.js
  packages/tabs/package.json
  packages/tabs/src/containers/TabsContainer.example.md
  packages/tabs/src/containers/TabsContainer.js
  packages/tabs/src/elements/Tabs.js
  packages/tabs/src/elements/Tabs.spec.js
  packages/tabs/src/views/Tab.js
  packages/tabs/src/views/TabPanel.js
Labels: PR: New Feature :rocket:

#451 feat(tooltips): deprecate TooltipContainer and migrate to useTooltip
  packages/autocomplete/package.json
  packages/menus/package.json
  packages/select/package.json
  packages/tooltips/package.json
  packages/tooltips/src/containers/TooltipContainer.example.md
  packages/tooltips/src/containers/TooltipContainer.js
  packages/tooltips/src/elements/Tooltip.js
  packages/tooltips/src/elements/Tooltip.spec.js
Labels: PR: New Feature :rocket:

#453 feat(pagination): deprecate PaginationContainer and migrate to container-pagination
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/dropdowns/src/Dropdown/Dropdown.tsx
  packages/dropdowns/src/Fields/Label.tsx
  packages/forms/package.json
  packages/pagination/package.json
  packages/pagination/src/containers/PaginationContainer.example.md
  packages/pagination/src/containers/PaginationContainer.js
  packages/pagination/src/elements/Pagination.js
  packages/pagination/src/elements/Pagination.spec.js
  packages/tabs/package.json
  packages/tooltips/package.json
  utils/build/declarations.d.ts
Labels: PR: New Feature :rocket:

#456 feat(modals): deprecate FocusJailContainer and ModalContainer
  packages/autocomplete/package.json
  packages/menus/package.json
  packages/modals/package.json
  packages/modals/src/containers/FocusJailContainer.example.md
  packages/modals/src/containers/FocusJailContainer.js
  packages/modals/src/containers/ModalContainer.example.md
  packages/modals/src/containers/ModalContainer.js
  packages/modals/src/elements/Modal.js
  packages/select/package.json
Labels: PR: New Feature :rocket:

#439 feat(dropdowns): introduce Multiselect component
  .lintstagedrc
  lint-staged.config.js
  packages/dropdowns/examples/autocomplete.md
  packages/dropdowns/examples/examples.md
  packages/dropdowns/examples/menu.md
  packages/dropdowns/examples/multiselect.md
  packages/dropdowns/examples/select.md
  packages/dropdowns/package.json
  packages/dropdowns/src/Dropdown/Dropdown.spec.tsx
  packages/dropdowns/src/Dropdown/Dropdown.tsx
  packages/dropdowns/src/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/Multiselect/Multiselect.tsx
  packages/dropdowns/src/index.ts
  packages/dropdowns/src/styled/field/StyledMultiselect.tsx
  packages/dropdowns/src/styled/index.ts
  packages/dropdowns/styleguide.config.js
Labels: PR: New Feature :rocket:

#450 feat(avatars): CSS-in-JS refactor
  BREAKING_CHANGES.md
  packages/avatars/README.md
  packages/avatars/examples/advanced.md
  packages/avatars/examples/basic.md
  packages/avatars/package.json
  packages/avatars/src/Avatar.example.md
  packages/avatars/src/Avatar.js
  packages/avatars/src/Avatar.spec.js
  packages/avatars/src/components/Avatar.js
  packages/avatars/src/components/Avatar.spec.js
  packages/avatars/src/index.js
  packages/avatars/src/styled.js
  packages/avatars/src/styled.spec.js
  packages/avatars/src/styled/StyledAvatar.js
  packages/avatars/src/styled/StyledAvatar.spec.js
  packages/avatars/src/styled/StyledText.js
  packages/avatars/src/styled/StyledText.spec.js
  packages/avatars/src/styled/index.js
  packages/avatars/styleguide.config.js
Labels: PR: Breaking Change :boom:

#458 chore: update renovate configuration
  .github/CODEOWNERS
  renovate.json
Labels: PR: Internal :seedling:

#459 fix(modals): allow Modal to receive ref prop
  packages/modals/src/elements/Modal.js
  packages/modals/src/index.spec.js
  packages/modals/src/utils/useCombinedRefs.js
  packages/modals/src/utils/useCombinedRefs.spec.js
Labels: PR: Bug Fix :bug:

#460 feat(buttons): deprecate ButtonGroupContainer
  packages/autocomplete/package.json
  packages/buttons/package.json
  packages/buttons/src/containers/ButtonGroupContainer.example.md
  packages/buttons/src/containers/ButtonGroupContainer.js
  packages/buttons/src/elements/ButtonGroup.js
  packages/buttons/src/elements/ButtonGroup.spec.js
  packages/menus/package.json
  packages/tabs/package.json
Labels: PR: New Feature :rocket:

#461 feat(chrome): deprecate AccordionContainer
  packages/chrome/package.json
  packages/chrome/src/containers/AccordionContainer.example.md
  packages/chrome/src/containers/AccordionContainer.js
  packages/chrome/src/views/subnav/CollapsibleSubNavItem.js
Labels: PR: New Feature :rocket:

#464 fix(avatars): prevent badge `content-box` sizing overrides
  packages/avatars/package.json
Labels: PR: Bug Fix :bug:

#466 chore: update renovate schedule
  renovate.json
Labels: PR: Internal :seedling:

#477 feat(avatars): migrate to TypeScript
  packages/avatars/package.json
  packages/avatars/src/components/Avatar.spec.tsx
  packages/avatars/src/components/Avatar.tsx
  packages/avatars/src/index.ts
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/src/styled/StyledText.spec.tsx
  packages/avatars/src/styled/StyledText.ts
  packages/avatars/src/styled/index.ts
  packages/avatars/styleguide.config.js
  packages/avatars/tsconfig.build.json
Labels: PR: New Feature :rocket:

#478 fix(build): revert react-docgen-typescript upgrade
  package.json
  yarn.lock
Labels: PR: Internal :seedling:
