Repository zendeskgarden/react-components, pull requests merged in 2019-07, with the labels that each got.

#373 feat(datepickers): introduce Datepicker component
  README.md
  babel.config.js
  demo/index.html
  package.json
  packages/datepickers/README.md
  packages/datepickers/package.json
  packages/datepickers/src/Datepicker.spec.tsx
  packages/datepickers/src/Datepicker.tsx
  packages/datepickers/src/components/Calendar.tsx
  packages/datepickers/src/components/MonthSelector.tsx
  packages/datepickers/src/examples/compact.md
  packages/datepickers/src/examples/custom-formats.md
  packages/datepickers/src/examples/default-usage.md
  packages/datepickers/src/examples/examples.md
  packages/datepickers/src/examples/localization.md
  packages/datepickers/src/examples/min-max-dates.md
  packages/datepickers/src/index.ts
  packages/datepickers/src/styled/index.ts
  packages/datepickers/src/styled/styled-datepicker.tsx
  packages/datepickers/src/styled/styled-menu.spec.tsx
  packages/datepickers/src/styled/styled-menu.tsx
  packages/datepickers/src/utils/calendar-utils.spec.ts
  packages/datepickers/src/utils/calendar-utils.ts
  packages/datepickers/src/utils/garden-placements.spec.ts
  packages/datepickers/src/utils/garden-placements.ts
  packages/datepickers/src/utils/reducer.ts
  packages/datepickers/src/utils/useDatepickerContext.ts
  packages/datepickers/styleguide.config.js
  packages/datepickers/tsconfig.build.json
  utils/build/declarations.d.ts
  utils/build/webpack.base.js
  utils/styleguide/styleguide.base.config.js
  yarn.lock
Labels: PR: New Feature :rocket:

#379 fix(notifications): show correct Notification and Alert styling
  packages/notifications/src/Alert.js
  packages/notifications/src/Alert.spec.js
  packages/notifications/src/Notification.js
  packages/notifications/src/Notification.spec.js
Labels: PR: Bug Fix :bug:

#386 fix(dropdowns): remove webkit button styling when used with css-bedrock
  packages/dropdowns/src/styled/field/StyledSelect.ts
Labels: PR: Bug Fix :bug:

#388 feat(typography): add `List` component
  packages/typography/examples/list.md
  packages/typography/src/index.js
  packages/typography/src/index.spec.js
  packages/typography/src/views/lists/OrderedList.example.md
  packages/typography/src/views/lists/OrderedList.js
  packages/typography/src/views/lists/OrderedList.spec.js
  packages/typography/src/views/lists/OrderedListItem.js
  packages/typography/src/views/lists/OrderedListItem.spec.js
  packages/typography/src/views/lists/UnorderedList.example.md
  packages/typography/src/views/lists/UnorderedList.js
  packages/typography/src/views/lists/UnorderedList.spec.js
  packages/typography/src/views/lists/UnorderedListItem.js
  packages/typography/src/views/lists/UnorderedListItem.spec.js
  packages/typography/src/views/lists/styles.js
  packages/typography/src/views/lists/useOrderedListContext.js
  packages/typography/src/views/lists/useOrderedListContext.spec.js
  packages/typography/src/views/lists/useUnorderedListContext.js
  packages/typography/src/views/lists/useUnorderedListContext.spec.js
  packages/typography/styleguide.config.js
Labels: PR: New Feature :rocket:

#391 fix(dropdowns): allow previous item selection with arrow key
  packages/dropdowns/src/Dropdown/Dropdown.tsx
  packages/dropdowns/src/examples/menu.md
Labels: PR: Bug Fix :bug:

#393 chore(datepicker): update examples to include correct localization names
  packages/datepickers/README.md
  packages/datepickers/src/Datepicker.tsx
  packages/datepickers/src/examples/localization.md
Labels: PR: Docs :memo:

#394 Update autocomplete dropdown example due to google translate issue
  packages/dropdowns/src/examples/autocomplete.md
Labels: PR: Docs :memo:

#370 feat(loaders): Replace ScheduleContainer with useSchedule hook
  BREAKING_CHANGES.md
  packages/loaders/package.json
  packages/loaders/src/Dots.example.md
  packages/loaders/src/Dots.js
  packages/loaders/src/Dots.spec.js
  packages/loaders/src/Spinner.js
  packages/loaders/src/Spinner.spec.js
  packages/loaders/src/containers/ScheduleContainer.js
  packages/loaders/src/hooks/useCSSSVGAnimation.js
  packages/loaders/src/styled-elements.js
  packages/loaders/src/styled-elements.spec.js
  packages/loaders/src/utils/animations.js
  packages/loaders/src/utils/animations.spec.js
  packages/loaders/src/utils/dot-coordinates.js
  packages/loaders/src/utils/dot-coordinates.spec.js
Labels: PR: Breaking Change :boom:

#396 fix(buttons): allow correct ref validation in PropTypes
  packages/buttons/src/views/icon-button/ChevronButton.js
  packages/buttons/src/views/icon-button/IconButton.js
Labels: PR: Bug Fix :bug:
