Repository zendeskgarden/react-components, pull requests merged in 2019-08, with the labels that each got.

#398 fix(buttons): white-space/word-wrap styling in the Anchor component
  packages/buttons/src/views/Anchor.js
Labels: PR: Bug Fix :bug:

#402 feat(Menu/Items/Item): change Item 'value' requirement to be inclusive of 0
  packages/dropdowns/src/Menu/Items/Item.ts
Labels: PR: Bug Fix :bug:

#397 feat(datepickers): introduce DatepickerRange component
  packages/datepickers/examples/compact.md
  packages/datepickers/examples/custom-formats.md
  packages/datepickers/examples/default-usage.md
  packages/datepickers/examples/examples.md
  packages/datepickers/examples/localization.md
  packages/datepickers/examples/min-max-dates.md
  packages/datepickers/examples/range.md
  packages/datepickers/src/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/Datepicker/Datepicker.tsx
  packages/datepickers/src/Datepicker/components/Calendar.tsx
  packages/datepickers/src/Datepicker/components/MonthSelector.tsx
  packages/datepickers/src/Datepicker/utils/datepicker-reducer.ts
  packages/datepickers/src/Datepicker/utils/garden-placements.spec.ts
  packages/datepickers/src/Datepicker/utils/garden-placements.ts
  packages/datepickers/src/Datepicker/utils/useDatepickerContext.ts
  packages/datepickers/src/DatepickerRange/DatepickerRange.spec.tsx
  packages/datepickers/src/DatepickerRange/DatepickerRange.tsx
  packages/datepickers/src/DatepickerRange/components/Calendar.tsx
  packages/datepickers/src/DatepickerRange/components/End.spec.tsx
  packages/datepickers/src/DatepickerRange/components/End.tsx
  packages/datepickers/src/DatepickerRange/components/Month.tsx
  packages/datepickers/src/DatepickerRange/components/Start.spec.tsx
  packages/datepickers/src/DatepickerRange/components/Start.tsx
  packages/datepickers/src/DatepickerRange/utils/datepicker-range-reducer.ts
  packages/datepickers/src/DatepickerRange/utils/useDatepickerRangeContext.ts
  packages/datepickers/src/index.ts
  packages/datepickers/src/styled/styled-datepicker.tsx
  packages/datepickers/src/styled/styled-menu.spec.tsx
  packages/datepickers/src/styled/styled-menu.tsx
  packages/datepickers/src/utils/calendar-utils.spec.ts
  packages/datepickers/styleguide.config.js
  utils/test/jest.d.ts
Labels: PR: New Feature :rocket:

#409 fix(build): correct prettier error to release
  packages/datepickers/examples/range.md
Labels: PR: Bug Fix :bug:

#413 chore: add bundle size badges
  README.md
Labels: PR: Docs :memo:

#412 chore: organize theming package
  packages/avatars/src/Avatar.example.md
  packages/chrome/src/containers/AccordionContainer.example.md
  packages/dropdowns/src/examples/menu.md
  packages/dropdowns/src/examples/select.md
  packages/loaders/src/Dots.example.md
  packages/loaders/src/Inline.example.md
  packages/loaders/src/Skeleton.example.md
  packages/loaders/src/Spinner.example.md
  packages/tables/src/examples/paginated-table.md
  packages/theming/examples/default-theme.md
  packages/theming/examples/palette.md
  packages/theming/examples/theme-provider.md
  packages/theming/src/ThemeProvider.js
  packages/theming/src/index.js
  packages/theming/src/index.spec.js
  packages/theming/styleguide.config.js
  utils/styleguide/setup.js
Labels: PR: Internal :seedling:

#421 docs: correct react-theming peer dependencies
  packages/theming/README.md
Labels: PR: Docs :memo:

#415 fix(datepicker): correct minValue and maxValue displays and allow same date selection within Range
  packages/datepickers/examples/range.md
  packages/datepickers/src/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/Datepicker/components/Calendar.tsx
  packages/datepickers/src/DatepickerRange/DatepickerRange.spec.tsx
  packages/datepickers/src/DatepickerRange/components/Month.tsx
  packages/datepickers/src/DatepickerRange/utils/datepicker-range-reducer.ts
Labels: PR: Bug Fix :bug:
