Repository zendeskgarden/react-components, pull requests merged in 2019-10, with the labels that each got.

#479 chore(selection): remove usages of react-selection KEY_CODES and composeEventHandlers
  packages/modals/package.json
  packages/modals/src/elements/Modal.spec.js
  packages/modals/src/views/Close.js
  packages/pagination/package.json
  packages/pagination/src/elements/Pagination.spec.js
  packages/tables/package.json
  packages/tables/src/views/OverflowButton.js
  packages/tables/src/views/Row.js
  packages/tags/package.json
  packages/tags/src/views/Close.example.md
  utils/build/declarations.d.ts
Labels: PR: Internal :seedling:

#468 feat(loaders): introduce Progress component
  packages/loaders/README.md
  packages/loaders/src/Progress.example.md
  packages/loaders/src/Progress.js
  packages/loaders/src/Progress.spec.js
  packages/loaders/src/index.js
Labels: PR: New Feature :rocket:

#463 feat(forms): deprecate react-ranges and migrate components to react-forms
  demo/index.html
  packages/forms/examples/multi-thumb-range.md
  packages/forms/examples/range.md
  packages/forms/package.json
  packages/forms/src/fields/MultiThumbRange.js
  packages/forms/src/fields/MultiThumbRange.spec.js
  packages/forms/src/fields/Range.js
  packages/forms/src/fields/Range.spec.js
  packages/forms/src/fields/common/Field.js
  packages/forms/src/fields/other/MediaInput.spec.js
  packages/forms/src/index.js
  packages/forms/src/styled/StyledField.js
  packages/forms/src/styled/StyledField.spec.js
  packages/forms/src/styled/index.js
  packages/forms/src/styled/range/StyledRangeSingleThumb.js
  packages/forms/src/styled/range/StyledRangeSingleThumb.spec.js
  packages/forms/src/styled/text/StyledTextLabel.js
  packages/forms/styleguide.config.js
  packages/loaders/src/Dots.example.md
  packages/loaders/src/Spinner.example.md
  packages/ranges/src/index.js
  packages/typography/examples/list.md
  utils/scripts/version.sh
Labels: PR: New Feature :rocket:

#480 fix(forms): allow MediaInput to receive all possible ref values
  packages/forms/src/fields/other/MediaInput.js
Labels: PR: Bug Fix :bug:

#481 fix(datepicker): ensure mouse events are propogated correctly
  packages/datepickers/src/DatepickerRange/utils/datepicker-range-reducer.ts
  packages/datepickers/src/styled/styled-datepicker.tsx
Labels: PR: Bug Fix :bug:

#462 feat(loaders): deprecate ScheduleContainer BREAKING
  packages/loaders/package.json
  packages/loaders/src/Dots.example.md
  packages/loaders/src/Dots.js
  packages/loaders/src/Dots.spec.js
  packages/loaders/src/Progress.example.md
  packages/loaders/src/Skeleton.js
  packages/loaders/src/Spinner.js
  packages/loaders/src/Spinner.spec.js
  packages/loaders/src/containers/ScheduleContainer.example.md
  packages/loaders/src/containers/ScheduleContainer.js
  packages/loaders/src/containers/ScheduleContainer.spec.js
  packages/loaders/src/hooks/useCSSSVGAnimation.js
  packages/loaders/src/styled-elements.js
  packages/loaders/src/styled-elements.spec.js
  packages/loaders/src/utils/animations.js
  packages/loaders/src/utils/animations.spec.js
  packages/loaders/src/utils/dot-coordinates.js
  packages/loaders/src/utils/dot-coordinates.spec.js
  packages/loaders/styleguide.config.js
Labels: PR: Breaking Change :boom:

#491 feat(loaders): deprecate ScheduleContainer BREAKING
  packages/loaders/package.json
  packages/loaders/src/Dots.example.md
  packages/loaders/src/Dots.js
  packages/loaders/src/Dots.spec.js
  packages/loaders/src/Progress.example.md
  packages/loaders/src/Skeleton.js
  packages/loaders/src/Spinner.js
  packages/loaders/src/Spinner.spec.js
  packages/loaders/src/containers/ScheduleContainer.example.md
  packages/loaders/src/containers/ScheduleContainer.js
  packages/loaders/src/containers/ScheduleContainer.spec.js
  packages/loaders/src/hooks/useCSSSVGAnimation.js
  packages/loaders/src/styled-elements.js
  packages/loaders/src/styled-elements.spec.js
  packages/loaders/src/utils/animations.js
  packages/loaders/src/utils/animations.spec.js
  packages/loaders/src/utils/dot-coordinates.js
  packages/loaders/src/utils/dot-coordinates.spec.js
  packages/loaders/styleguide.config.js
Labels: PR: Breaking Change :boom:

#485 chore(internal): remove all deprecated render-prop containers BREAKING
  .github/CONTRIBUTING.md
  API.md
  package.json
  packages/breadcrumbs/src/containers/BreadcrumbContainer.example.md
  packages/breadcrumbs/src/containers/BreadcrumbContainer.js
  packages/breadcrumbs/src/containers/BreadcrumbContainer.spec.js
  packages/breadcrumbs/src/elements/Breadcrumb.spec.js
  packages/breadcrumbs/src/index.js
  packages/breadcrumbs/styleguide.config.js
  packages/buttons/src/containers/ButtonGroupContainer.example.md
  packages/buttons/src/containers/ButtonGroupContainer.js
  packages/buttons/src/containers/ButtonGroupContainer.spec.js
  packages/buttons/src/elements/ButtonGroup.example.md
  packages/buttons/src/index.js
  packages/buttons/src/views/button-group/ButtonGroupView.example.md
  packages/buttons/styleguide.config.js
  packages/chrome/src/containers/AccordionContainer.example.md
  packages/chrome/src/containers/AccordionContainer.js
  packages/chrome/src/containers/AccordionContainer.spec.js
  packages/chrome/src/index.js
  packages/chrome/styleguide.config.js
  packages/modals/src/containers/FocusJailContainer.example.md
  packages/modals/src/containers/FocusJailContainer.js
  packages/modals/src/containers/FocusJailContainer.spec.js
  packages/modals/src/containers/ModalContainer.example.md
  packages/modals/src/containers/ModalContainer.js
  packages/modals/src/containers/ModalContainer.spec.js
  packages/modals/src/elements/Modal.example.md
  packages/modals/src/index.js
  packages/modals/src/views/ModalView.example.md
  packages/modals/styleguide.config.js
  packages/pagination/src/containers/PaginationContainer.example.md
  packages/pagination/src/containers/PaginationContainer.js
  packages/pagination/src/containers/PaginationContainer.spec.js
  packages/pagination/src/index.js
  packages/pagination/styleguide.config.js
  packages/tabs/src/containers/TabsContainer.example.md
  packages/tabs/src/containers/TabsContainer.js
  packages/tabs/src/containers/TabsContainer.spec.js
  packages/tabs/src/elements/Tabs.example.md
  packages/tabs/src/index.js
  packages/tabs/styleguide.config.js
  packages/tooltips/README.md
  packages/tooltips/src/containers/TooltipContainer.example.md
  packages/tooltips/src/containers/TooltipContainer.js
  packages/tooltips/src/containers/TooltipContainer.spec.js
  packages/tooltips/src/elements/Tooltip.example.md
  packages/tooltips/src/index.js
  packages/tooltips/styleguide.config.js
Labels: PR: Breaking Change :boom:

#486 chore(internal): deprecated react-selection and migrate Tabs and Pagination components BREAKING
  README.md
  demo/index.html
  packages/buttons/package.json
  packages/chrome/package.json
  packages/modals/package.json
  packages/pagination/package.json
  packages/pagination/src/elements/Pagination.example.md
  packages/pagination/src/elements/Pagination.js
  packages/pagination/src/elements/Pagination.spec.js
  packages/selection/src/index.js
  packages/tabs/package.json
  packages/tabs/src/elements/Tabs.example.md
  packages/tabs/src/elements/Tabs.js
  packages/tabs/src/elements/Tabs.spec.js
  packages/tooltips/package.json
  utils/styleguide/styleguide.base.config.js
Labels: PR: Breaking Change :boom:

#490 chore(deps): update dom-helpers
  __mocks__/dom-helpers/scrollTo.js
  packages/buttons/package.json
  packages/modals/package.json
  packages/modals/src/elements/Modal.js
  packages/selection/package.json
  packages/selection/src/containers/SelectionContainer.js
  packages/tables/package.json
  packages/tables/src/views/Table.js
Labels: PR: Internal :seedling:

#487 chore(internal): update react-popper dependencies
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/tooltips/package.json
  packages/tooltips/src/elements/Tooltip.js
Labels: PR: Internal :seedling:

#495 chore(deps): upgrade react-theming peerDependencies to allow v7
  packages/.template/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/selection/package.json
  packages/tables/package.json
  packages/tables/src/examples/paginated-table.md
  packages/tabs/package.json
  packages/tabs/src/elements/Tabs.spec.js
  packages/tags/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Internal :seedling:

#496 chore(internal): upgrade Garden examples to v7
  examples/codesandbox/garden-create-react-app/package.json
  examples/codesandbox/garden-create-react-app/yarn.lock
  examples/nextjs/.babelrc
  examples/nextjs/next.config.js
  examples/nextjs/package.json
  examples/nextjs/pages/_app.js
  examples/nextjs/pages/_document.js
  examples/nextjs/yarn.lock
Labels: PR: Docs :memo:

#498 fix(buttons): allow buttons to control type attribute
  packages/buttons/src/views/Button.js
Labels: PR: Bug Fix :bug:

#499 fix(buttons): allow buttons to control type attribute (#498) [BACKPORT v6]
  packages/buttons/src/views/Button.js
Labels: PR: Bug Fix :bug:
