Repository zendeskgarden/react-components, pull requests merged in 2020-02, with the labels that each got.

#608 fix(build): correct failing tests
  packages/pagination/src/elements/Pagination.spec.js
Labels: PR: Bug Fix :bug:

#606 feat(tables): theming color design updates
  packages/tables/examples/virtual-table.md
  packages/tables/src/elements/OverflowButton.spec.tsx
  packages/tables/src/styled/StyledOverflowButton.ts
  packages/tables/src/styled/StyledRow.ts
Labels: PR: New Feature :rocket:

#607 fix(dropdowns): overflow in Multiselect items
  packages/dropdowns/examples/multiselect.md
  packages/dropdowns/src/styled/field/StyledMultiselect.tsx
Labels: PR: Bug Fix :bug:

#613 fix(dropdowns): limit PopperJS computations while dropdowns are closed
  packages/dropdowns/src/Dropdown/Dropdown.tsx
  packages/dropdowns/src/Menu/Menu.tsx
Labels: PR: Bug Fix :bug:

#612 chore: cleanup `.template` etc in prep for v8
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/development.md
  docs/versioning.md
  package.json
  packages/.template/README.md
  packages/.template/examples/basic.md
  packages/.template/package.json
  packages/.template/src/Example.example.md
  packages/.template/src/Example.js
  packages/.template/src/elements/Example.spec.tsx
  packages/.template/src/elements/Example.tsx
  packages/.template/src/index.spec.js
  packages/.template/src/index.ts
  packages/.template/src/styled/StyledExample.spec.tsx
  packages/.template/src/styled/StyledExample.ts
  packages/.template/src/styled/index.ts
  packages/.template/styleguide.config.js
  packages/.template/tsconfig.build.json
  utils/test/jest.config.js
  utils/test/rootDir/__mocks__/dom-helpers/scrollTo.js
  utils/test/rootDir/__mocks__/popper.js.js
Labels: PR: Internal :seedling:

#609 perf(loaders): prevent rerender for dots
  packages/loaders/src/Dots.js
  packages/loaders/src/Dots.spec.js
Labels: PR: Bug Fix :bug:

#617 fix(tags): utilize `border-box` box sizing model
  packages/tags/examples/advanced.md
  packages/tags/examples/basic.md
  packages/tags/src/styled/StyledTag.ts
Labels: PR: Bug Fix :bug:

#618 fix(dropdowns): allow forwardRef usage of Select component
  packages/dropdowns/src/Select/Select.tsx
  packages/dropdowns/src/index.ts
Labels: PR: Bug Fix :bug:

#616 fix(notifications): Add ARIA role to Notification components
  packages/notifications/examples/basic.md
  packages/notifications/src/elements/Alert.spec.tsx
  packages/notifications/src/elements/Notification.spec.tsx
  packages/notifications/src/styled/StyledAlert.ts
  packages/notifications/src/styled/StyledNotification.ts
Labels: PR: Bug Fix :bug:

#623 fix(build): move from uglify to terser for UMD builds
  .lintstagedrc
  package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/tooltips/package.json
  utils/build/webpack.umd.js
  yarn.lock
Labels: PR: Bug Fix :bug:

#629 fix(deps): ensure all garden container packages support ie11
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/tooltips/package.json
Labels: PR: Bug Fix :bug:

#637 fix(build): allow lerna to publish under non-latest tag
  lerna.json
  packages/datepickers/package.json
Labels: PR: Internal :seedling:

#640 feat(build): allow all packages to consume v8 theming
  packages/.template/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/selection/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Bug Fix :bug:

#641 feat(examples): migrate create-react-app example to v8
  examples/codesandbox/garden-create-react-app/package.json
  examples/codesandbox/garden-create-react-app/src/components/ExampleWrapper.js
  examples/codesandbox/garden-create-react-app/src/examples/Example.js
  examples/codesandbox/garden-create-react-app/src/global-styling.js
  examples/codesandbox/garden-create-react-app/src/index.js
  examples/codesandbox/garden-create-react-app/yarn.lock
Labels: PR: Docs :memo:

#642 chore(docs): add link to v7 docs
  demo/index.html
Labels: PR: Docs :memo:

#644 chore(docs): add link to v6 documentation
  demo/index.html
Labels: PR: Docs :memo:

#643 chore(docs): update v7 documentation link
  demo/index.html
Labels: PR: Docs :memo:

#646 fix(datepickers): ensure animation is positioned correctly
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
  packages/datepickers/src/styled/StyledMenu.tsx
Labels: PR: Bug Fix :bug:

#647 fix(dropdowns): remove invalid aria-labelledby value from Trigger
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
Labels: PR: Bug Fix :bug:

#650 chore(modals): update container dependencies
  packages/modals/package.json
  packages/modals/yarn.lock
Labels: PR: Internal :seedling:

#649 chore(all): increase test coverage
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/buttons/.size-snapshot.json
  packages/buttons/src/elements/Button.tsx
  packages/chrome/src/elements/header/HeaderItem.spec.tsx
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/elements/subnav/SubNav.spec.tsx
  packages/chrome/src/elements/subnav/SubNavItem.spec.tsx
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/elements/Datepicker/utils/datepicker-reducer.ts
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.spec.tsx
  packages/datepickers/src/styled/StyledMenu.tsx
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns/src/elements/Fields/Hint.spec.tsx
  packages/dropdowns/src/elements/Fields/Label.spec.tsx
  packages/dropdowns/src/elements/Fields/Label.tsx
  packages/dropdowns/src/elements/Fields/Message.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaFigure.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/styled/field/SelectWrapper.tsx
  packages/dropdowns/src/styled/menu/StyledMenu.tsx
  packages/dropdowns/src/utils/gardenPlacements.spec.ts
  packages/forms/src/elements/MultiThumbRange.spec.tsx
  packages/forms/src/elements/MultiThumbRange.tsx
  packages/loaders/.size-snapshot.json
  packages/loaders/src/styled/StyledProgress.ts
  packages/loaders/src/utils/useCSSSVGAnimation.spec.tsx
  packages/modals/src/utils/useModalContext.spec.tsx
  packages/notifications/src/elements/content/Title.spec.tsx
  packages/tables/src/elements/Cell.spec.tsx
  packages/tables/src/elements/HeaderCell.spec.tsx
  packages/tables/src/elements/HeaderRow.spec.tsx
  packages/tables/src/elements/OverflowButton.spec.tsx
  packages/tables/src/elements/Row.spec.tsx
  packages/tables/src/elements/SortableCell.spec.tsx
  packages/tags/src/styled/StyledTag.spec.tsx
  packages/theming/.size-snapshot.json
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.spec.ts
  packages/theming/src/utils/getLineHeight.spec.ts
  packages/theming/src/utils/withTheme.spec.tsx
  packages/theming/src/utils/withTheme.ts
  packages/tooltips/src/elements/Tooltip.spec.tsx
Labels: PR: Internal :seedling:

#648 chore: update documentation for v8
  .github/CONTRIBUTING.md
  README.md
  docs/api.md
  docs/development.md
  docs/versioning.md
  examples/codesandbox/garden-create-react-app/src/components/ExampleWrapper.js
  examples/codesandbox/garden-create-react-app/src/examples/Example.js
Labels: PR: Docs :memo:

#652 docs(modals): include a11y note on restoring focus
  packages/modals/examples/basic.md
Labels: PR: Docs :memo:

#653 chore(markdown): include package examples in lint:markdown
  package.json
  packages/typography/examples/lists.md
Labels: PR: Internal :seedling:
