Repository zendeskgarden/react-components, pull requests merged in 2020-07, with the labels that each got.

#789 fix(forms): override Bedrock CSS [hidden] styling for radios, checkboxes, and toggles
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/radio/StyledRadioLabel.ts
Labels: PR: Bug Fix :bug:

#790 fix(chrome): add fixed positioning to html element
  packages/chrome/.size-snapshot.json
  packages/chrome/examples/basic.md
  packages/chrome/examples/header.md
  packages/chrome/src/elements/Chrome.spec.tsx
  packages/chrome/src/elements/Chrome.tsx
Labels: PR: Bug Fix :bug:

#794 fix(avatars): use fluid chrome in avatars example
  packages/avatars/examples/advanced.md
Labels: PR: Bug Fix :bug:

#795 chore: revert v8.15.1 release
  CHANGELOG.md
  lerna.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/.size-snapshot.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/.size-snapshot.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/theming/package.json
  packages/tooltips/package.json
  packages/typography/package.json
  packages/utilities/package.json
Labels: PR: Internal :seedling:

#807 chore(examples): update codesandbox package.json
  examples/codesandbox/package.json
Labels: PR: Internal :seedling:

#810 fix(typography): set UnorderedList type default to "disc"
  packages/typography/.size-snapshot.json
  packages/typography/src/elements/lists/UnorderedList.spec.js
  packages/typography/src/elements/lists/UnorderedList.tsx
Labels: PR: Bug Fix :bug:

#796 feat(typography): add media components to Span
  packages/typography/.size-snapshot.json
  packages/typography/examples/span.md
  packages/typography/src/elements/Span.spec.tsx
  packages/typography/src/elements/Span.tsx
  packages/typography/src/styled/StyledFont.tsx
  packages/typography/src/styled/StyledIcon.spec.tsx
  packages/typography/src/styled/StyledIcon.ts
  packages/typography/src/styled/index.ts
Labels: PR: New Feature :rocket:

#814 feat(theming): add mediaQuery utility
  packages/theming/.size-snapshot.json
  packages/theming/src/index.ts
  packages/theming/src/utils/mediaQuery.spec.ts
  packages/theming/src/utils/mediaQuery.ts
Labels: PR: New Feature :rocket:

#811 chore(docs): update Table selection example to allow keyboard
  packages/tables/examples/selectable-table.md
Labels: PR: Docs :memo:

#817 fix(dropdowns): allow object values for NextItem selection
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/NextItem.tsx
Labels: PR: Bug Fix :bug:

#818 fix(dropdowns): allow NextItem to receive an object value
  packages/dropdowns/src/Dropdown/Dropdown.spec.tsx
  packages/dropdowns/src/Menu/Items/NextItem.tsx
Labels: PR: Bug Fix :bug:
