Repository zendeskgarden/react-components, pull requests merged in 2020-08, with the labels that each got.

#821 feat(buttons): default external links to use safe referrer attributes
  packages/buttons/.size-snapshot.json
  packages/buttons/src/elements/Anchor.spec.tsx
  packages/buttons/src/elements/Anchor.tsx
Labels: PR: New Feature :rocket:

#820 feat(forms): allow Textarea to dynamically change height
  packages/forms/.size-snapshot.json
  packages/forms/examples/basic.md
  packages/forms/src/elements/Textarea.spec.tsx
  packages/forms/src/elements/Textarea.tsx
  packages/forms/src/styled/text/StyledTextarea.ts
Labels: PR: New Feature :rocket:

#825 fix(forms): ensure Textarea autoresizing is calculated with controlled value
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/Textarea.spec.tsx
  packages/forms/src/elements/Textarea.tsx
Labels: PR: Bug Fix :bug:

#826 chore(buttons): update Anchor isExternal prop docs
  packages/buttons/src/elements/Anchor.tsx
Labels: PR: Docs :memo:

#822 chore(tests): add user-event testing library
  package.json
  packages/accordions/src/elements/accordion/components/Header.spec.tsx
  packages/buttons/src/elements/ButtonGroup.spec.tsx
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.spec.tsx
  packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/components/End.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Start.spec.tsx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
  packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
  packages/dropdowns/src/elements/Fields/Label.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/AddItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Menu.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
  packages/forms/src/elements/FauxInput.spec.tsx
  packages/forms/src/elements/MediaInput.spec.tsx
  packages/forms/src/elements/MultiThumbRange.spec.tsx
  packages/forms/src/elements/Range.spec.tsx
  packages/forms/src/elements/tiles/Tiles.spec.tsx
  packages/modals/src/elements/Modal.spec.tsx
  packages/pagination/src/elements/Pagination/Pagination.spec.tsx
  packages/tables/src/elements/OverflowButton.spec.tsx
  packages/tables/src/elements/Row.spec.tsx
  packages/tabs/src/elements/Tabs.spec.tsx
  packages/tooltips/src/elements/Tooltip.spec.tsx
  yarn.lock
Labels: PR: Internal :seedling:

#824 feat(forms): allow Textarea to autoresize based on content
  packages/forms/examples/text-input.md
  packages/forms/src/fields/Textarea.js
  packages/forms/src/fields/Textarea.spec.js
  packages/forms/src/styled/text/StyledTextarea.js
Labels: PR: New Feature :rocket:

#823 fix(notifications): update notification padding
  packages/notifications/.size-snapshot.json
  packages/notifications/src/styled/StyledBase.spec.tsx
  packages/notifications/src/styled/StyledBase.ts
  packages/notifications/src/styled/StyledIcon.ts
  packages/notifications/src/styled/StyledWell.ts
Labels: PR: Bug Fix :bug:

#829 feat(forms, dropdowns): use FauxInput as the fundamental styling basis for Select, Autocomplete, and Multiselect
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/examples/field-variants.md
  packages/dropdowns/examples/multiselect.md
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/styled/field/SelectWrapper.tsx
  packages/dropdowns/src/styled/field/StyledMultiselect.ts
  packages/dropdowns/src/styled/field/StyledSelect.ts
  packages/dropdowns/src/styled/index.ts
  packages/dropdowns/src/styled/multiselect/StyledMultiselectInput.ts
  packages/dropdowns/src/styled/multiselect/StyledMultiselectItemWrapper.ts
  packages/dropdowns/src/styled/multiselect/StyledMultiselectItemsContainer.ts
  packages/dropdowns/src/styled/multiselect/StyledMultiselectMoreAnchor.ts
  packages/dropdowns/src/styled/select/StyledFauxInput.ts
  packages/dropdowns/src/styled/select/StyledInput.ts
  packages/dropdowns/src/styled/select/StyledSelect.ts
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/FauxInput.spec.tsx
  packages/forms/src/elements/FauxInput.tsx
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/index.ts
  packages/forms/src/styled/text/StyledTextFauxInput.ts
  packages/forms/src/styled/text/StyledTextInput.ts
  packages/forms/src/styled/text/StyledTextMediaFigure.spec.tsx
  packages/forms/src/styled/text/StyledTextMediaFigure.ts
Labels: PR: New Feature :rocket:

#831 fix(buttons): allow user selection on link and anchor buttons
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledButton.spec.tsx
  packages/buttons/src/styled/StyledButton.ts
Labels: PR: Bug Fix :bug:

#832 fix(dropdowns): update downshift dependency
  packages/dropdowns/package.json
Labels: PR: Bug Fix :bug:

#830 fix(datepickers): format day with NumberFormat utility
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/Datepicker/components/Calendar.tsx
Labels: PR: Bug Fix :bug:

#834 fix(datepickers): use gregorian labels for days
  packages/datepickers/src/Datepicker/components/Calendar.tsx
Labels: PR: Bug Fix :bug:

#833 feat(forms): new native Select component
  packages/forms/.size-snapshot.json
  packages/forms/examples/advanced.md
  packages/forms/examples/basic.md
  packages/forms/src/elements/Select.spec.tsx
  packages/forms/src/elements/Select.tsx
  packages/forms/src/index.ts
  packages/forms/src/styled/index.ts
  packages/forms/src/styled/select/StyledSelect.spec.tsx
  packages/forms/src/styled/select/StyledSelect.ts
  packages/forms/src/styled/select/StyledSelectWrapper.spec.tsx
  packages/forms/src/styled/select/StyledSelectWrapper.ts
  packages/forms/src/styled/text/StyledTextFauxInput.ts
Labels: PR: New Feature :rocket:

#836 fix: danger anchor focus color
  packages/buttons/.size-snapshot.json
  packages/buttons/examples/basic.md
  packages/buttons/src/styled/StyledButton.ts
Labels: PR: Bug Fix :bug:

#828 feat(modals): introduce new TooltipModal component
  packages/modals/.size-snapshot.json
  packages/modals/examples/tooltip-modal.md
  packages/modals/package.json
  packages/modals/src/elements/TooltipModal/Body.spec.tsx
  packages/modals/src/elements/TooltipModal/Body.tsx
  packages/modals/src/elements/TooltipModal/Close.spec.tsx
  packages/modals/src/elements/TooltipModal/Close.tsx
  packages/modals/src/elements/TooltipModal/Title.spec.tsx
  packages/modals/src/elements/TooltipModal/Title.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.spec.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
  packages/modals/src/index.ts
  packages/modals/src/styled/StyledTooltipModal.ts
  packages/modals/src/styled/StyledTooltipModalBackdrop.ts
  packages/modals/src/styled/StyledTooltipModalBody.ts
  packages/modals/src/styled/StyledTooltipModalClose.ts
  packages/modals/src/styled/StyledTooltipModalFooter.ts
  packages/modals/src/styled/StyledTooltipModalFooterItem.ts
  packages/modals/src/styled/StyledTooltipModalTitle.ts
  packages/modals/src/styled/StyledTooltipWrapper.ts
  packages/modals/src/styled/index.ts
  packages/modals/src/utils/gardenPlacements.tsx
  packages/modals/src/utils/useTooltipModalContext.spec.tsx
  packages/modals/src/utils/useTooltipModalContext.tsx
  packages/modals/styleguide.config.js
  packages/modals/yarn.lock
  utils/test/tsconfig.test.json
Labels: PR: New Feature :rocket:

#837 fix(buttons): apply min-width to icon buttons
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledIconButton.ts
Labels: PR: Bug Fix :bug:

#839 docs(tooltip) fix errors in tooltip docs
  packages/tooltips/src/elements/Tooltip.tsx
Labels: PR: Docs :memo:

#840 fix(typography): prevent prop from being added to DOM element
  packages/typography/.size-snapshot.json
  packages/typography/src/styled/StyledIcon.ts
Labels: PR: Bug Fix :bug:

#838 fix(accordions): remove default button behavior
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/accordion/components/Header.tsx
  packages/accordions/src/elements/accordion/components/Label.spec.tsx
Labels: PR: Bug Fix :bug:

#842 fix(forms): workaround shift+click checkbox labels on Firefox
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/common/Label.tsx
  packages/forms/src/styled/checkbox/StyledCheckSvg.ts
  packages/forms/src/styled/checkbox/StyledDashSvg.ts
Labels: PR: Bug Fix :bug:

#844 fix(forms): allow checkbox label click for Firefox
  packages/forms/src/fields/common/Label.js
Labels: PR: Bug Fix :bug:

#841 feat(forms): introduce InputGroup component
  packages/forms/.size-snapshot.json
  packages/forms/examples/input-group.md
  packages/forms/src/elements/Input.tsx
  packages/forms/src/elements/input-group/InputGroup.spec.tsx
  packages/forms/src/elements/input-group/InputGroup.tsx
  packages/forms/src/index.ts
  packages/forms/src/styled/index.ts
  packages/forms/src/styled/input-group/StyledInputGroup.ts
  packages/forms/src/utils/useInputGroupContext.ts
  packages/forms/styleguide.config.js
Labels: PR: New Feature :rocket:

#848 chore(ci): ensure all PRs include semantic release label
  .github/workflows/pull-request-labels.yaml
Labels: PR: Internal :seedling:

#847 chore(docs): remove primary button from input-group docs
  packages/forms/examples/input-group.md
Labels: PR: Docs :memo:
