Repository zendeskgarden/react-components, pull requests merged in 2020-04, with the labels that each got.

#691 fix(forms): replace encoded background images with inline SVGs
  .stylelintrc
  packages/accordions/package.json
  packages/accordions/yarn.lock
  packages/breadcrumbs/.size-snapshot.json
  packages/breadcrumbs/package.json
  packages/breadcrumbs/yarn.lock
  packages/buttons/.size-snapshot.json
  packages/buttons/package.json
  packages/buttons/yarn.lock
  packages/chrome/.size-snapshot.json
  packages/chrome/package.json
  packages/chrome/yarn.lock
  packages/datepickers/.size-snapshot.json
  packages/datepickers/package.json
  packages/datepickers/yarn.lock
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/package.json
  packages/dropdowns/yarn.lock
  packages/forms/.size-snapshot.json
  packages/forms/package.json
  packages/forms/src/elements/common/Label.tsx
  packages/forms/src/styled/checkbox/StyledCheckInput.ts
  packages/forms/src/styled/checkbox/StyledCheckSvg.spec.tsx
  packages/forms/src/styled/checkbox/StyledCheckSvg.ts
  packages/forms/src/styled/checkbox/StyledDashSvg.spec.tsx
  packages/forms/src/styled/checkbox/StyledDashSvg.ts
  packages/forms/src/styled/index.ts
  packages/forms/src/styled/radio/StyledRadioInput.ts
  packages/forms/src/styled/radio/StyledRadioSvg.spec.tsx
  packages/forms/src/styled/radio/StyledRadioSvg.ts
  packages/forms/src/styled/tiles/StyledTile.ts
  packages/forms/src/styled/toggle/StyledToggleInput.spec.tsx
  packages/forms/src/styled/toggle/StyledToggleInput.ts
  packages/forms/src/styled/toggle/StyledToggleSvg.spec.tsx
  packages/forms/src/styled/toggle/StyledToggleSvg.ts
  packages/forms/yarn.lock
  packages/modals/package.json
  packages/modals/yarn.lock
  packages/notifications/package.json
  packages/notifications/yarn.lock
  packages/pagination/.size-snapshot.json
  packages/pagination/package.json
  packages/pagination/yarn.lock
  packages/tables/package.json
  packages/tables/yarn.lock
  packages/tags/package.json
  packages/tags/yarn.lock
Labels: PR: Bug Fix :bug:

#696 feat(buttons): allow custom Button type
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledButton.spec.tsx
  packages/buttons/src/styled/StyledButton.ts
Labels: PR: Bug Fix :bug:

#697 fix(tooltips): ensure updated content triggers new position
  packages/tooltips/.size-snapshot.json
  packages/tooltips/src/elements/Tooltip.tsx
Labels: PR: Bug Fix :bug:

#694 chore(theming): upgrade polished and remove deprecated stripUnit usages
  packages/.template/package.json
  packages/accordions/package.json
  packages/accordions/yarn.lock
  packages/avatars/package.json
  packages/avatars/yarn.lock
  packages/breadcrumbs/package.json
  packages/breadcrumbs/yarn.lock
  packages/buttons/package.json
  packages/buttons/yarn.lock
  packages/chrome/package.json
  packages/chrome/yarn.lock
  packages/dropdowns/package.json
  packages/dropdowns/yarn.lock
  packages/forms/package.json
  packages/forms/yarn.lock
  packages/grid/package.json
  packages/grid/yarn.lock
  packages/loaders/package.json
  packages/loaders/yarn.lock
  packages/pagination/package.json
  packages/pagination/yarn.lock
  packages/tables/package.json
  packages/tables/yarn.lock
  packages/tabs/package.json
  packages/tabs/yarn.lock
  packages/tags/package.json
  packages/tags/yarn.lock
  packages/theming/.size-snapshot.json
  packages/theming/package.json
  packages/theming/src/utils/getLineHeight.ts
  packages/theming/yarn.lock
  packages/tooltips/package.json
  packages/tooltips/yarn.lock
  packages/typography/package.json
  packages/typography/yarn.lock
Labels: PR: Internal :seedling:

#715 chore(deps): update non-major shared dependencies
  package.json
  packages/accordions/.size-snapshot.json
  packages/breadcrumbs/.size-snapshot.json
  packages/buttons/.size-snapshot.json
  packages/chrome/.size-snapshot.json
  packages/datepickers/.size-snapshot.json
  packages/dropdowns/.size-snapshot.json
  packages/forms/.size-snapshot.json
  packages/loaders/.size-snapshot.json
  packages/modals/.size-snapshot.json
  packages/notifications/.size-snapshot.json
  packages/pagination/.size-snapshot.json
  packages/tables/.size-snapshot.json
  packages/tabs/.size-snapshot.json
  packages/tags/.size-snapshot.json
  packages/theming/.size-snapshot.json
  yarn.lock
Labels: PR: Internal :seedling:

#699 chore(loaders): update Dots API descriptions
  packages/loaders/src/elements/Dots.tsx
Labels: PR: Docs :memo:

#719 chore(renovate): allow open ranges for dev dependencies
  renovate.json
Labels: PR: Internal :seedling:

#713 feat(all): add styled-components v5 as valid peer dependency
  examples/codesandbox/package.json
  examples/codesandbox/yarn.lock
  examples/gatsby/package.json
  examples/gatsby/yarn.lock
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/theming/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: New Feature :rocket:

#714 fix(chrome): update accordion usage
  packages/chrome/.size-snapshot.json
  packages/chrome/package.json
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
  packages/chrome/yarn.lock
Labels: PR: Internal :seedling:

#712 fix(accordions): update height when content scrollHeight changes
  packages/accordions/.size-snapshot.json
  packages/accordions/package.json
  packages/accordions/src/elements/stepper/components/Content.tsx
  packages/accordions/src/styled/stepper/StyledInnerContent.tsx
  packages/accordions/yarn.lock
Labels: PR: Bug Fix :bug:

#692 feat(pagination): create CursorPagination component
  packages/pagination/.size-snapshot.json
  packages/pagination/README.md
  packages/pagination/examples/advanced.md
  packages/pagination/examples/basic.md
  packages/pagination/src/elements/CursorPagination/CursorPagination.tsx
  packages/pagination/src/elements/CursorPagination/components/First.spec.tsx
  packages/pagination/src/elements/CursorPagination/components/First.tsx
  packages/pagination/src/elements/CursorPagination/components/Last.spec.tsx
  packages/pagination/src/elements/CursorPagination/components/Last.tsx
  packages/pagination/src/elements/CursorPagination/components/Next.spec.tsx
  packages/pagination/src/elements/CursorPagination/components/Next.tsx
  packages/pagination/src/elements/CursorPagination/components/Previous.spec.tsx
  packages/pagination/src/elements/CursorPagination/components/Previous.tsx
  packages/pagination/src/elements/Pagination/Pagination.spec.tsx
  packages/pagination/src/elements/Pagination/Pagination.tsx
  packages/pagination/src/index.ts
  packages/pagination/src/styled/CursorPagination/StyledCursor.spec.tsx
  packages/pagination/src/styled/CursorPagination/StyledCursor.ts
  packages/pagination/src/styled/CursorPagination/StyledCursorPagination.ts
  packages/pagination/src/styled/CursorPagination/StyledIcon.spec.tsx
  packages/pagination/src/styled/CursorPagination/StyledIcon.ts
  packages/pagination/src/styled/Pagination/StyledGap.spec.tsx
  packages/pagination/src/styled/Pagination/StyledGap.ts
  packages/pagination/src/styled/Pagination/StyledNavigation.spec.tsx
  packages/pagination/src/styled/Pagination/StyledNavigation.ts
  packages/pagination/src/styled/Pagination/StyledPage.spec.tsx
  packages/pagination/src/styled/Pagination/StyledPage.ts
  packages/pagination/src/styled/Pagination/StyledPageBase.ts
  packages/pagination/src/styled/Pagination/StyledPagination.spec.tsx
  packages/pagination/src/styled/Pagination/StyledPagination.ts
  packages/pagination/src/styled/index.ts
  packages/pagination/styleguide.config.js
Labels: PR: New Feature :rocket:

#721 fix(pagination): fix styleguidist path
  packages/pagination/styleguide.config.js
Labels: PR: Docs :memo:

#700 chore(loaders): update remaining Loaders API descriptions
  packages/loaders/src/elements/Dots.tsx
  packages/loaders/src/elements/Inline.tsx
  packages/loaders/src/elements/Progress.tsx
  packages/loaders/src/elements/Skeleton.tsx
  packages/loaders/src/elements/Spinner.tsx
Labels: PR: Docs :memo:

#698 feat(menu): revise menu spacing
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/examples/advanced-menu.md
  packages/dropdowns/examples/tree-menu.md
  packages/dropdowns/src/elements/Menu/Items/HeaderIcon.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/HeaderItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaFigure.spec.tsx
  packages/dropdowns/src/styled/items/StyledItem.ts
  packages/dropdowns/src/styled/items/StyledItemIcon.ts
  packages/dropdowns/src/styled/items/StyledNextItem.ts
  packages/dropdowns/src/styled/items/header/StyledHeaderIcon.ts
  packages/dropdowns/src/styled/items/header/StyledHeaderItem.ts
  packages/dropdowns/src/styled/items/media/StyledMediaBody.ts
  packages/dropdowns/src/styled/items/media/StyledMediaFigure.ts
  packages/dropdowns/src/styled/items/media/StyledMediaItem.ts
  packages/dropdowns/src/styled/menu/StyledMenu.ts
Labels: PR: Internal :seedling:

#722 feat(typography): add bold option
  packages/typography/.size-snapshot.json
  packages/typography/examples/code.md
  packages/typography/examples/lists.md
  packages/typography/examples/typography.md
  packages/typography/src/elements/LG.spec.tsx
  packages/typography/src/elements/LG.tsx
  packages/typography/src/elements/MD.spec.tsx
  packages/typography/src/elements/MD.tsx
  packages/typography/src/elements/SM.spec.tsx
  packages/typography/src/elements/SM.tsx
  packages/typography/src/elements/XL.spec.tsx
  packages/typography/src/elements/XL.tsx
  packages/typography/src/elements/XXL.spec.tsx
  packages/typography/src/elements/XXL.tsx
  packages/typography/src/elements/XXXL.spec.tsx
  packages/typography/src/elements/XXXL.tsx
  packages/typography/src/styled/StyledFont.spec.js
  packages/typography/src/styled/StyledFont.tsx
  utils/build/styled.d.ts
Labels: PR: New Feature :rocket:

#723 chore(tabs): update Tabs API descriptions
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/src/elements/TabList.tsx
  packages/tabs/src/elements/TabPanel.tsx
  packages/tabs/src/elements/Tabs.tsx
Labels: PR: Docs :memo:

#724 feat(typography): add Paragraph component
  packages/typography/.size-snapshot.json
  packages/typography/examples/paragraph.md
  packages/typography/src/elements/Paragraph.spec.tsx
  packages/typography/src/elements/Paragraph.tsx
  packages/typography/src/elements/lists/OrderedList.tsx
  packages/typography/src/elements/lists/UnorderedList.tsx
  packages/typography/src/index.ts
  packages/typography/src/styled/StyledCode.spec.tsx
  packages/typography/src/styled/StyledEllipsis.spec.tsx
  packages/typography/src/styled/StyledFont.spec.tsx
  packages/typography/src/styled/StyledList.spec.tsx
  packages/typography/src/styled/StyledList.ts
  packages/typography/src/styled/StyledListItem.spec.tsx
  packages/typography/src/styled/StyledParagraph.spec.tsx
  packages/typography/src/styled/StyledParagraph.ts
  packages/typography/src/styled/index.ts
  packages/typography/styleguide.config.js
Labels: PR: New Feature :rocket:

#726 chore: enhanced scripting workflow
  .circleci/config.yml
  .gitignore
  package.json
  utils/scripts/deploy.js
  utils/scripts/get-cids.sh
  utils/scripts/gh-pages.js
  utils/scripts/github-release.js
  utils/scripts/new.js
  utils/scripts/tag.js
  utils/scripts/update-changelog.js
  utils/scripts/version.sh
  yarn.lock
Labels: PR: Internal :seedling:

#730 fix(notifications): restore transition to close button focus & hover styles
  packages/notifications/.size-snapshot.json
  packages/notifications/src/styled/content/StyledClose.ts
Labels: PR: Bug Fix :bug:

#729 fix(forms): retain line height for hidden radio/checkbox/toggle labels
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/radio/StyledRadioLabel.spec.tsx
  packages/forms/src/styled/radio/StyledRadioLabel.ts
  packages/forms/src/styled/toggle/StyledToggleLabel.ts
Labels: PR: Bug Fix :bug:

#725 feat(accordions): add new accordion component
  packages/accordions/.size-snapshot.json
  packages/accordions/README.md
  packages/accordions/examples/advanced.md
  packages/accordions/examples/basic.md
  packages/accordions/package.json
  packages/accordions/src/elements/accordion/Accordion.spec.tsx
  packages/accordions/src/elements/accordion/Accordion.tsx
  packages/accordions/src/elements/accordion/components/Header.spec.tsx
  packages/accordions/src/elements/accordion/components/Header.tsx
  packages/accordions/src/elements/accordion/components/Label.spec.tsx
  packages/accordions/src/elements/accordion/components/Label.tsx
  packages/accordions/src/elements/accordion/components/Panel.spec.tsx
  packages/accordions/src/elements/accordion/components/Panel.tsx
  packages/accordions/src/elements/accordion/components/Section.spec.tsx
  packages/accordions/src/elements/accordion/components/Section.tsx
  packages/accordions/src/index.ts
  packages/accordions/src/styled/accordion/StyledAccordion.ts
  packages/accordions/src/styled/accordion/StyledButton.spec.tsx
  packages/accordions/src/styled/accordion/StyledButton.ts
  packages/accordions/src/styled/accordion/StyledHeader.spec.tsx
  packages/accordions/src/styled/accordion/StyledHeader.ts
  packages/accordions/src/styled/accordion/StyledInnerPanel.spec.tsx
  packages/accordions/src/styled/accordion/StyledInnerPanel.ts
  packages/accordions/src/styled/accordion/StyledPanel.spec.tsx
  packages/accordions/src/styled/accordion/StyledPanel.ts
  packages/accordions/src/styled/accordion/StyledRotateIcon.spec.tsx
  packages/accordions/src/styled/accordion/StyledRotateIcon.ts
  packages/accordions/src/styled/accordion/StyledSection.ts
  packages/accordions/src/styled/index.ts
  packages/accordions/src/utils/index.ts
  packages/accordions/src/utils/useAccordionContext.spec.tsx
  packages/accordions/src/utils/useAccordionContext.ts
  packages/accordions/src/utils/useHeaderContext.spec.tsx
  packages/accordions/src/utils/useHeaderContext.ts
  packages/accordions/src/utils/useSectionContext.spec.tsx
  packages/accordions/src/utils/useSectionContext.ts
  packages/accordions/styleguide.config.js
  packages/accordions/yarn.lock
Labels: PR: New Feature :rocket:

#731 chore(scripts): ensure version commit hits CI, triggering npm publish
  .github/PULL_REQUEST_TEMPLATE.md
  utils/scripts/tag.js
Labels: PR: Internal :seedling:

#728 feat(dropdowns): add start slot to autocomplete and select components
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/examples/field-variants.md
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/styled/field/StyledSelect.ts
Labels: PR: New Feature :rocket:
