Repository zendeskgarden/react-components, pull requests merged in 2020-09, with the labels that each got.

#852 fix(pagination): fix cursor button type definitions
  packages/pagination/src/elements/CursorPagination/components/First.tsx
  packages/pagination/src/elements/CursorPagination/components/Last.tsx
  packages/pagination/src/elements/CursorPagination/components/Next.tsx
  packages/pagination/src/elements/CursorPagination/components/Previous.tsx
Labels: PR: Bug Fix :bug:

#851 fix(dropdowns): allow internal elements to receive custom component styles
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/styled/multiselect/StyledMultiselectInput.ts
  packages/dropdowns/src/styled/multiselect/StyledMultiselectItemWrapper.ts
  packages/dropdowns/src/styled/multiselect/StyledMultiselectItemsContainer.ts
  packages/dropdowns/src/styled/multiselect/StyledMultiselectMoreAnchor.ts
  packages/dropdowns/src/styled/select/StyledFauxInput.ts
  packages/dropdowns/src/styled/select/StyledInput.ts
  packages/dropdowns/src/styled/select/StyledSelect.ts
Labels: PR: Bug Fix :bug:

#853 fix: correct keyboard navigation for nested multiselect menus
  packages/dropdowns/src/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/Multiselect/Multiselect.tsx
Labels: PR: Bug Fix :bug:

#856 fix(dropdowns): correct keyboard navigation for nested multiselect me…
  packages/dropdowns/src/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/Multiselect/Multiselect.tsx
Labels: PR: Bug Fix :bug:

#857 fix(datepickers): allow event composition on Datepicker inputs
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
  packages/datepickers/src/elements/DatepickerRange/components/End.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Start.tsx
Labels: PR: Bug Fix :bug:

#845 fix(accordions): prevent double trigger invocation on Firefox
  package.json
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/accordion/components/Header.tsx
  yarn.lock
Labels: PR: Bug Fix :bug:

#858 internal(accordions): update snapshot
  packages/accordions/.size-snapshot.json
Labels: PR: Internal :seedling:

#854 feat(typography): introduce CodeBlock component
  packages/typography/.size-snapshot.json
  packages/typography/examples/codeblock.md
  packages/typography/package.json
  packages/typography/src/elements/CodeBlock.spec.tsx
  packages/typography/src/elements/CodeBlock.tsx
  packages/typography/src/index.ts
  packages/typography/src/styled/StyledCodeBlock.spec.tsx
  packages/typography/src/styled/StyledCodeBlock.ts
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.ts
  packages/typography/src/styled/StyledCodeBlockToken.spec.tsx
  packages/typography/src/styled/StyledCodeBlockToken.ts
  packages/typography/src/styled/index.ts
  packages/typography/styleguide.config.js
  packages/typography/yarn.lock
Labels: PR: New Feature :rocket:

#850 feat(forms): introduce FileUpload component
  packages/forms/.size-snapshot.json
  packages/forms/examples/file-upload.md
  packages/forms/package.json
  packages/forms/src/elements/FileUpload.spec.tsx
  packages/forms/src/elements/FileUpload.tsx
  packages/forms/src/index.ts
  packages/forms/src/styled/file-upload/StyledFileUpload.ts
  packages/forms/src/styled/index.ts
  packages/forms/styleguide.config.js
  packages/forms/yarn.lock
Labels: PR: New Feature :rocket:

#875 fix(forms, datepickers, dropdowns): bump input border hover color from blue-400 to blue-600
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/radio/StyledRadioInput.ts
  packages/forms/src/styled/text/StyledTextInput.ts
  packages/forms/src/styled/tiles/StyledTile.ts
Labels: PR: Bug Fix :bug:

#877 fix(typography): codeblock styling tweaks
  packages/typography/.size-snapshot.json
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.ts
Labels: PR: Bug Fix :bug:

#873 chore(docs): introduce storybook and migrate react-tabs examples
  .circleci/config.yml
  .eslintignore
  .eslintrc.json
  .storybook/babel.config.js
  .storybook/gardenTheme.js
  .storybook/main.js
  .storybook/manager-head.html
  .storybook/manager.js
  .storybook/preview-head.html
  .storybook/preview.js
  demo/index.html
  package.json
  packages/tabs/.size-snapshot.json
  packages/tabs/README.md
  packages/tabs/examples/default-tabs.md
  packages/tabs/package.json
  packages/tabs/src/elements/Tabs.tsx
  packages/tabs/src/index.ts
  packages/tabs/stories/Readme.stories.mdx
  packages/tabs/stories/Tabs.stories.tsx
  packages/tabs/styleguide.config.js
  packages/theming/src/index.ts
  tsconfig.json
  utils/styleguide/public/images/garden.svg
  yarn.lock
Labels: PR: Docs :memo:

#876 fix(modals): allow Modal to be used in SSR environments
  packages/modals/.size-snapshot.json
  packages/modals/package.json
  packages/modals/src/elements/Modal.tsx
  packages/modals/yarn.lock
Labels: PR: Bug Fix :bug:

#878 chore(docs): migrate react-accordions examples to storybook
  .eslintrc.json
  .storybook/main.js
  demo/index.html
  packages/accordions/README.md
  packages/accordions/examples/advanced.md
  packages/accordions/examples/basic.md
  packages/accordions/package.json
  packages/accordions/stories/1-Readme.stories.mdx
  packages/accordions/stories/2-Accordion.stories.tsx
  packages/accordions/stories/3-Stepper.stories.tsx
  packages/accordions/stories/examples/Controlled.tsx
  packages/accordions/stories/examples/Uncontrolled.tsx
  packages/accordions/styleguide.config.js
  packages/dropdowns/src/index.ts
  packages/forms/src/index.ts
Labels: PR: Docs :memo:

#880 chore(docs): migrate react-breadcrumbs docs to storybook
  demo/index.html
  packages/breadcrumbs/README.md
  packages/breadcrumbs/examples/basic.md
  packages/breadcrumbs/package.json
  packages/breadcrumbs/stories/1-Readme.stories.mdx
  packages/breadcrumbs/stories/2-Breadcrumbs.stories.tsx
  packages/breadcrumbs/styleguide.config.js
Labels: PR: Docs :memo:

#879 feat(forms): add readonly support for text inputs
  packages/forms/.size-snapshot.json
  packages/forms/examples/basic.md
  packages/forms/examples/input-group.md
  packages/forms/src/elements/FauxInput.tsx
  packages/forms/src/elements/Input.spec.tsx
  packages/forms/src/elements/Input.tsx
  packages/forms/src/elements/MediaInput.spec.tsx
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/elements/Textarea.spec.tsx
  packages/forms/src/elements/Textarea.tsx
  packages/forms/src/styled/text/StyledTextFauxInput.spec.tsx
  packages/forms/src/styled/text/StyledTextFauxInput.ts
  packages/forms/src/styled/text/StyledTextInput.spec.tsx
  packages/forms/src/styled/text/StyledTextInput.ts
Labels: PR: New Feature :rocket:

#882 fix(build): ensure ts types directory is relative
  packages/.template/tsconfig.build.json
  packages/accordions/tsconfig.build.json
  packages/avatars/tsconfig.build.json
  packages/breadcrumbs/tsconfig.build.json
  packages/buttons/tsconfig.build.json
  packages/chrome/tsconfig.build.json
  packages/datepickers/tsconfig.build.json
  packages/dropdowns/tsconfig.build.json
  packages/forms/tsconfig.build.json
  packages/grid/tsconfig.build.json
  packages/loaders/tsconfig.build.json
  packages/modals/tsconfig.build.json
  packages/notifications/tsconfig.build.json
  packages/pagination/tsconfig.build.json
  packages/tables/tsconfig.build.json
  packages/tabs/tsconfig.build.json
  packages/tags/tsconfig.build.json
  packages/theming/tsconfig.build.json
  packages/tooltips/tsconfig.build.json
  packages/typography/tsconfig.build.json
Labels: PR: Bug Fix :bug:

#883 chore(docs): migrate react-chrome to storybook
  .eslintrc.json
  demo/index.html
  packages/chrome/.size-snapshot.json
  packages/chrome/README.md
  packages/chrome/examples/basic.md
  packages/chrome/examples/header.md
  packages/chrome/package.json
  packages/chrome/src/elements/Chrome.tsx
  packages/chrome/src/elements/header/HeaderItemWrapper.tsx
  packages/chrome/src/styled/index.ts
  packages/chrome/stories/1-Readme.stories.mdx
  packages/chrome/stories/2-Chrome.stories.tsx
  packages/chrome/stories/examples/Default.tsx
  packages/chrome/stories/examples/StandaloneHeader.tsx
  packages/chrome/styleguide.config.js
Labels: PR: Docs :memo:

#885 chore(docs): migrate react-loaders documentation to Storybook
  demo/index.html
  packages/loaders/README.md
  packages/loaders/examples/dots.md
  packages/loaders/examples/inline.md
  packages/loaders/examples/progress.md
  packages/loaders/examples/skeleton.md
  packages/loaders/examples/spinner.md
  packages/loaders/package.json
  packages/loaders/src/elements/Dots.tsx
  packages/loaders/src/elements/Inline.tsx
  packages/loaders/src/elements/Progress.tsx
  packages/loaders/src/elements/Skeleton.tsx
  packages/loaders/src/elements/Spinner.tsx
  packages/loaders/src/index.ts
  packages/loaders/src/styled/index.ts
  packages/loaders/stories/1-Readme.stories.mdx
  packages/loaders/stories/2-Dots.stories.tsx
  packages/loaders/stories/3-Inline.stories.tsx
  packages/loaders/stories/4-Progress.stories.tsx
  packages/loaders/stories/5-Skeleton.stories.tsx
  packages/loaders/stories/6-Spinner.stories.tsx
  packages/loaders/styleguide.config.js
Labels: PR: Docs :memo:

#887 fix(modals): provide ref object for focusvisible
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/Modal.tsx
Labels: PR: Bug Fix :bug:

#888 fix(table): revise cell type definition
  packages/tables/src/elements/Cell.tsx
  packages/tables/src/elements/HeaderCell.tsx
Labels: PR: Bug Fix :bug:

#890 fix(theming): update brand spec'd product colors
  packages/theming/.size-snapshot.json
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.ts
Labels: PR: Bug Fix :bug:

#884 feat(modals): introduce drawer modal
  package.json
  packages/modals/.size-snapshot.json
  packages/modals/examples/drawer-modal.md
  packages/modals/package.json
  packages/modals/src/elements/DrawerModal/Body.spec.tsx
  packages/modals/src/elements/DrawerModal/Body.tsx
  packages/modals/src/elements/DrawerModal/Close.spec.tsx
  packages/modals/src/elements/DrawerModal/Close.tsx
  packages/modals/src/elements/DrawerModal/DrawerModal.spec.tsx
  packages/modals/src/elements/DrawerModal/DrawerModal.tsx
  packages/modals/src/elements/DrawerModal/Header.spec.tsx
  packages/modals/src/elements/DrawerModal/Header.tsx
  packages/modals/src/index.ts
  packages/modals/src/styled/StyledDrawerModal.ts
  packages/modals/src/styled/StyledDrawerModalBackdrop.ts
  packages/modals/src/styled/StyledDrawerModalBody.ts
  packages/modals/src/styled/StyledDrawerModalClose.ts
  packages/modals/src/styled/StyledDrawerModalFooter.ts
  packages/modals/src/styled/StyledDrawerModalFooterItem.ts
  packages/modals/src/styled/StyledDrawerModalHeader.ts
  packages/modals/src/styled/index.ts
  packages/modals/styleguide.config.js
  packages/modals/yarn.lock
  yarn.lock
Labels: PR: New Feature :rocket:
