Repository zendeskgarden/react-components, pull requests merged in 2020-10, with the labels that each got.

#892 fix(modals): add backdrop transparency to drawer
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/DrawerModal/DrawerModal.tsx
  packages/modals/src/styled/StyledDrawerModalBackdrop.ts
  packages/modals/src/styled/index.ts
Labels: PR: Bug Fix :bug:

#893 fix(buttons): improve stroke/fill icon swap for ToggleIconButton
  packages/buttons/.size-snapshot.json
  packages/buttons/examples/basic.md
  packages/buttons/src/styled/StyledIcon.ts
  packages/buttons/src/styled/StyledIconButton.ts
Labels: PR: Bug Fix :bug:

#889 chore(docs): migrate react-buttons to storybook
  .storybook/preview.js
  demo/index.html
  packages/buttons/.size-snapshot.json
  packages/buttons/README.md
  packages/buttons/examples/advanced.md
  packages/buttons/examples/basic.md
  packages/buttons/package.json
  packages/buttons/src/elements/Anchor.tsx
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/ButtonGroup.tsx
  packages/buttons/src/elements/IconButton.tsx
  packages/buttons/src/elements/ToggleButton.tsx
  packages/buttons/src/elements/ToggleIconButton.tsx
  packages/buttons/src/index.ts
  packages/buttons/stories/1-Readme.stories.mdx
  packages/buttons/stories/2-Button.stories.tsx
  packages/buttons/stories/3-Anchor.stories.tsx
  packages/buttons/stories/4-ButtonGroup.stories.tsx
  packages/buttons/stories/5-ChevronButton.stories.tsx
  packages/buttons/stories/6-IconButton.stories.tsx
  packages/buttons/stories/7-SplitButton.stories.tsx
  packages/buttons/stories/8-ToggleButton.stories.tsx
  packages/buttons/stories/9-ToggleIcon.stories.tsx
  packages/buttons/styleguide.config.js
Labels: PR: Docs :memo:

#894 fix(modals): prevent html overflow
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/DrawerModal/DrawerModal.spec.tsx
  packages/modals/src/elements/DrawerModal/DrawerModal.tsx
  packages/modals/src/elements/Modal.spec.tsx
  packages/modals/src/elements/Modal.tsx
Labels: PR: Bug Fix :bug:

#881 chore(docs): migrate react-avatars examples to storybook
  demo/index.html
  packages/avatars/.size-snapshot.json
  packages/avatars/README.md
  packages/avatars/package.json
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/stories/1-Readme.stories.mdx
  packages/avatars/stories/2-Avatar.stories.tsx
  packages/avatars/stories/examples/ChromeUsage.tsx
  packages/avatars/stories/examples/Default.tsx
  packages/avatars/stories/examples/MenuUsage.tsx
  packages/avatars/styleguide.config.js
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/styled/items/media/StyledMediaFigure.ts
Labels: PR: Docs :memo:

#896 fix(modals|notifications): update type definition for button elements
  packages/modals/src/elements/Close.tsx
  packages/modals/src/elements/DrawerModal/Close.tsx
  packages/modals/src/elements/TooltipModal/Close.tsx
  packages/notifications/src/elements/content/Close.tsx
Labels: PR: Bug Fix :bug:

#897 feat(theming): provide scoping <div> knock-out for ThemeProvider
  packages/theming/.size-snapshot.json
  packages/theming/src/elements/ThemeProvider.spec.tsx
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/styleguide.config.js
Labels: PR: New Feature :rocket:

#898 chore(pagination): get theme from context
  packages/pagination/.size-snapshot.json
  packages/pagination/src/elements/Pagination/Pagination.tsx
Labels: PR: Internal :seedling:

#895 chore(docs): migrate react-typography to storybook
  demo/index.html
  packages/typography/README.md
  packages/typography/package.json
  packages/typography/stories/1-Readme.stories.mdx
  packages/typography/stories/13-OrderedList.stories.tsx
  packages/typography/stories/14-UnorderedList.stories.tsx
  packages/typography/stories/2-Code.stories.tsx
  packages/typography/stories/3-CodeBlock.stories.tsx
  packages/typography/stories/4-Ellipsis.stories.tsx
  packages/typography/stories/5-Paragraph.stories.tsx
  packages/typography/stories/6-Span.stories.tsx
  packages/typography/stories/typograpghy/1-SM.stories.tsx
  packages/typography/stories/typograpghy/2-MD.stories.tsx
  packages/typography/stories/typograpghy/3-LG.stories.tsx
  packages/typography/stories/typograpghy/4-XL.stories.tsx
  packages/typography/stories/typograpghy/5-XXL.stories.tsx
  packages/typography/stories/typograpghy/6-XXXL.stories.tsx
  packages/typography/styleguide.config.js
Labels: PR: Docs :memo:

#902 fix(dropdowns): support Safari Voiceover commands
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Fields/Field.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
Labels: PR: Bug Fix :bug:

#903 fix(dropdowns): improve safari voiceover support
  packages/dropdowns/src/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/Fields/Field.tsx
  packages/dropdowns/src/Multiselect/Multiselect.tsx
  packages/dropdowns/src/Trigger/Trigger.tsx
Labels: PR: Bug Fix :bug:

#904 fix(tables): ensure sortable header cells have focus-visible styling
  packages/tables/.size-snapshot.json
  packages/tables/src/styled/StyledSortableButton.ts
Labels: PR: Bug Fix :bug:

#906 chore: update selection based containers
  packages/buttons/yarn.lock
  packages/dropdowns/yarn.lock
  packages/pagination/yarn.lock
  packages/tabs/yarn.lock
Labels: PR: Internal :seedling:

#907 fix(modals): align close button
  packages/modals/.size-snapshot.json
  packages/modals/src/styled/StyledClose.spec.tsx
  packages/modals/src/styled/StyledClose.ts
Labels: PR: Bug Fix :bug:

#908 chore(docs): migrate react-notifications examples to storybook
  demo/index.html
  packages/notifications/README.md
  packages/notifications/examples/basic.md
  packages/notifications/package.json
  packages/notifications/src/styled/index.ts
  packages/notifications/stories/1-Readme.stories.mdx
  packages/notifications/stories/2-Alert.stories.tsx
  packages/notifications/stories/3-Notification.stories.tsx
  packages/notifications/stories/4-Well.stories.tsx
Labels: PR: Docs :memo:

#905 chore(docs): migrate react-pagination examples to storybook
  demo/index.html
  packages/pagination/README.md
  packages/pagination/examples/advanced.md
  packages/pagination/examples/basic.md
  packages/pagination/package.json
  packages/pagination/src/index.ts
  packages/pagination/src/styled/index.ts
  packages/pagination/stories/1-Readme.stories.mdx
  packages/pagination/stories/2-Pagination.stories.tsx
  packages/pagination/stories/3-CursorPagination.stories.tsx
  packages/pagination/styleguide.config.js
Labels: PR: Docs :memo:

#909 chore(docs): update migration doc
  docs/migration.md
Labels: PR: Docs :memo:
