Repository zendeskgarden/react-components, pull requests merged in 2020-12, with the labels that each got.

#947 chore(docs): update Menu arrow usage
  packages/dropdowns/README.md
Labels: PR: Docs :memo:

#948 fix(dropdowns): revert tab selection #943
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
Labels: PR: Bug Fix :bug:

#951 chore(accordions): update prop descriptions
  packages/accordions/src/elements/accordion/Accordion.tsx
  packages/accordions/src/elements/stepper/Stepper.tsx
Labels: PR: Docs :memo:

#952 chore(avatars): update prop descriptions
  packages/avatars/src/elements/Avatar.tsx
Labels: PR: Docs :memo:

#953 chore(buttons): update prop descriptions
  packages/buttons/src/elements/Anchor.tsx
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/ButtonGroup.tsx
  packages/buttons/src/elements/IconButton.tsx
  packages/buttons/src/elements/ToggleButton.tsx
  packages/buttons/src/elements/ToggleIconButton.tsx
Labels: PR: Docs :memo:

#954 chore(chrome): update prop descriptions
  packages/chrome/src/elements/Chrome.tsx
  packages/chrome/src/elements/body/Body.tsx
  packages/chrome/src/elements/header/HeaderItem.tsx
  packages/chrome/src/elements/nav/Nav.tsx
  packages/chrome/src/elements/nav/NavItem.tsx
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
  packages/chrome/src/elements/subnav/SubNavItem.tsx
  packages/chrome/src/styled/header/StyledBaseHeaderItem.ts
  packages/chrome/src/styled/header/StyledHeader.ts
  packages/chrome/src/styled/header/StyledHeaderItemText.ts
  packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
  packages/chrome/src/styled/nav/StyledNavItemText.ts
  packages/chrome/src/styled/subnav/StyledSubNavItemText.ts
Labels: PR: Docs :memo:

#955 feat(tables): introduce read-only styling
  packages/tables/.size-snapshot.json
  packages/tables/examples/basic.md
  packages/tables/src/elements/Row.spec.tsx
  packages/tables/src/elements/Row.tsx
  packages/tables/src/elements/Table.tsx
  packages/tables/src/styled/StyledRow.ts
  packages/tables/src/utils/useTableContext.ts
Labels: PR: New Feature :rocket:

#956 chore(datepickers): update prop descriptions
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.tsx
Labels: PR: Docs :memo:

#957 chore(dropdowns): update prop descriptions
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns/src/elements/Fields/Label.tsx
  packages/dropdowns/src/elements/Fields/Message.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
Labels: PR: Docs :memo:

#958 chore(forms): update prop descriptions
  packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
  packages/forms/src/elements/Checkbox.tsx
  packages/forms/src/elements/FauxInput.tsx
  packages/forms/src/elements/FileUpload.tsx
  packages/forms/src/elements/Input.tsx
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/elements/MultiThumbRange.tsx
  packages/forms/src/elements/Select.tsx
  packages/forms/src/elements/Textarea.tsx
  packages/forms/src/elements/common/Field.tsx
  packages/forms/src/elements/common/Label.tsx
  packages/forms/src/elements/common/Message.tsx
  packages/forms/src/elements/input-group/InputGroup.tsx
  packages/forms/src/elements/tiles/Tiles.tsx
  packages/forms/src/elements/tiles/components/Tile.tsx
Labels: PR: Docs :memo:

#959 chore(grid): update prop descriptions
  packages/grid/src/elements/Col.tsx
  packages/grid/src/elements/Grid.tsx
  packages/grid/src/elements/Row.tsx
Labels: PR: Docs :memo:

#960 chore(loaders): update prop descriptions
  packages/loaders/src/elements/Dots.tsx
  packages/loaders/src/elements/Inline.tsx
  packages/loaders/src/elements/Progress.tsx
  packages/loaders/src/elements/Skeleton.tsx
  packages/loaders/src/elements/Spinner.tsx
Labels: PR: Docs :memo:

#961 chore(modals): update prop descriptions
  packages/modals/src/elements/DrawerModal/DrawerModal.tsx
  packages/modals/src/elements/Modal.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
  packages/modals/src/styled/StyledHeader.ts
Labels: PR: Docs :memo:

#962 chore(notifications, pagination): update prop descriptions
  packages/notifications/src/elements/Alert.tsx
  packages/notifications/src/elements/Well.tsx
  packages/notifications/src/elements/content/Title.tsx
  packages/notifications/src/styled/StyledNotification.ts
  packages/pagination/src/elements/Pagination/Pagination.tsx
Labels: PR: Docs :memo:

#963 chore(tables): update prop descriptions
  packages/tables/src/elements/SortableCell.tsx
  packages/tables/src/styled/StyledCell.ts
  packages/tables/src/styled/StyledOverflowButton.ts
  packages/tables/src/styled/StyledRow.ts
  packages/tables/src/styled/StyledSortableButton.ts
  packages/tables/src/styled/StyledTable.ts
Labels: PR: Docs :memo:

#964 chore(tabs): update prop descriptions
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/src/elements/TabPanel.tsx
  packages/tabs/src/elements/Tabs.tsx
Labels: PR: Docs :memo:

#965 chore(tags): update prop descriptions
  packages/tags/src/elements/Tag.tsx
Labels: PR: Docs :memo:

#966 chore(tooltips): update prop descriptions
  packages/tooltips/src/elements/Tooltip.tsx
Labels: PR: Docs :memo:

#967 chore(typography): update prop descriptions
  packages/typography/src/elements/Blockquote.tsx
  packages/typography/src/elements/Code.tsx
  packages/typography/src/elements/CodeBlock.tsx
  packages/typography/src/elements/Ellipsis.tsx
  packages/typography/src/elements/LG.tsx
  packages/typography/src/elements/MD.tsx
  packages/typography/src/elements/Paragraph.tsx
  packages/typography/src/elements/SM.tsx
  packages/typography/src/elements/Span.tsx
  packages/typography/src/elements/XL.tsx
  packages/typography/src/elements/XXL.tsx
  packages/typography/src/elements/XXXL.tsx
  packages/typography/src/elements/lists/OrderedList.tsx
  packages/typography/src/elements/lists/UnorderedList.tsx
Labels: PR: Docs :memo:

#981 fix(tables): sortable cell truncation
  packages/tables/.size-snapshot.json
  packages/tables/src/elements/HeaderCell.spec.tsx
  packages/tables/src/elements/SortableCell.spec.tsx
  packages/tables/src/styled/StyledHeaderCell.ts
Labels: PR: Bug Fix :bug:
