Repository zendeskgarden/react-components, pull requests merged in 2020-03, with the labels that each got.

#657 fix(chrome): box-shadow and color styling
  packages/chrome/.size-snapshot.json
  packages/chrome/examples/header.md
  packages/chrome/src/styled/header/StyledHeader.ts
  packages/chrome/src/styled/nav/StyledLogoNavItem.ts
  packages/chrome/src/styled/nav/StyledNav.ts
  packages/chrome/src/styled/subnav/StyledSubNav.ts
Labels: PR: Bug Fix :bug:

#655 feat: add utility for menu styles
  docs/api.md
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
  packages/datepickers/src/elements/Datepicker/utils/garden-placements.ts
  packages/datepickers/src/styled/StyledMenu.ts
  packages/datepickers/src/styled/StyledMenu.tsx
  packages/datepickers/src/styled/StyledMenuWrapper.ts
  packages/datepickers/src/styled/index.ts
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Menu/Items/AddItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/AddItem.tsx
  packages/dropdowns/src/elements/Menu/Items/HeaderItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/HeaderItem.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaItem.tsx
  packages/dropdowns/src/elements/Menu/Items/NextItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/NextItem.tsx
  packages/dropdowns/src/elements/Menu/Items/PreviousItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/PreviousItem.tsx
  packages/dropdowns/src/elements/Menu/Menu.spec.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
  packages/dropdowns/src/elements/Menu/Separator.spec.tsx
  packages/dropdowns/src/elements/Menu/Separator.tsx
  packages/dropdowns/src/styled/index.ts
  packages/dropdowns/src/styled/items/StyledItem.ts
  packages/dropdowns/src/styled/menu/StyledMenu.ts
  packages/dropdowns/src/styled/menu/StyledMenu.tsx
  packages/dropdowns/src/styled/menu/StyledMenuWrapper.ts
  packages/dropdowns/src/styled/menu/StyledSeparator.ts
  packages/dropdowns/src/utils/garden-placements.ts
  packages/dropdowns/src/utils/gardenPlacements.spec.ts
  packages/theming/.size-snapshot.json
  packages/theming/src/index.ts
  packages/theming/src/utils/arrowStyles.ts
  packages/theming/src/utils/menuStyles.example.md
  packages/theming/src/utils/menuStyles.spec.tsx
  packages/theming/src/utils/menuStyles.ts
Labels: PR: Bug Fix :bug:, PR: New Feature :rocket:

#651 fix(all): allow server side rendering for all packages
  examples/gatsby/.gitignore
  examples/gatsby/gatsby-config.js
  examples/gatsby/package.json
  examples/gatsby/src/pages/index.js
  examples/gatsby/static/favicon.ico
  examples/gatsby/yarn.lock
  examples/nextjs/.babelrc
  examples/nextjs/.gitignore
  examples/nextjs/README.md
  examples/nextjs/components/layout.js
  examples/nextjs/next.config.js
  examples/nextjs/nextjs-example.png
  examples/nextjs/package.json
  examples/nextjs/pages/_app.js
  examples/nextjs/pages/_document.js
  examples/nextjs/pages/index.js
  examples/nextjs/yarn.lock
  lerna.json
  package.json
  packages/.template/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/datepickers/package.json
  packages/dropdowns/package.json
  packages/forms/.size-snapshot.json
  packages/forms/package.json
  packages/forms/src/elements/MultiThumbRange.tsx
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/.size-snapshot.json
  packages/modals/package.json
  packages/modals/src/elements/Modal.tsx
  packages/modals/yarn.lock
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/theming/.size-snapshot.json
  packages/theming/package.json
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/src/index.ts
  packages/theming/src/utils/useDocument.spec.tsx
  packages/theming/src/utils/useDocument.ts
  packages/theming/yarn.lock
  packages/tooltips/package.json
  packages/typography/package.json
  yarn.lock
Labels: PR: New Feature :rocket:

#659 fix(forms): allow controlled range to render background-size
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/Range.spec.tsx
  packages/forms/src/elements/Range.tsx
Labels: PR: Bug Fix :bug:

#654 feat(forms): introduce new Tiles component
  .eslintrc.json
  packages/forms/.size-snapshot.json
  packages/forms/examples/tiles.md
  packages/forms/src/elements/tiles/Tiles.spec.tsx
  packages/forms/src/elements/tiles/Tiles.tsx
  packages/forms/src/elements/tiles/components/Description.tsx
  packages/forms/src/elements/tiles/components/Icon.tsx
  packages/forms/src/elements/tiles/components/Label.tsx
  packages/forms/src/elements/tiles/components/Tile.tsx
  packages/forms/src/index.ts
  packages/forms/src/styled/index.ts
  packages/forms/src/styled/tiles/StyledTile.ts
  packages/forms/src/styled/tiles/StyledTileDescription.ts
  packages/forms/src/styled/tiles/StyledTileIcon.ts
  packages/forms/src/styled/tiles/StyledTileInput.ts
  packages/forms/src/styled/tiles/StyledTileLabel.ts
  packages/forms/src/utils/useTilesContext.ts
  packages/forms/styleguide.config.js
Labels: PR: New Feature :rocket:

#661 fix: Update Modal's prop type for appendToNode to be PropType.any
  packages/modals/src/elements/Modal.js
Labels: PR: Bug Fix :bug:

#662 feat(modal): update Modal prop type for appendToNode to any
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/Modal.tsx
Labels: PR: Bug Fix :bug:

#663 fix(modals): include useModal args as props
  packages/modals/.size-snapshot.json
  packages/modals/package.json
  packages/modals/src/elements/Modal.tsx
  packages/modals/yarn.lock
Labels: PR: Bug Fix :bug:

#664 chore: update to use CircleCI
  .circleci/config.yml
  .travis.yml
  README.md
  package.json
  packages/.template/README.md
  packages/avatars/README.md
  packages/breadcrumbs/README.md
  packages/buttons/README.md
  packages/chrome/README.md
  packages/datepickers/README.md
  packages/dropdowns/README.md
  packages/forms/README.md
  packages/grid/README.md
  packages/loaders/README.md
  packages/modals/README.md
  packages/notifications/README.md
  packages/pagination/README.md
  packages/tables/README.md
  packages/tabs/README.md
  packages/tags/README.md
  packages/theming/README.md
  packages/tooltips/README.md
  packages/typography/README.md
  packages/utilities/README.md
  utils/scripts/gh-pages.js
  utils/travis/publish-gh-pages.sh
Labels: PR: Internal :seedling:

#665 chore: fix CircleCI config
  .circleci/config.yml
  .nvmrc
Labels: PR: Bug Fix :bug:

#666 chore: add /examples to renovate configuration
  .circleci/config.yml
  .github/ISSUE_TEMPLATE.md
  .nvmrc
  README.md
  examples/codesandbox/.env
  examples/codesandbox/.gitignore
  examples/codesandbox/.prettierrc
  examples/codesandbox/package.json
  examples/codesandbox/public/favicon.ico
  examples/codesandbox/public/index.html
  examples/codesandbox/public/manifest.json
  examples/codesandbox/src/components/ExampleWrapper.js
  examples/codesandbox/src/examples/Example.js
  examples/codesandbox/src/index.js
  examples/codesandbox/yarn.lock
  package.json
  renovate.json
  yarn.lock
Labels: PR: Internal :seedling:

#658 feat(accordions): introduce new Stepper component
  README.md
  demo/index.html
  packages/accordions/.size-snapshot.json
  packages/accordions/README.md
  packages/accordions/examples/basic.md
  packages/accordions/package.json
  packages/accordions/src/elements/Stepper.spec.tsx
  packages/accordions/src/elements/Stepper.tsx
  packages/accordions/src/elements/components/Step.spec.tsx
  packages/accordions/src/elements/components/Step.tsx
  packages/accordions/src/elements/components/StepContent.spec.tsx
  packages/accordions/src/elements/components/StepContent.tsx
  packages/accordions/src/elements/components/StepLabel.spec.tsx
  packages/accordions/src/elements/components/StepLabel.tsx
  packages/accordions/src/index.ts
  packages/accordions/src/styled/StyledContent.spec.tsx
  packages/accordions/src/styled/StyledContent.ts
  packages/accordions/src/styled/StyledIcon.spec.tsx
  packages/accordions/src/styled/StyledIcon.ts
  packages/accordions/src/styled/StyledInnerContent.tsx
  packages/accordions/src/styled/StyledLabel.spec.tsx
  packages/accordions/src/styled/StyledLabel.ts
  packages/accordions/src/styled/StyledLabelText.spec.tsx
  packages/accordions/src/styled/StyledLabelText.ts
  packages/accordions/src/styled/StyledLine.ts
  packages/accordions/src/styled/StyledStep.spec.tsx
  packages/accordions/src/styled/StyledStep.ts
  packages/accordions/src/styled/StyledStepper.spec.tsx
  packages/accordions/src/styled/StyledStepper.ts
  packages/accordions/src/styled/index.ts
  packages/accordions/src/utils/index.ts
  packages/accordions/src/utils/useStepContext.ts
  packages/accordions/src/utils/useStepperContext.ts
  packages/accordions/styleguide.config.js
  packages/accordions/tsconfig.build.json
  packages/accordions/yarn.lock
  utils/styleguide/styleguide.base.config.js
Labels: PR: New Feature :rocket:

#667 chore: fix CircleCI deploy
  .circleci/config.yml
  demo/index.html
  package.json
  packages/.template/README.md
  packages/accordions/README.md
  packages/avatars/README.md
  packages/avatars/examples/advanced.md
  packages/breadcrumbs/README.md
  packages/buttons/README.md
  packages/chrome/README.md
  packages/datepickers/README.md
  packages/dropdowns/README.md
  packages/forms/README.md
  packages/grid/README.md
  packages/loaders/README.md
  packages/modals/README.md
  packages/notifications/README.md
  packages/pagination/README.md
  packages/tables/README.md
  packages/tabs/README.md
  packages/tags/README.md
  packages/theming/README.md
  packages/tooltips/README.md
  packages/typography/README.md
  packages/utilities/README.md
  renovate.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#674 chore: update gh-pages deploy
  .circleci/config.yml
  utils/scripts/gh-pages.js
Labels: PR: Internal :seedling:

#676 feat(theming): add gather product color
  packages/theming/.size-snapshot.json
  packages/theming/README.md
  packages/theming/package.json
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.ts
Labels: PR: New Feature :rocket:

#678 fix(theming): remove Hue usage to allow TS projects to build
  packages/theming/src/utils/getColor.ts
  utils/build/styled.d.ts
Labels: PR: Bug Fix :bug:

#679 fix(tiles): update Tiles label wrapping and Icon colors
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/tiles/StyledTile.ts
  packages/forms/src/styled/tiles/StyledTileIcon.ts
  packages/forms/src/styled/tiles/StyledTileLabel.ts
Labels: PR: Bug Fix :bug:

#680 chore: sync local tags with remote
  utils/scripts/version.sh
Labels: PR: Internal :seedling:

#681 chore: update `format` commands for CI
  .circleci/config.yml
  package.json
Labels: PR: Internal :seedling:

#682 feat(tags): allow flexible tag hue
  packages/tags/.size-snapshot.json
  packages/tags/examples/advanced.md
  packages/tags/examples/basic.md
  packages/tags/src/elements/Tag.tsx
  packages/tags/src/styled/StyledTag.ts
Labels: PR: New Feature :rocket:

#683 fix: use default CircleCI node_modules cache
  .circleci/config.yml
  package.json
Labels: PR: Internal :seedling:

#685 chore(steppers): reorganize directory structure
  packages/accordions/.size-snapshot.json
  packages/accordions/examples/basic.md
  packages/accordions/src/elements/components/StepContent.tsx
  packages/accordions/src/elements/stepper/Stepper.spec.tsx
  packages/accordions/src/elements/stepper/Stepper.tsx
  packages/accordions/src/elements/stepper/components/Content.spec.tsx
  packages/accordions/src/elements/stepper/components/Content.tsx
  packages/accordions/src/elements/stepper/components/Label.spec.tsx
  packages/accordions/src/elements/stepper/components/Label.tsx
  packages/accordions/src/elements/stepper/components/Step.spec.tsx
  packages/accordions/src/elements/stepper/components/Step.tsx
  packages/accordions/src/index.ts
  packages/accordions/src/styled/index.ts
  packages/accordions/src/styled/stepper/StyledContent.spec.tsx
  packages/accordions/src/styled/stepper/StyledContent.ts
  packages/accordions/src/styled/stepper/StyledIcon.spec.tsx
  packages/accordions/src/styled/stepper/StyledIcon.ts
  packages/accordions/src/styled/stepper/StyledInnerContent.tsx
  packages/accordions/src/styled/stepper/StyledLabel.spec.tsx
  packages/accordions/src/styled/stepper/StyledLabel.ts
  packages/accordions/src/styled/stepper/StyledLabelText.spec.tsx
  packages/accordions/src/styled/stepper/StyledLabelText.ts
  packages/accordions/src/styled/stepper/StyledLine.ts
  packages/accordions/src/styled/stepper/StyledStep.spec.tsx
  packages/accordions/src/styled/stepper/StyledStep.ts
  packages/accordions/src/styled/stepper/StyledStepper.spec.tsx
  packages/accordions/src/styled/stepper/StyledStepper.ts
  packages/accordions/styleguide.config.js
Labels: PR: Internal :seedling:

#684 fix(dropdowns): conditionally apply popper ref to Menu
  packages/dropdowns/src/Menu/Menu.tsx
Labels: PR: Bug Fix :bug:

#688 fix: correct build status badge links
  README.md
Labels: PR: Docs :memo:

#686 chore: configure CircleCI for v7 branch
  .circleci/config.yml
  .travis.yml
  README.md
  package.json
Labels: PR: Internal :seedling:

#687 chore: configure CircleCI for v6 branch
  .circleci/config.yml
  .travis.yml
  README.md
  package.json
Labels: PR: Internal :seedling:

#689 feat(avatars): add XXS avatar size
  packages/avatars/.size-snapshot.json
  packages/avatars/examples/basic.md
  packages/avatars/src/elements/Avatar.tsx
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/styled/StyledAvatar.ts
Labels: PR: New Feature :rocket:

#690 fix(dropdowns, datepickers): restore menu theming and prevent autocomplete pixel nudge
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/styled/StyledMenuWrapper.ts
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/styled/field/StyledSelect.ts
  packages/dropdowns/src/styled/menu/StyledMenuWrapper.ts
  packages/forms/.size-snapshot.json
  packages/forms/examples/advanced.md
  packages/forms/src/styled/text/StyledTextFauxInput.ts
  packages/theming/src/utils/menuStyles.example.md
Labels: PR: Bug Fix :bug:
