Repository zendeskgarden/react-components, pull requests merged in 2020-05, with the labels that each got.

#735 fix(breadcrumbs): change chevron color from black to grey-600
  packages/breadcrumbs/.size-snapshot.json
  packages/breadcrumbs/src/styled/StyledChevronIcon.tsx
Labels: PR: Bug Fix :bug:

#733 feat(forms/dropdowns): improve start icon sizing
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/styled/field/SelectWrapper.tsx
  packages/dropdowns/src/styled/field/StyledSelect.ts
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/styled/text/StyledTextInput.ts
  packages/forms/src/styled/text/StyledTextMediaFigure.spec.tsx
  packages/forms/src/styled/text/StyledTextMediaFigure.ts
Labels: PR: New Feature :rocket:

#736 chore: deploy script improvements
  .circleci/config.yml
  package.json
  utils/scripts/deploy.js
  utils/scripts/tag.js
  yarn.lock
Labels: PR: Internal :seedling:

#743 chore(deps): update @zendeskgarden/scripts
  package.json
  yarn.lock
Labels: PR: Internal :seedling:

#745 chore(build): update yarn.lock file
  packages/accordions/.size-snapshot.json
  packages/breadcrumbs/.size-snapshot.json
  packages/buttons/.size-snapshot.json
  packages/chrome/.size-snapshot.json
  packages/datepickers/.size-snapshot.json
  packages/dropdowns/.size-snapshot.json
  packages/forms/.size-snapshot.json
  packages/modals/.size-snapshot.json
  packages/notifications/.size-snapshot.json
  packages/pagination/.size-snapshot.json
  packages/tables/.size-snapshot.json
  packages/tags/.size-snapshot.json
  yarn.lock
Labels: PR: Internal :seedling:

#734 fix(dropdowns): use correct aria attributes for menu dropdown
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
  packages/dropdowns/src/utils/useDropdownContext.ts
Labels: PR: Bug Fix :bug:

#746 feat(grid): add `textAlign` prop to `Col` component
  packages/grid/.size-snapshot.json
  packages/grid/examples/basic.md
  packages/grid/src/elements/Col.tsx
  packages/grid/src/styled/StyledCol.spec.tsx
  packages/grid/src/styled/StyledCol.ts
  packages/grid/src/utils/types.ts
Labels: PR: New Feature :rocket:

#747 fix(dropdowns): inputValue logic when selected
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
Labels: PR: Bug Fix :bug:

#749 fix(scripts): support terminal-based editors for changelog step in tag sequence
  utils/scripts/tag.js
Labels: PR: Internal :seedling:

#748 fix(accordions): improve vertical mobile stepper spacing
  packages/accordions/.size-snapshot.json
  packages/accordions/src/styled/stepper/StyledContent.spec.tsx
  packages/accordions/src/styled/stepper/StyledContent.ts
  packages/accordions/src/styled/stepper/StyledIcon.spec.tsx
  packages/accordions/src/styled/stepper/StyledIcon.ts
  packages/accordions/src/styled/stepper/StyledLine.ts
Labels: PR: Bug Fix :bug:

#750 feat(typography): add Span component and allow Code to inherit
  packages/typography/.size-snapshot.json
  packages/typography/examples/code.md
  packages/typography/examples/span.md
  packages/typography/src/elements/Code.tsx
  packages/typography/src/elements/Paragraph.tsx
  packages/typography/src/elements/Span.spec.tsx
  packages/typography/src/elements/Span.tsx
  packages/typography/src/index.ts
  packages/typography/src/styled/StyledCode.spec.tsx
  packages/typography/src/styled/StyledCode.ts
  packages/typography/src/styled/StyledFont.spec.tsx
  packages/typography/src/styled/StyledFont.tsx
  packages/typography/styleguide.config.js
Labels: PR: New Feature :rocket:

#752 chore(scripts): update tag script to force install
  utils/scripts/tag.js
Labels: PR: Internal :seedling:

#753 chore(utils): force version tag
  package.json
  utils/scripts/tag.js
  yarn.lock
Labels: PR: Internal :seedling:

#754 fix(modals): vertically center close button SVG
  package.json
  packages/modals/.size-snapshot.json
  packages/modals/src/styled/StyledClose.ts
  utils/styleguide/TableOfContentsRenderer/index.js
  utils/styleguide/Wrapper/index.js
  utils/styleguide/styleguide.base.config.js
  yarn.lock
Labels: PR: Bug Fix :bug:

#755 feat(tags): support mixed weight content
  packages/tags/.size-snapshot.json
  packages/tags/examples/advanced.md
  packages/tags/examples/basic.md
  packages/tags/src/elements/Tag.tsx
  packages/tags/src/styled/StyledTag.spec.tsx
  packages/tags/src/styled/StyledTag.ts
Labels: PR: New Feature :rocket:

#756 fix(dropdowns): prevent icon box-sizing inheritance
  .github/PULL_REQUEST_TEMPLATE.md
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/styled/field/SelectWrapper.tsx
  packages/dropdowns/src/styled/field/StyledSelect.ts
Labels: PR: Bug Fix :bug:

#751 feat(buttons): revise button padding
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledButton.ts
Labels: PR: New Feature :rocket:
