Repository zendeskgarden/react-components, pull requests merged in 2020-06, with the labels that each got.

#759 fix(dropdowns): remove type attribute from div
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/styled/field/StyledSelect.ts
Labels: PR: Bug Fix :bug:

#757 feat(buttons): new toggle button components
  .eslintrc.json
  packages/buttons/.size-snapshot.json
  packages/buttons/README.md
  packages/buttons/examples/basic.md
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/ChevronButton.tsx
  packages/buttons/src/elements/IconButton.tsx
  packages/buttons/src/elements/ToggleButton.spec.tsx
  packages/buttons/src/elements/ToggleButton.tsx
  packages/buttons/src/elements/ToggleIconButton.spec.tsx
  packages/buttons/src/elements/ToggleIconButton.tsx
  packages/buttons/src/index.ts
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledIconButton.ts
Labels: PR: New Feature :rocket:

#772 fix(dropdowns): remove type attribute from div
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
Labels: PR: Bug Fix :bug:

#775 chore: update renovate schedule
  .github/PULL_REQUEST_TEMPLATE.md
  .github/renovate.json
Labels: PR: Internal :seedling:

#776 fix(menus): prevent inherited line-height from affecting positioning
  packages/theming/.size-snapshot.json
  packages/theming/src/utils/menuStyles.ts
Labels: PR: Bug Fix :bug:

#774 feat(theming): update palette to match new brand colors
  packages/chrome/.size-snapshot.json
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/styled/nav/StyledNavItem.ts
  packages/notifications/src/styled/StyledBase.spec.tsx
  packages/theming/.size-snapshot.json
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.ts
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
Labels: PR: New Feature :rocket:

#777 fix(accordions): correct spacing for rotate icon
  packages/accordions/.size-snapshot.json
  packages/accordions/src/styled/accordion/StyledRotateIcon.ts
Labels: PR: Bug Fix :bug:

#779 chore(docs): update Multiselect example to allow IME input
  packages/dropdowns/examples/multiselect.md
Labels: PR: Docs :memo:

#780 fix(tables): cell and overflow padding
  packages/tables/.size-snapshot.json
  packages/tables/examples/paginated-table.md
  packages/tables/examples/selectable-table.md
  packages/tables/src/elements/Cell.spec.tsx
  packages/tables/src/styled/StyledCell.ts
Labels: PR: Bug Fix :bug:

#781 feat(typography): add isMonospace prop to Span component
  packages/typography/.size-snapshot.json
  packages/typography/examples/span.md
  packages/typography/src/elements/Span.tsx
Labels: PR: New Feature :rocket:

#783 fix(grid): remove relative position from col
  packages/grid/.size-snapshot.json
  packages/grid/src/styled/StyledCol.spec.tsx
  packages/grid/src/styled/StyledCol.ts
Labels: PR: Bug Fix :bug:

#784 chore: remove pendo snippet
  package.json
  utils/styleguide/styleguide.base.config.js
Labels: PR: Internal :seedling:

#785 fix(buttons): inline display for button groups
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledButtonGroup.ts
Labels: PR: Bug Fix :bug:

#786 feat(dropdowns): allow Select to receive alphanumeric selection
  .circleci/config.yml
  packages/dropdowns/src/Dropdown/Dropdown.tsx
  packages/dropdowns/src/Menu/Items/Item.ts
  packages/dropdowns/src/Menu/Menu.tsx
  packages/dropdowns/src/Select/Select.tsx
  packages/dropdowns/src/Trigger/Trigger.tsx
Labels: PR: New Feature :rocket:

#787 feat(dropdowns): allow Select to search with keyboard interaction
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
  packages/dropdowns/src/utils/useDropdownContext.ts
Labels: PR: New Feature :rocket:

#788 fix(notifications): add support for regular weight title
  packages/notifications/.size-snapshot.json
  packages/notifications/examples/basic.md
  packages/notifications/src/elements/content/Title.spec.tsx
  packages/notifications/src/elements/content/Title.tsx
  packages/notifications/src/styled/content/StyledTitle.ts
Labels: PR: Bug Fix :bug:
