Repository zendeskgarden/react-components, pull requests merged in 2020-11, with the labels that each got.

#923 fix(dropdowns): keep focus on multiselect input when navigating previous item
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
Labels: PR: Bug Fix :bug:

#927 chore(breadcrumbs): update prop descriptions
  packages/breadcrumbs/src/elements/Breadcrumb.tsx
Labels: PR: Docs :memo:

#929 feat(modals): add prop type checks
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/DrawerModal/DrawerModal.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
Labels: PR: New Feature :rocket:

#910 chore(docs): migrate react-modals examples to Storybook
  demo/index.html
  packages/modals/.size-snapshot.json
  packages/modals/README.md
  packages/modals/examples/basic.md
  packages/modals/examples/drawer-modal.md
  packages/modals/package.json
  packages/modals/src/styled/index.ts
  packages/modals/stories/1-Readme.stories.mdx
  packages/modals/stories/2-Modal.stories.tsx
  packages/modals/stories/3-DrawerModal.stories.tsx
  packages/modals/stories/4-TooltipModal.stories.tsx
Labels: PR: Docs :memo:

#924 chore(accordions): update prop descriptions
  packages/accordions/src/elements/accordion/Accordion.tsx
  packages/accordions/src/elements/stepper/components/Label.tsx
Labels: PR: Docs :memo:

#926 chore(avatars): update prop descriptions
  packages/avatars/src/elements/Avatar.tsx
Labels: PR: Docs :memo:

#933 chore(deps): update react
  package.json
  yarn.lock
Labels: PR: Internal :seedling:

#935 feat(accordions): allow animation to be turned off
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/accordion/Accordion.tsx
  packages/accordions/src/elements/accordion/components/Panel.tsx
  packages/accordions/src/styled/accordion/StyledInnerPanel.spec.tsx
  packages/accordions/src/styled/accordion/StyledInnerPanel.ts
  packages/accordions/src/styled/accordion/StyledPanel.spec.tsx
  packages/accordions/src/styled/accordion/StyledPanel.ts
  packages/accordions/src/utils/useAccordionContext.ts
  packages/accordions/stories/examples/Uncontrolled.tsx
Labels: PR: New Feature :rocket:

#925 feat(typography): support anchor-styled code snippets
  packages/typography/.size-snapshot.json
  packages/typography/src/styled/StyledCode.spec.tsx
  packages/typography/src/styled/StyledCode.ts
  packages/typography/stories/2-Code.stories.tsx
Labels: PR: New Feature :rocket:

#937 feat(typography): add Blockquote component
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  packages/typography/.size-snapshot.json
  packages/typography/src/elements/Blockquote.spec.tsx
  packages/typography/src/elements/Blockquote.tsx
  packages/typography/src/index.ts
  packages/typography/src/styled/StyledBlockquote.spec.tsx
  packages/typography/src/styled/StyledBlockquote.ts
  packages/typography/src/styled/index.ts
  packages/typography/stories/2-Blockquote.stories.tsx
  utils/test/jest.config.js
Labels: PR: New Feature :rocket:

#939 feat(typography): add Blockquote size prop to control sibling spacing
  packages/typography/.size-snapshot.json
  packages/typography/src/elements/Blockquote.spec.tsx
  packages/typography/src/elements/Blockquote.tsx
  packages/typography/src/elements/Paragraph.spec.tsx
  packages/typography/src/styled/StyledBlockquote.ts
  packages/typography/src/styled/StyledParagraph.spec.tsx
  packages/typography/src/styled/StyledParagraph.ts
  packages/typography/stories/2-Blockquote.stories.tsx
Labels: PR: New Feature :rocket:

#936 fix(loaders): fix Dot loader for IE11
  packages/loaders/.size-snapshot.json
  packages/loaders/src/elements/Dots.spec.tsx
  packages/loaders/src/elements/Dots.tsx
  packages/loaders/src/utils/useCSSSVGAnimation.spec.tsx
  packages/loaders/src/utils/useCSSSVGAnimation.ts
Labels: PR: Bug Fix :bug:

#940 fix(forms): restore relative positioning context on Field container
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/common/StyledField.ts
Labels: PR: Bug Fix :bug:

#941 chore: fix production storybook navigation
  .circleci/config.yml
  .storybook/gardenTheme.js
  .storybook/preview.js
Labels: PR: Internal :seedling:

#944 fix(build): ensure jest is able to run tests in all environments
  package.json
  yarn.lock
Labels: PR: Bug Fix :bug:

#942 fix(dropdowns): ensure Tab key selects highlighted items
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/examples/advanced-select.md
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
Labels: PR: Bug Fix :bug:

#943 feat(dropdowns): ensure dropdowns allow space key in Safari with voiceover
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
Labels: PR: Bug Fix :bug:
