Repository zendeskgarden/react-components, pull requests merged in 2021-04, with the labels that each got.

#1072 fix(notifications): use IE11 compatible react-uid
  packages/notifications/.size-snapshot.json
  packages/notifications/package.json
  packages/notifications/src/elements/toaster/useToast.ts
  packages/notifications/yarn.lock
Labels: PR: Bug Fix :bug:

#1071 fix(colorpickers): allow props to be applied to color dialog trigger
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/elements/ColorpickerDialog/index.spec.tsx
  packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
  packages/colorpickers/stories/examples/ColorpickerDialog/Controlled.tsx
  packages/colorpickers/stories/examples/ColorpickerDialog/Uncontrolled.tsx
Labels: PR: Bug Fix :bug:

#1073 feat(dropdowns): new combobox component
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Combobox/Combobox.spec.tsx
  packages/dropdowns/src/elements/Combobox/Combobox.tsx
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/index.ts
  packages/dropdowns/src/utils/useDropdownContext.ts
  packages/dropdowns/stories/6-Combobox.stories.tsx
  packages/dropdowns/stories/examples/Autocomplete/Default.tsx
  packages/dropdowns/stories/examples/Combobox/Default.tsx
  packages/dropdowns/stories/examples/Select/Advanced.tsx
  packages/dropdowns/stories/examples/Select/Default.tsx
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/FauxInput.tsx
  packages/forms/src/elements/MediaInput.tsx
Labels: PR: New Feature :rocket:

#1074 fix(colorpickers): override tooltip modal width
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/styled/ColorpickerDialog/StyledTooltipModal.ts
Labels: PR: Bug Fix :bug:

#1075 fix(colorpickers): stabilize slider position styling
  package.json
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/styled/Colorpicker/StyledSliders.ts
Labels: PR: Bug Fix :bug:

#1078 chore(dropdowns): update lock & upgrade downshift
  packages/dropdowns/yarn.lock
Labels: PR: Internal :seedling:
