Repository zendeskgarden/react-components, pull requests merged in 2021-03, with the labels that each got.

#1023 fix(typography): prevent monospace Code and Span from pixel shifting line heights
  packages/avatars/examples/advanced.md
  packages/avatars/examples/basic.md
  packages/typography/.size-snapshot.json
  packages/typography/examples/code.md
  packages/typography/examples/codeblock.md
  packages/typography/examples/ellipsis.md
  packages/typography/examples/lists.md
  packages/typography/examples/paragraph.md
  packages/typography/examples/span.md
  packages/typography/examples/typography.md
  packages/typography/src/styled/StyledFont.spec.tsx
  packages/typography/src/styled/StyledFont.tsx
  packages/typography/stories/2-Code.stories.tsx
  packages/typography/stories/5-Paragraph.stories.tsx
Labels: PR: Bug Fix :bug:

#1025 chore(modals): upgrade container-modal version
  packages/modals/package.json
  packages/modals/yarn.lock
Labels: PR: Internal :seedling:

#1021 feat(notifications): introduce toast pattern and utilities
  package.json
  packages/modals/package.json
  packages/modals/yarn.lock
  packages/notifications/.size-snapshot.json
  packages/notifications/README.md
  packages/notifications/package.json
  packages/notifications/src/elements/toaster/Toast.tsx
  packages/notifications/src/elements/toaster/ToastProvider.spec.tsx
  packages/notifications/src/elements/toaster/ToastProvider.tsx
  packages/notifications/src/elements/toaster/ToastSlot.spec.tsx
  packages/notifications/src/elements/toaster/ToastSlot.tsx
  packages/notifications/src/elements/toaster/reducer.ts
  packages/notifications/src/elements/toaster/styled.ts
  packages/notifications/src/elements/toaster/useToast.spec.tsx
  packages/notifications/src/elements/toaster/useToast.ts
  packages/notifications/src/index.ts
  packages/notifications/stories/5-Toasts.stories.tsx
  packages/notifications/yarn.lock
  packages/tables/yarn.lock
  yarn.lock
Labels: PR: New Feature :rocket:

#1024 fix(modals): fadeout tooltip modal
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
  packages/modals/src/styled/StyledTooltipModal.ts
  packages/modals/src/styled/StyledTooltipModalBackdrop.ts
  packages/modals/stories/4-TooltipModal.stories.tsx
Labels: PR: Bug Fix :bug:

#1029 fix(colorpickers): fix broken color picker dialog test
  packages/colorpickers/src/elements/ColorpickerDialog/index.spec.tsx
Labels: PR: Bug Fix :bug:

#1030 fix(colorpickers): move react-buttons to a direct dependency
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/package.json
  packages/colorpickers/yarn.lock
Labels: PR: Bug Fix :bug:

#1031 fix(colorpickers): disable hex spell checking and arrow by default
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/elements/Colorpicker/index.tsx
  packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
Labels: PR: Bug Fix :bug:

#1028 chore(docs): migrate react-forms to storybook
  demo/index.html
  packages/forms/README.md
  packages/forms/examples/advanced.md
  packages/forms/examples/basic.md
  packages/forms/examples/input-group.md
  packages/forms/examples/tiles.md
  packages/forms/package.json
  packages/forms/stories/1-Readme.stories.mdx
  packages/forms/stories/10-Range.stories.tsx
  packages/forms/stories/11-MultiThumbRange.stories.tsx
  packages/forms/stories/12-Tiles.stories.tsx
  packages/forms/stories/13-InputGroup.stories.tsx
  packages/forms/stories/14-FileUpload.stories.tsx
  packages/forms/stories/2-Input.stories.tsx
  packages/forms/stories/3-Textarea.stories.tsx
  packages/forms/stories/4-MediaInput.stories.tsx
  packages/forms/stories/5-FauxInput.stories.tsx
  packages/forms/stories/6-Select.stories.tsx
  packages/forms/stories/7-Checkbox.stories.tsx
  packages/forms/stories/8-Radio.stories.tsx
  packages/forms/stories/9-Toggle.stories.tsx
  packages/forms/stories/story-types.ts
Labels: PR: Docs :memo:

#1034 fix(colorpickers): prevent subpixel slider height increase
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/styled/Colorpicker/StyledSliders.ts
Labels: PR: Bug Fix :bug:

#1035 fix(modals): TooltipModal arrow styling
  packages/modals/.size-snapshot.json
  packages/modals/src/styled/StyledTooltipModal.ts
Labels: PR: Bug Fix :bug:

#1033 fix(colorpickers|tooltips): color well and tooltip fixes
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/package.json
  packages/colorpickers/src/elements/Colorpicker/ColorWell.tsx
  packages/colorpickers/src/elements/ColorpickerDialog/index.spec.tsx
  packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
  packages/colorpickers/stories/examples/ColorpickerDialog/WithIconButton.tsx
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
  packages/tooltips/.size-snapshot.json
  packages/tooltips/package.json
  packages/tooltips/src/elements/Tooltip.tsx
  packages/tooltips/yarn.lock
Labels: PR: Bug Fix :bug:

#1039 fix(deps): update dropdowns peer dependencies to include React v17
  packages/dropdowns/package.json
Labels: PR: Bug Fix :bug:

#1040 fix(colorpickers): add missing popper dependency
  packages/colorpickers/package.json
  packages/colorpickers/yarn.lock
Labels: PR: Bug Fix :bug:

#1043 fix(colorpickers): add missing react-popper peer dependency
  packages/colorpickers/package.json
Labels: PR: Bug Fix :bug:

#1037 chore(dropdowns): migrate react-dropdowns to Storybook
  demo/index.html
  packages/dropdowns/README.md
  packages/dropdowns/examples/advanced-menu.md
  packages/dropdowns/examples/advanced-select.md
  packages/dropdowns/examples/autocomplete.md
  packages/dropdowns/examples/basic-menu.md
  packages/dropdowns/examples/basic-select.md
  packages/dropdowns/examples/examples.md
  packages/dropdowns/examples/field-variants.md
  packages/dropdowns/examples/multiselect.md
  packages/dropdowns/examples/tree-menu.md
  packages/dropdowns/package.json
  packages/dropdowns/stories/1-Readme.stories.mdx
  packages/dropdowns/stories/2-Menu.stories.tsx
  packages/dropdowns/stories/3-Select.stories.tsx
  packages/dropdowns/stories/4-Autocomplete.stories.tsx
  packages/dropdowns/stories/5-Multiselect.stories.tsx
  packages/dropdowns/stories/examples/Autocomplete/Default.tsx
  packages/dropdowns/stories/examples/Menu/Advanced.tsx
  packages/dropdowns/stories/examples/Menu/Default.tsx
  packages/dropdowns/stories/examples/Menu/Icon.tsx
  packages/dropdowns/stories/examples/Menu/Tree.tsx
  packages/dropdowns/stories/examples/Multiselect/Default.tsx
  packages/dropdowns/stories/examples/Select/Advanced.tsx
  packages/dropdowns/stories/examples/Select/Default.tsx
Labels: PR: Docs :memo:

#1041 feat(forms): add support for accessibly hidden labels
  packages/datepickers/stories/3-Range.stories.tsx
  packages/datepickers/stories/examples/Default.tsx
  packages/dropdowns/stories/examples/Autocomplete/Default.tsx
  packages/dropdowns/stories/examples/Multiselect/Default.tsx
  packages/dropdowns/stories/examples/Select/Advanced.tsx
  packages/dropdowns/stories/examples/Select/Default.tsx
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/common/StyledLabel.spec.tsx
  packages/forms/src/styled/common/StyledLabel.ts
  packages/forms/src/styled/common/StyledMessage.spec.tsx
  packages/forms/src/styled/common/StyledMessage.ts
  packages/forms/src/styled/file-upload/StyledFileUpload.ts
  packages/forms/src/styled/input-group/StyledInputGroup.ts
  packages/forms/src/styled/radio/StyledRadioLabel.ts
  packages/forms/src/styled/range/StyledRangeInput.spec.tsx
  packages/forms/src/styled/range/StyledRangeInput.ts
  packages/forms/src/styled/range/StyledSlider.spec.tsx
  packages/forms/src/styled/range/StyledSlider.ts
  packages/forms/src/styled/text/StyledTextFauxInput.ts
  packages/forms/src/styled/text/StyledTextInput.ts
  packages/forms/stories/10-Range.stories.tsx
  packages/forms/stories/11-MultiThumbRange.stories.tsx
  packages/forms/stories/13-InputGroup.stories.tsx
  packages/forms/stories/14-FileUpload.stories.tsx
  packages/forms/stories/2-Input.stories.tsx
  packages/forms/stories/3-Textarea.stories.tsx
  packages/forms/stories/4-MediaInput.stories.tsx
  packages/forms/stories/5-FauxInput.stories.tsx
  packages/forms/stories/6-Select.stories.tsx
  packages/forms/stories/story-types.ts
Labels: PR: New Feature :rocket:

#1047 chore(docs): migrate react-grid to storybook
  demo/index.html
  packages/grid/README.md
  packages/grid/examples/advanced.md
  packages/grid/examples/basic.md
  packages/grid/package.json
  packages/grid/stories/1-Readme.stories.mdx
  packages/grid/stories/2-Grid.stories.tsx
  packages/grid/stories/examples/Default.tsx
  packages/grid/styleguide.config.js
Labels: PR: Docs :memo:

#1049 chore(docs): use evergreen bedrock CSS link
  .storybook/preview-head.html
  .storybook/preview.js
Labels: PR: Internal :seedling:

#1050 fix(accordions): stepper and accordion typeface styling
  .storybook/preview.js
  packages/accordions/.size-snapshot.json
  packages/accordions/src/styled/accordion/StyledButton.ts
  packages/accordions/src/styled/stepper/StyledIcon.spec.tsx
  packages/accordions/src/styled/stepper/StyledIcon.ts
  packages/accordions/src/styled/stepper/StyledInnerContent.ts
  packages/accordions/src/styled/stepper/StyledLabel.spec.tsx
  packages/accordions/src/styled/stepper/StyledLabel.ts
Labels: PR: Bug Fix :bug:

#1052 fix(modals): allow pointer-events to pass through fading tooltip modal
  packages/modals/.size-snapshot.json
  packages/modals/src/styled/StyledTooltipModalBackdrop.ts
Labels: PR: Bug Fix :bug:

#1054 chore(modals): upgrade container-modal
  packages/modals/package.json
  packages/modals/yarn.lock
Labels: PR: Internal :seedling:

#1056 chore(modals): remove @types/react-transition-group direct dependency
  packages/modals/package.json
  packages/modals/yarn.lock
Labels: PR: Internal :seedling:

#1057 chore(modals): update README example to use correct props
  packages/modals/README.md
Labels: PR: Docs :memo:

#1055 feat(notifications): allow placement customizations for toast
  packages/notifications/.size-snapshot.json
  packages/notifications/src/elements/toaster/ToastProvider.spec.tsx
  packages/notifications/src/elements/toaster/ToastProvider.tsx
  packages/notifications/src/elements/toaster/ToastSlot.tsx
  packages/notifications/src/elements/toaster/useToast.spec.tsx
Labels: PR: New Feature :rocket:

#1058 chore: add "primary hue" tool to storybook
  .storybook/preview.js
Labels: PR: Internal :seedling:

#1059 fix(dropdowns): ensure current theme is passed to underlying FauxInput
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/styled/select/StyledFauxInput.ts
Labels: PR: Bug Fix :bug:

#1060 chore(forms, colorpickers): provide mechanism for removing Range lower track
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/styled/Colorpicker/StyledAlphaRange.ts
  packages/colorpickers/src/styled/Colorpicker/StyledHueRange.ts
  packages/colorpickers/src/styled/common/StyledRange.ts
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/Range.tsx
  packages/forms/src/styled/range/StyledRangeInput.ts
Labels: PR: Internal :seedling:

#1051 chore(deps): upgrade styled-components to v5
  package.json
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/styled/Colorpicker/StyledAlphaRange.ts
  packages/forms/src/elements/MultiThumbRange.spec.tsx
  packages/loaders/src/elements/Dots.spec.tsx
  packages/loaders/src/elements/Spinner.spec.tsx
  packages/pagination/.size-snapshot.json
  packages/pagination/src/styled/Pagination/StyledPage.spec.tsx
  packages/pagination/src/styled/Pagination/StyledPage.ts
  yarn.lock
Labels: PR: Internal :seedling:

#1070 chore: upgrade husky and stylelint
  .husky/.gitignore
  .husky/pre-commit
  .huskyrc
  package.json
  yarn.lock
Labels: PR: Internal :seedling:
