Repository zendeskgarden/react-components, pull requests merged in 2021-09, with the labels that each got.

#1171 feat(colorpickers): add `isOpaque` prop for removing alpha controls
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/elements/Colorpicker/index.spec.tsx
  packages/colorpickers/src/elements/Colorpicker/index.tsx
  packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
  packages/colorpickers/src/styled/Colorpicker/StyledAlphaRange.ts
  packages/colorpickers/src/styled/Colorpicker/StyledColorPicker.ts
  packages/colorpickers/src/styled/Colorpicker/StyledColorWell.ts
  packages/colorpickers/src/styled/Colorpicker/StyledColorWellThumb.ts
  packages/colorpickers/src/styled/Colorpicker/StyledHexField.ts
  packages/colorpickers/src/styled/Colorpicker/StyledHueRange.ts
  packages/colorpickers/src/styled/Colorpicker/StyledPreview.ts
  packages/colorpickers/src/styled/Colorpicker/StyledRGBAField.spec.tsx
  packages/colorpickers/src/styled/Colorpicker/StyledRGBAField.ts
  packages/colorpickers/src/styled/Colorpicker/StyledSliderGroup.ts
  packages/colorpickers/src/styled/Colorpicker/StyledSliders.ts
  packages/colorpickers/src/styled/ColorpickerDialog/StyledTooltipModal.ts
  packages/colorpickers/src/styled/common/StyledRange.ts
  packages/colorpickers/stories/examples/Colorpicker/Controlled.tsx
  packages/colorpickers/stories/examples/Colorpicker/Uncontrolled.tsx
  packages/colorpickers/stories/examples/ColorpickerDialog/Controlled.tsx
  packages/colorpickers/stories/examples/ColorpickerDialog/Uncontrolled.tsx
Labels: PR: New Feature :rocket:

#1172 fix(tabs): render without a `ThemeProvider`
  docs/versioning.md
  packages/tabs/.size-snapshot.json
  packages/tabs/src/elements/Tabs.spec.tsx
  packages/tabs/src/elements/Tabs.tsx
Labels: PR: Bug Fix :bug:

#1173 chore(storybook): add browser env for disabling addon-docs
  .storybook/main.js
Labels: PR: Internal :seedling:

#1192 chore(renovate): update to resolve config warnings
  .github/renovate.json
Labels: PR: Internal :seedling:

#1175 chore(scripts): enhance deploy with added bandwidth checking
  package.json
  tsconfig.json
  utils/scripts/deploy.js
  yarn.lock
Labels: PR: Internal :seedling:

#1202 chore(renovate): refactor config
  .github/renovate.json
Labels: PR: Internal :seedling:

#1206 chore(tooltips): update container-tooltip
  packages/tooltips/package.json
  packages/tooltips/yarn.lock
Labels: PR: Internal :seedling:

#1176 fix(dropdowns): Ensure the input value is preserved and announced by screen readers
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/stories/examples/Autocomplete/Default.tsx
Labels: PR: Bug Fix :bug:

#1214 chore(babel): update config for private-property-in-object plugin
  babel.config.js
Labels: PR: Internal :seedling:

#1213 refactor(components): replace utility useCombinedRefs with mergeRefs
  packages/accordions/.size-snapshot.json
  packages/accordions/package.json
  packages/accordions/src/elements/accordion/components/Panel.tsx
  packages/accordions/src/elements/stepper/components/Content.tsx
  packages/accordions/yarn.lock
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/package.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Combobox/Combobox.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/yarn.lock
  packages/forms/.size-snapshot.json
  packages/forms/package.json
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/elements/Range.tsx
  packages/forms/src/elements/Select.tsx
  packages/forms/src/elements/Textarea.tsx
  packages/forms/src/elements/tiles/components/Label.tsx
  packages/forms/yarn.lock
  packages/tabs/.size-snapshot.json
  packages/tabs/package.json
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/yarn.lock
Labels: PR: Internal :seedling:

#1215 fix(types): export IAvatarProps and ILabelProps
  packages/avatars/src/elements/Avatar.tsx
  packages/avatars/src/index.ts
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Combobox/Combobox.tsx
  packages/dropdowns/src/elements/Fields/Label.tsx
  packages/dropdowns/src/elements/Menu/Items/HeaderItem.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
  packages/dropdowns/src/index.ts
Labels: PR: Bug Fix :bug:

#1218 fix(modals): drawer modal backdrop required two clicks to close
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/DrawerModal/DrawerModal.tsx
Labels: PR: Bug Fix :bug:

#1216 feat(typography): add diff language styling to `CodeBlock`
  packages/typography/.size-snapshot.json
  packages/typography/src/elements/CodeBlock.spec.tsx
  packages/typography/src/elements/CodeBlock.tsx
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.ts
  packages/typography/src/styled/StyledCodeBlockToken.ts
  packages/typography/stories/3-CodeBlock.stories.tsx
Labels: PR: New Feature :rocket:
