Repository zendeskgarden/react-components, pull requests merged in 2021-02, with the labels that each got.

#1000 fix(chrome): enable SkipNav fade out transition animation
  packages/chrome/.size-snapshot.json
  packages/chrome/src/styled/StyledSkipNav.ts
Labels: PR: Bug Fix :bug:

#1009 fix(buttons): disabled IconButton background color
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledButtonGroup.spec.tsx
  packages/buttons/src/styled/StyledIconButton.spec.tsx
  packages/buttons/src/styled/StyledIconButton.ts
Labels: PR: Bug Fix :bug:

#1010 fix(build): allow version tagging process to complete
  utils/scripts/tag.js
Labels: PR: Bug Fix :bug:

#1012 feat(typography): add line highlighting to CodeBlock component
  packages/typography/.size-snapshot.json
  packages/typography/package.json
  packages/typography/src/elements/CodeBlock.spec.tsx
  packages/typography/src/elements/CodeBlock.tsx
  packages/typography/src/styled/StyledCodeBlock.ts
  packages/typography/src/styled/StyledCodeBlockContainer.spec.tsx
  packages/typography/src/styled/StyledCodeBlockContainer.ts
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.ts
  packages/typography/src/styled/index.ts
  packages/typography/stories/3-CodeBlock.stories.tsx
  packages/typography/yarn.lock
Labels: PR: New Feature :rocket:

#1015 fix(typography): simplify DOM structure for list components
  packages/typography/.size-snapshot.json
  packages/typography/src/elements/lists/OrderedList.spec.tsx
  packages/typography/src/elements/lists/OrderedListItem.spec.js
  packages/typography/src/elements/lists/OrderedListItem.tsx
  packages/typography/src/elements/lists/UnorderedList.spec.js
  packages/typography/src/elements/lists/UnorderedListItem.spec.js
  packages/typography/src/elements/lists/UnorderedListItem.tsx
  packages/typography/src/styled/StyledListItem.spec.tsx
  packages/typography/src/styled/StyledListItem.ts
  packages/typography/stories/13-OrderedList.stories.tsx
  packages/typography/stories/14-UnorderedList.stories.tsx
Labels: PR: Bug Fix :bug:

#1013 fix(accordions): Stop stepper's counter incrementing twice in React.StrictMode
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/stepper/components/Step.spec.tsx
  packages/accordions/src/elements/stepper/components/Step.tsx
Labels: PR: Bug Fix :bug:

#1017 fix(buttons): danger IconButton foreground color styling
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledIconButton.ts
Labels: PR: Bug Fix :bug:

#1019 fix(tables): ensure readonly tables don't show focus treatment
  packages/tables/.size-snapshot.json
  packages/tables/src/elements/Row.spec.tsx
  packages/tables/src/elements/Row.tsx
Labels: PR: Bug Fix :bug:

#1020 fix(dropdowns): allow multiselect to receive focus when state is cont…
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
Labels: PR: Bug Fix :bug:

#1014 chore(theming): migrate theming documentation to storybook
  demo/index.html
  packages/theming/.size-snapshot.json
  packages/theming/README.md
  packages/theming/examples/default-theme.md
  packages/theming/examples/palette.md
  packages/theming/examples/theme-provider.md
  packages/theming/package.json
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/src/index.ts
  packages/theming/src/utils/arrowStyles.example.md
  packages/theming/src/utils/menuStyles.example.md
  packages/theming/src/utils/withTheme.example.md
  packages/theming/stories/1-Readme.stories.mdx
  packages/theming/stories/2-ThemeProvider.stories.tsx
  packages/theming/stories/3-Utils.stories.mdx
  packages/theming/stories/examples/ArrowStyles.tsx
  packages/theming/stories/examples/MenuStyles.tsx
  packages/theming/stories/examples/WithTheme.tsx
Labels: PR: Docs :memo:
