Repository zendeskgarden/react-components, pull requests merged in 2021-01, with the labels that each got.

#983 chore: add missing and fix existing @extends clauses
  packages/accordions/src/elements/accordion/components/Label.tsx
  packages/accordions/src/elements/stepper/components/Step.tsx
  packages/avatars/src/elements/Avatar.tsx
  packages/buttons/src/elements/Button.tsx
  packages/chrome/src/elements/header/HeaderItemIcon.tsx
  packages/chrome/src/elements/nav/NavItemIcon.tsx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Menu/Items/AddItem.tsx
  packages/dropdowns/src/elements/Menu/Items/HeaderIcon.tsx
  packages/dropdowns/src/elements/Menu/Items/HeaderItem.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Menu/Items/ItemMeta.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaBody.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaFigure.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaItem.tsx
  packages/dropdowns/src/elements/Menu/Items/NextItem.tsx
  packages/dropdowns/src/elements/Menu/Items/PreviousItem.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
  packages/dropdowns/src/elements/Menu/Separator.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
  packages/forms/src/elements/MultiThumbRange.tsx
  packages/loaders/src/elements/Progress.tsx
  packages/tooltips/src/elements/Tooltip.tsx
  packages/typography/src/elements/Code.tsx
  packages/typography/src/styled/StyledCode.ts
Labels: PR: Internal :seedling:

#984 fix(theming): allow theming of typescript consumers
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/index.ts
  utils/build/styled.d.ts
Labels: PR: Bug Fix :bug:

#985 chore(deps): upgrade all packages to React v17
  .eslintrc.json
  package.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/accordions/yarn.lock
  packages/avatars/package.json
  packages/avatars/stories/examples/Default.tsx
  packages/avatars/yarn.lock
  packages/breadcrumbs/package.json
  packages/breadcrumbs/yarn.lock
  packages/buttons/package.json
  packages/buttons/yarn.lock
  packages/chrome/package.json
  packages/chrome/yarn.lock
  packages/datepickers/package.json
  packages/datepickers/yarn.lock
  packages/dropdowns/package.json
  packages/dropdowns/yarn.lock
  packages/forms/package.json
  packages/forms/yarn.lock
  packages/grid/package.json
  packages/grid/yarn.lock
  packages/loaders/package.json
  packages/loaders/yarn.lock
  packages/modals/package.json
  packages/modals/yarn.lock
  packages/notifications/package.json
  packages/notifications/yarn.lock
  packages/pagination/package.json
  packages/pagination/src/elements/Pagination/Pagination.tsx
  packages/pagination/yarn.lock
  packages/tables/package.json
  packages/tables/yarn.lock
  packages/tabs/package.json
  packages/tabs/src/elements/Tabs.spec.tsx
  packages/tabs/yarn.lock
  packages/tags/package.json
  packages/tags/yarn.lock
  packages/theming/package.json
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/yarn.lock
  packages/tooltips/.size-snapshot.json
  packages/tooltips/package.json
  packages/tooltips/src/elements/Tooltip.tsx
  packages/tooltips/yarn.lock
  packages/typography/package.json
  packages/typography/stories/6-Span.stories.tsx
  packages/typography/yarn.lock
  yarn.lock
Labels: PR: Internal :seedling:

#988 feat(modals): export placement type for tooltip modal
  packages/modals/src/index.ts
Labels: PR: New Feature :rocket:

#989 docs: Add Modal's Header prop change to V8 migration
  docs/migration.md
Labels: PR: Docs :memo:

#987 chore(tags): migrate Tag examples to storybook
  demo/index.html
  packages/avatars/stories/examples/ChromeUsage.tsx
  packages/avatars/stories/examples/MenuUsage.tsx
  packages/tags/README.md
  packages/tags/examples/advanced.md
  packages/tags/examples/basic.md
  packages/tags/package.json
  packages/tags/stories/1-Readme.stories.mdx
  packages/tags/stories/2-Examples.stories.tsx
  packages/tags/stories/examples/CustomHue.tsx
  packages/tags/stories/examples/Default.tsx
  packages/tags/stories/examples/FontWeight.tsx
  packages/tags/stories/examples/Truncation.tsx
Labels: PR: Docs :memo:

#990 fix(dropdowns): allow menu usage in table elements
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/styled/select/StyledInput.ts
  packages/tables/examples/scrollable-table.md
Labels: PR: Bug Fix :bug:

#986 chore(tooltips): migrate tooltip example to storybook
  demo/index.html
  packages/tooltips/.size-snapshot.json
  packages/tooltips/README.md
  packages/tooltips/examples/basic.md
  packages/tooltips/package.json
  packages/tooltips/src/elements/Tooltip.spec.tsx
  packages/tooltips/src/elements/Tooltip.tsx
  packages/tooltips/src/index.ts
  packages/tooltips/src/styled/index.ts
  packages/tooltips/stories/1-Readme.stories.mdx
  packages/tooltips/stories/2-Tooltip.stories.tsx
Labels: PR: Docs :memo:

#992 chore(docs): migrate datepicker docs to storybook
  demo/index.html
  packages/datepickers/.size-snapshot.json
  packages/datepickers/README.md
  packages/datepickers/examples/compact.md
  packages/datepickers/examples/custom-formats.md
  packages/datepickers/examples/default-usage.md
  packages/datepickers/examples/examples.md
  packages/datepickers/examples/localization.md
  packages/datepickers/examples/min-max-dates.md
  packages/datepickers/examples/range.md
  packages/datepickers/package.json
  packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.tsx
  packages/datepickers/src/elements/DatepickerRange/components/End.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Month.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Start.spec.tsx
  packages/datepickers/src/index.ts
  packages/datepickers/stories/1-Readme.stories.mdx
  packages/datepickers/stories/2-Default.stories.tsx
  packages/datepickers/stories/3-CustomFormat.stories.tsx
  packages/datepickers/stories/4-Range.stories.tsx
Labels: PR: Docs :memo:

#997 fix(build): ensure typescript declarations are built with correct path
  utils/build/styled.d.ts
Labels: PR: Bug Fix :bug:

#998 chore: simplify storybook configuration
  .storybook/gardenTheme.js
  .storybook/main.js
  .storybook/manager-head.html
  .storybook/manager.js
  .storybook/preview.js
  README.md
  package.json
  yarn.lock
Labels: PR: Docs :memo:

#993 fix(accordions): correct default color of accordion labels
  packages/accordions/.size-snapshot.json
  packages/accordions/src/styled/accordion/StyledButton.ts
  packages/accordions/src/styled/accordion/StyledRotateIcon.spec.tsx
  packages/accordions/src/styled/accordion/StyledRotateIcon.ts
Labels: PR: Bug Fix :bug:

#994 feat(chrome): add SkipNav component
  packages/chrome/.size-snapshot.json
  packages/chrome/src/elements/SkipNav.spec.tsx
  packages/chrome/src/elements/SkipNav.tsx
  packages/chrome/src/index.ts
  packages/chrome/src/styled/StyledChrome.ts
  packages/chrome/src/styled/StyledSkipNav.ts
  packages/chrome/src/styled/StyledSkipNavIcon.ts
  packages/chrome/src/styled/body/StyledContent.tsx
  packages/chrome/src/styled/body/StyledMain.tsx
  packages/chrome/src/styled/body/StyledSidebar.ts
  packages/chrome/src/styled/header/StyledHeaderItem.ts
  packages/chrome/src/styled/index.ts
  packages/chrome/src/styled/nav/StyledNavItem.ts
  packages/chrome/src/styled/subnav/StyledSubNavItem.tsx
  packages/chrome/stories/2-Chrome.stories.tsx
  packages/chrome/stories/examples/Default.tsx
  packages/chrome/stories/examples/StandaloneHeader.tsx
  packages/chrome/yarn.lock
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
Labels: PR: New Feature :rocket:
