Repository zendeskgarden/react-components, pull requests merged in 2021-05, with the labels that each got.

#1080 chore(template): update yarn new
  packages/.template/README.md
  packages/.template/examples/basic.md
  packages/.template/package.json
  packages/.template/stories/1-Readme.stories.mdx
  packages/.template/stories/2-Example.stories.tsx
  utils/scripts/new.js
Labels: PR: Internal :seedling:

#1082 chore(demo): restore coverage report
  .circleci/config.yml
  .gitignore
  utils/test/jest.config.js
Labels: PR: Internal :seedling:

#1083 fix(dropdowns): handle combobox controlled open
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Combobox/Combobox.tsx
  packages/dropdowns/stories/examples/Autocomplete/Default.tsx
  packages/dropdowns/stories/examples/Combobox/Default.tsx
  packages/dropdowns/stories/examples/Menu/Default.tsx
  packages/dropdowns/stories/examples/Menu/Icon.tsx
  packages/dropdowns/stories/examples/Multiselect/Default.tsx
  packages/dropdowns/stories/examples/Select/Advanced.tsx
  packages/dropdowns/stories/examples/Select/Default.tsx
Labels: PR: Bug Fix :bug:

#1081 feat(buttons,colorpickers,dropdowns,forms): add support for neutral button styling
  packages/buttons/.size-snapshot.json
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/IconButton.tsx
  packages/buttons/src/styled/StyledButton.spec.tsx
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledIcon.ts
  packages/buttons/stories/2-Button.stories.tsx
  packages/buttons/stories/4-ButtonGroup.stories.tsx
  packages/buttons/stories/5-ChevronButton.stories.tsx
  packages/buttons/stories/6-IconButton.stories.tsx
  packages/buttons/stories/7-SplitButton.stories.tsx
  packages/buttons/stories/8-ToggleButton.stories.tsx
  packages/buttons/stories/9-ToggleIcon.stories.tsx
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
  packages/colorpickers/src/styled/ColorpickerDialog/StyledButton.ts
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/styled/input-group/StyledInputGroup.ts
  packages/forms/stories/13-InputGroup.stories.tsx
Labels: PR: New Feature :rocket:

#1088 feat(forms): add compact styling to Radio, Checkbox, and Toggle components
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/Checkbox.tsx
  packages/forms/src/elements/Radio.tsx
  packages/forms/src/elements/Toggle.tsx
  packages/forms/src/index.ts
  packages/forms/src/styled/radio/StyledRadioInput.spec.tsx
  packages/forms/src/styled/radio/StyledRadioInput.ts
  packages/forms/stories/15-Fieldset.stories.tsx
  packages/forms/stories/7-Checkbox.stories.tsx
  packages/forms/stories/8-Radio.stories.tsx
  packages/forms/stories/9-Toggle.stories.tsx
  packages/forms/stories/story-types.ts
Labels: PR: New Feature :rocket:

#1091 fix(forms, buttons): finesse component group z-index transitions
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledButton.ts
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/input-group/StyledInputGroup.ts
  packages/forms/src/styled/text/StyledTextInput.ts
  packages/forms/stories/13-InputGroup.stories.tsx
Labels: PR: Bug Fix :bug:

#1117 fix(chrome): recalculate height of subnavs when children change
  packages/chrome/.size-snapshot.json
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
  packages/chrome/stories/examples/Default.tsx
Labels: PR: Bug Fix :bug:

#1118 chore(typography): use scroll region hook for code block
  packages/typography/.size-snapshot.json
  packages/typography/package.json
  packages/typography/src/elements/CodeBlock.tsx
  packages/typography/yarn.lock
Labels: PR: Internal :seedling:
