Repository zendeskgarden/react-components, pull requests merged in 2021-11, with the labels that each got.

#1232 chore(deps): align root and sub-package @types/react
  package.json
  packages/forms/src/elements/MultiThumbRange.tsx
  packages/modals/yarn.lock
  packages/notifications/yarn.lock
  packages/tables/yarn.lock
  yarn.lock
Labels: PR: Internal :seedling:

#1230 fix(colorpickers): retain previous indices for uncontrolled color swatch
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/elements/ColorSwatchDialog/index.spec.tsx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
Labels: PR: Bug Fix :bug:

#1233 fix(spinner): fix placeholder proportions
  packages/loaders/.size-snapshot.json
  packages/loaders/src/elements/Spinner.tsx
  packages/loaders/src/styled/StyledLoadingPlaceholder.ts
  packages/loaders/src/styled/StyledSVG.ts
Labels: PR: Bug Fix :bug:

#1240 fix: duplicate characters in `version` script
  package.json
Labels: PR: Internal :seedling:

#1241 chore: remove multiple `displayName` assignments per file
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Menu/Items/AddItem.tsx
  packages/dropdowns/src/elements/Menu/Items/NextItem.tsx
  packages/dropdowns/src/elements/Menu/Items/PreviousItem.tsx
Labels: PR: Internal :seedling:

#1243 chore: remove version lifecycle package lockfile updates
  package.json
Labels: PR: Internal :seedling:

#1244 chore(deps): update @types/react
  package.json
  packages/modals/yarn.lock
  packages/notifications/yarn.lock
  packages/tables/yarn.lock
  yarn.lock
Labels: PR: Internal :seedling:

#1242 feat(accordions): add default expanded sections prop
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/accordion/Accordion.spec.tsx
  packages/accordions/src/elements/accordion/Accordion.tsx
  packages/accordions/stories/examples/Uncontrolled.tsx
  packages/accordions/yarn.lock
Labels: PR: New Feature :rocket:

#1248 fix(buttons): do not persist link color on click
  packages/buttons/.size-snapshot.json
  packages/buttons/src/styled/StyledButton.ts
Labels: PR: Bug Fix :bug:

#1250 fix(buttons): Remove repeated word from prop description
  packages/buttons/src/elements/Anchor.tsx
Labels: PR: Bug Fix :bug:

#1231 feat(chrome): create sheet components
  packages/chrome/.size-snapshot.json
  packages/chrome/package.json
  packages/chrome/src/elements/sheet/Sheet.spec.tsx
  packages/chrome/src/elements/sheet/Sheet.tsx
  packages/chrome/src/elements/sheet/components/Body.spec.tsx
  packages/chrome/src/elements/sheet/components/Body.tsx
  packages/chrome/src/elements/sheet/components/Close.spec.tsx
  packages/chrome/src/elements/sheet/components/Close.tsx
  packages/chrome/src/elements/sheet/components/Description.spec.tsx
  packages/chrome/src/elements/sheet/components/Description.tsx
  packages/chrome/src/elements/sheet/components/Footer.spec.tsx
  packages/chrome/src/elements/sheet/components/Footer.tsx
  packages/chrome/src/elements/sheet/components/FooterItem.spec.tsx
  packages/chrome/src/elements/sheet/components/FooterItem.tsx
  packages/chrome/src/elements/sheet/components/Header.spec.tsx
  packages/chrome/src/elements/sheet/components/Header.tsx
  packages/chrome/src/elements/sheet/components/Title.spec.tsx
  packages/chrome/src/elements/sheet/components/Title.tsx
  packages/chrome/src/index.ts
  packages/chrome/src/styled/index.ts
  packages/chrome/src/styled/sheet/StyledSheet.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheet.ts
  packages/chrome/src/styled/sheet/StyledSheetBody.ts
  packages/chrome/src/styled/sheet/StyledSheetClose.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetClose.ts
  packages/chrome/src/styled/sheet/StyledSheetDescription.ts
  packages/chrome/src/styled/sheet/StyledSheetFooter.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetFooter.ts
  packages/chrome/src/styled/sheet/StyledSheetFooterItem.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetFooterItem.ts
  packages/chrome/src/styled/sheet/StyledSheetHeader.ts
  packages/chrome/src/styled/sheet/StyledSheetTitle.ts
  packages/chrome/src/styled/sheet/StyledSheetWrapper.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetWrapper.ts
  packages/chrome/src/utils/useFocusableMount.spec.tsx
  packages/chrome/src/utils/useFocusableMount.ts
  packages/chrome/src/utils/useSheetContext.ts
  packages/chrome/stories/2-Chrome.stories.tsx
  packages/chrome/stories/examples/Default.tsx
  packages/chrome/stories/examples/Sheet.tsx
  packages/chrome/yarn.lock
Labels: PR: New Feature :rocket:

#1251 chore: enhance `yarn new` script
  .storybook/preview.js
  package.json
  packages/.template/.size-snapshot.json
  packages/.template/README.md
  packages/.template/package.json
  packages/.template/src/elements/Example.spec.tsx
  packages/.template/src/elements/Example.tsx
  packages/.template/src/elements/{{capitalize component}}.spec.tsx
  packages/.template/src/elements/{{capitalize component}}.tsx
  packages/.template/src/elements/{{capitalize component}}Text.tsx
  packages/.template/src/index.ts
  packages/.template/src/styled/Styled{{capitalize component}}.spec.tsx
  packages/.template/src/styled/Styled{{capitalize component}}.ts
  packages/.template/src/styled/Styled{{capitalize component}}Text.spec.tsx
  packages/.template/src/styled/Styled{{capitalize component}}Text.ts
  packages/.template/src/styled/index.ts
  packages/.template/stories/#readme.stories.mdx
  packages/.template/stories/1-Readme.stories.mdx
  packages/.template/stories/2-Example.stories.tsx
  packages/.template/stories/{{lowercase component}}.stories.mdx
  packages/.template/yarn.lock
  utils/scripts/new.js
  yarn.lock
Labels: PR: Internal :seedling:
