Repository zendeskgarden/react-components, pull requests merged in 2021-12, with the labels that each got.

#1252 chore(chrome): update size snapshot
  packages/chrome/.size-snapshot.json
Labels: PR: Internal :seedling:

#1246 feat(dropdown): add danger state to menu items
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/styled/items/StyledItem.spec.tsx
  packages/dropdowns/src/styled/items/StyledItem.ts
  packages/dropdowns/stories/examples/Menu/Advanced.tsx
  packages/dropdowns/stories/examples/Menu/Default.tsx
  packages/dropdowns/stories/examples/Menu/Icon.tsx
  packages/dropdowns/stories/examples/Menu/Tree.tsx
  packages/theming/yarn.lock
Labels: PR: New Feature :rocket:

#1253 fix(datepicker): remove calender dom elements when hidden
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
Labels: PR: Bug Fix :bug:
