Repository zendeskgarden/react-components, pull requests merged in 2022-05, with the labels that each got.

#1348 fix(dropdowns): compose keydown for autocomplete
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
Labels: PR: Bug Fix :bug:

#1351 fix(dropdowns): stop overwriting of autocomplete keydown event
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
Labels: PR: Bug Fix :bug:

#1339 feat(splitter): add splitter component
  packages/grid/.size-snapshot.json
  packages/grid/README.md
  packages/grid/demo/pane.stories.mdx
  packages/grid/demo/stories/PaneProviderStory.tsx
  packages/grid/demo/stories/data.ts
  packages/grid/demo/stories/types.ts
  packages/grid/package.json
  packages/grid/src/elements/pane/Pane.spec.tsx
  packages/grid/src/elements/pane/Pane.tsx
  packages/grid/src/elements/pane/PaneProvider.spec.tsx
  packages/grid/src/elements/pane/PaneProvider.tsx
  packages/grid/src/elements/pane/components/Content.spec.tsx
  packages/grid/src/elements/pane/components/Content.tsx
  packages/grid/src/elements/pane/components/Splitter.spec.tsx
  packages/grid/src/elements/pane/components/Splitter.tsx
  packages/grid/src/index.ts
  packages/grid/src/styled/index.ts
  packages/grid/src/styled/pane/StyledPane.ts
  packages/grid/src/styled/pane/StyledPaneContent.ts
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/types/index.ts
  packages/grid/src/utils/usePaneContext.spec.tsx
  packages/grid/src/utils/usePaneContext.ts
  packages/grid/src/utils/useSplitterContext.spec.tsx
  packages/grid/src/utils/useSplitterContext.ts
  packages/grid/yarn.lock
Labels: PR: New Feature :rocket:

#1354 chore(examples): remove
  .github/ISSUE_TEMPLATE.md
  examples/codesandbox/.env
  examples/codesandbox/.gitignore
  examples/codesandbox/.prettierrc
  examples/codesandbox/package.json
  examples/codesandbox/public/favicon.ico
  examples/codesandbox/public/index.html
  examples/codesandbox/public/manifest.json
  examples/codesandbox/src/components/ExampleWrapper.js
  examples/codesandbox/src/examples/Example.js
  examples/codesandbox/src/index.js
  examples/codesandbox/yarn.lock
  examples/gatsby/.gitignore
  examples/gatsby/gatsby-config.js
  examples/gatsby/package.json
  examples/gatsby/src/pages/index.js
  examples/gatsby/static/favicon.ico
  examples/gatsby/yarn.lock
Labels: PR: Internal :seedling:

#1355 fix(multiselect): add useDocument
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
Labels: PR: Bug Fix :bug:

#1356 feat(pane): add providerId
  packages/grid/.size-snapshot.json
  packages/grid/demo/paneProvider.stories.mdx
  packages/grid/demo/stories/PaneProviderStory.tsx
  packages/grid/demo/~patterns/patterns.stories.mdx
  packages/grid/demo/~patterns/stories/CardStory.tsx
  packages/grid/demo/~patterns/stories/data.ts
  packages/grid/demo/~patterns/stories/types.ts
  packages/grid/package.json
  packages/grid/src/elements/pane/PaneProvider.spec.tsx
  packages/grid/src/elements/pane/PaneProvider.tsx
  packages/grid/src/elements/pane/components/Splitter.tsx
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/types/index.ts
  packages/grid/src/utils/usePaneContext.spec.tsx
  packages/grid/src/utils/usePaneProviderContext.ts
  packages/grid/src/utils/useSplitterContext.spec.tsx
  packages/grid/yarn.lock
Labels: PR: New Feature :rocket:

#1357 feat(theming,breadcrumbs,modals): add and apply `useText` utility
  packages/breadcrumbs/.size-snapshot.json
  packages/breadcrumbs/demo/breadcrumb.stories.mdx
  packages/breadcrumbs/src/elements/Breadcrumb.tsx
  packages/modals/.size-snapshot.json
  packages/modals/demo/drawerModal.stories.mdx
  packages/modals/demo/modal.stories.mdx
  packages/modals/demo/stories/DrawerModalStory.tsx
  packages/modals/demo/stories/ModalStory.tsx
  packages/modals/demo/stories/TooltipModalStory.tsx
  packages/modals/demo/tooltipModal.stories.mdx
  packages/modals/src/elements/Close.tsx
  packages/modals/src/elements/DrawerModal/Close.tsx
  packages/modals/src/elements/DrawerModal/DrawerModal.spec.tsx
  packages/modals/src/elements/TooltipModal/Close.tsx
  packages/theming/.size-snapshot.json
  packages/theming/src/index.ts
  packages/theming/src/utils/useText.spec.tsx
  packages/theming/src/utils/useText.ts
Labels: PR: New Feature :rocket:
