Repository zendeskgarden/react-components, pull requests merged in 2022-04, with the labels that each got.

#1297 chore(tooltips): refactor types and element interface
  packages/tooltips/.size-snapshot.json
  packages/tooltips/src/elements/Tooltip.spec.tsx
  packages/tooltips/src/elements/Tooltip.tsx
  packages/tooltips/src/index.ts
  packages/tooltips/src/styled/StyledTooltip.ts
  packages/tooltips/src/styled/index.ts
  packages/tooltips/src/types/index.ts
  packages/tooltips/src/utils/gardenPlacements.spec.ts
  packages/tooltips/src/utils/gardenPlacements.ts
Labels: PR: Internal :seedling:

#1312 chore(demo): add StrictMode decorator
  .lintstagedrc
  .storybook/preview.js
Labels: PR: Internal :seedling:

#1311 refactor(datepickers): use context rather than prop drilling
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/DatepickerRange/components/Calendar.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Month.tsx
Labels: PR: Internal :seedling:

#1320 fix(grid): refactor types and interfaces
  packages/grid/.size-snapshot.json
  packages/grid/demo/stories/GridStory.tsx
  packages/grid/src/elements/Col.tsx
  packages/grid/src/elements/Grid.tsx
  packages/grid/src/elements/Row.tsx
  packages/grid/src/index.ts
  packages/grid/src/styled/StyledCol.spec.tsx
  packages/grid/src/styled/StyledCol.ts
  packages/grid/src/styled/StyledGrid.spec.tsx
  packages/grid/src/styled/StyledGrid.ts
  packages/grid/src/styled/StyledRow.spec.tsx
  packages/grid/src/styled/StyledRow.ts
  packages/grid/src/types/index.ts
  packages/grid/src/utils/types.ts
  packages/grid/src/utils/useGridContext.ts
Labels: PR: Bug Fix :bug:

#1313 chore(scripts): improved local-to-CI linting
  .eslintignore
  .lintstagedrc
  .storybook/preview.js
  package.json
Labels: PR: Internal :seedling:

#1326 fix(theming, modals, colorpickers): refactor types and interfaces
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/demo/stories/data.ts
  packages/colorpickers/src/elements/ColorSwatch/index.tsx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
  packages/colorpickers/src/elements/Colorpicker/ColorWell.tsx
  packages/colorpickers/src/elements/Colorpicker/index.spec.tsx
  packages/colorpickers/src/elements/Colorpicker/index.tsx
  packages/colorpickers/src/elements/Colorpicker/reducer.ts
  packages/colorpickers/src/elements/ColorpickerDialog/index.spec.tsx
  packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
  packages/colorpickers/src/index.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledCell.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledIcon.ts
  packages/colorpickers/src/styled/Colorpicker/StyledAlphaRange.ts
  packages/colorpickers/src/styled/Colorpicker/StyledPreview.ts
  packages/colorpickers/src/styled/ColorpickerDialog/StyledButtonPreview.ts
  packages/colorpickers/src/types/index.ts
  packages/colorpickers/src/utils/saturation.ts
  packages/colorpickers/src/utils/types.ts
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/DrawerModal/DrawerModal.spec.tsx
  packages/modals/src/elements/DrawerModal/DrawerModal.tsx
  packages/modals/src/elements/Header.tsx
  packages/modals/src/elements/Modal.spec.tsx
  packages/modals/src/elements/Modal.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.spec.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
  packages/modals/src/index.ts
  packages/modals/src/styled/StyledTooltipModal.ts
  packages/modals/src/styled/StyledTooltipWrapper.ts
  packages/modals/src/styled/index.ts
  packages/modals/src/types/index.ts
  packages/modals/src/utils/gardenPlacements.tsx
  packages/theming/.size-snapshot.json
  packages/theming/demo/stories/ArrowStylesStory.tsx
  packages/theming/demo/stories/MenuStylesStory.tsx
  packages/theming/demo/utilities.stories.mdx
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/arrowStyles.spec.tsx
  packages/theming/src/utils/arrowStyles.ts
  packages/theming/src/utils/menuStyles.spec.tsx
  packages/theming/src/utils/menuStyles.ts
Labels: PR: Bug Fix :bug:

#1329 fix(forms, dropdowns): refactor types and interfaces
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Combobox/Combobox.tsx
  packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns/src/elements/Fields/Label.tsx
  packages/dropdowns/src/elements/Fields/Message.tsx
  packages/dropdowns/src/elements/Menu/Items/AddItem.tsx
  packages/dropdowns/src/elements/Menu/Items/HeaderItem.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaItem.tsx
  packages/dropdowns/src/elements/Menu/Items/NextItem.tsx
  packages/dropdowns/src/elements/Menu/Items/PreviousItem.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
  packages/dropdowns/src/index.ts
  packages/dropdowns/src/styled/menu/StyledMenu.ts
  packages/dropdowns/src/styled/menu/StyledMenuWrapper.ts
  packages/dropdowns/src/types/index.ts
  packages/dropdowns/src/utils/garden-placements.ts
  packages/dropdowns/src/utils/gardenPlacements.spec.ts
  packages/dropdowns/src/utils/validation.ts
  packages/forms/.size-snapshot.json
  packages/forms/demo/fauxInput.stories.mdx
  packages/forms/demo/multiThumbRange.stories.mdx
  packages/forms/src/elements/Checkbox.tsx
  packages/forms/src/elements/FileUpload.tsx
  packages/forms/src/elements/Input.tsx
  packages/forms/src/elements/MediaInput.spec.tsx
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/elements/MultiThumbRange.tsx
  packages/forms/src/elements/Radio.tsx
  packages/forms/src/elements/Range.tsx
  packages/forms/src/elements/Select.tsx
  packages/forms/src/elements/Textarea.tsx
  packages/forms/src/elements/Toggle.tsx
  packages/forms/src/elements/common/Fieldset.tsx
  packages/forms/src/elements/common/Label.tsx
  packages/forms/src/elements/common/Message.spec.tsx
  packages/forms/src/elements/common/Message.tsx
  packages/forms/src/elements/faux-input/FauxInput.tsx
  packages/forms/src/elements/faux-input/components/EndIcon.tsx
  packages/forms/src/elements/faux-input/components/StartIcon.tsx
  packages/forms/src/elements/file-list/components/File.tsx
  packages/forms/src/elements/file-list/utils.tsx
  packages/forms/src/elements/input-group/InputGroup.tsx
  packages/forms/src/elements/tiles/Tiles.tsx
  packages/forms/src/elements/tiles/components/Tile.tsx
  packages/forms/src/index.ts
  packages/forms/src/styled/common/StyledMessage.ts
  packages/forms/src/styled/common/StyledMessageIcon.spec.tsx
  packages/forms/src/styled/common/StyledMessageIcon.ts
  packages/forms/src/styled/file-list/StyledFile.ts
  packages/forms/src/styled/text/StyledTextInput.ts
  packages/forms/src/types/index.ts
  packages/forms/src/utils/useTilesContext.ts
  packages/forms/src/utils/validation.ts
Labels: PR: Bug Fix :bug:

#1330 fix(tables): refactor types and interfaces
  packages/tables/.size-snapshot.json
  packages/tables/src/elements/Cell.tsx
  packages/tables/src/elements/HeaderCell.tsx
  packages/tables/src/elements/Row.tsx
  packages/tables/src/elements/SortableCell.tsx
  packages/tables/src/elements/Table.tsx
  packages/tables/src/index.ts
  packages/tables/src/styled/StyledCell.ts
  packages/tables/src/styled/StyledOverflowButton.ts
  packages/tables/src/styled/StyledRow.ts
  packages/tables/src/styled/StyledSortableButton.ts
  packages/tables/src/styled/StyledTable.ts
  packages/tables/src/styled/index.ts
  packages/tables/src/styled/style-utils.ts
  packages/tables/src/types/index.ts
  packages/tables/src/utils/useTableContext.ts
Labels: PR: Bug Fix :bug:

#1331 chore(accordions): standardize interfaces
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/accordion/Accordion.tsx
  packages/accordions/src/elements/stepper/Stepper.tsx
  packages/accordions/src/elements/stepper/components/Label.tsx
  packages/accordions/src/elements/timeline/Timeline.tsx
  packages/accordions/src/elements/timeline/components/Item.tsx
  packages/accordions/src/index.ts
  packages/accordions/src/styled/accordion/StyledButton.ts
  packages/accordions/src/styled/accordion/StyledHeader.ts
  packages/accordions/src/styled/accordion/StyledInnerPanel.ts
  packages/accordions/src/styled/accordion/StyledPanel.ts
  packages/accordions/src/styled/accordion/StyledRotateIcon.ts
  packages/accordions/src/styled/stepper/StyledInnerContent.ts
  packages/accordions/src/styled/stepper/StyledStep.ts
  packages/accordions/src/styled/stepper/StyledStepper.ts
  packages/accordions/src/types/index.ts
Labels: PR: Internal :seedling:

#1332 chore(avatars): refactor types and interfaces
  packages/avatars/.size-snapshot.json
  packages/avatars/src/elements/Avatar.tsx
  packages/avatars/src/index.ts
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/src/types/index.ts
Labels: PR: Internal :seedling:

#1333 fix(buttons): refactor types and interfaces
  packages/buttons/.size-snapshot.json
  packages/buttons/src/elements/Anchor.tsx
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/ButtonGroup.tsx
  packages/buttons/src/elements/ChevronButton.tsx
  packages/buttons/src/elements/IconButton.tsx
  packages/buttons/src/elements/ToggleButton.tsx
  packages/buttons/src/elements/ToggleIconButton.tsx
  packages/buttons/src/elements/components/EndIcon.tsx
  packages/buttons/src/elements/components/StartIcon.tsx
  packages/buttons/src/index.ts
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledIconButton.ts
  packages/buttons/src/types/index.ts
Labels: PR: Bug Fix :bug:

#1335 fix(chrome): refactor types and interfaces
  packages/chrome/.size-snapshot.json
  packages/chrome/src/elements/Chrome.tsx
  packages/chrome/src/elements/SkipNav.tsx
  packages/chrome/src/elements/body/Body.tsx
  packages/chrome/src/elements/header/Header.tsx
  packages/chrome/src/elements/header/HeaderItem.spec.tsx
  packages/chrome/src/elements/header/HeaderItem.tsx
  packages/chrome/src/elements/header/HeaderItemText.tsx
  packages/chrome/src/elements/header/HeaderItemWrapper.tsx
  packages/chrome/src/elements/nav/Nav.tsx
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/elements/nav/NavItem.tsx
  packages/chrome/src/elements/nav/NavItemText.tsx
  packages/chrome/src/elements/sheet/Sheet.spec.tsx
  packages/chrome/src/elements/sheet/Sheet.tsx
  packages/chrome/src/elements/sheet/components/Footer.tsx
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
  packages/chrome/src/elements/subnav/SubNavItem.tsx
  packages/chrome/src/elements/subnav/SubNavItemText.tsx
  packages/chrome/src/index.ts
  packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
  packages/chrome/src/styled/index.ts
  packages/chrome/src/styled/nav/StyledLogoNavItem.ts
  packages/chrome/src/styled/sheet/StyledSheet.ts
  packages/chrome/src/styled/sheet/StyledSheetWrapper.ts
  packages/chrome/src/types/index.ts
  packages/chrome/src/utils/types.ts
Labels: PR: Bug Fix :bug:

#1336 fix(datepickers): refactor types and interfaces
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
  packages/datepickers/src/elements/Datepicker/utils/datepicker-reducer.ts
  packages/datepickers/src/elements/Datepicker/utils/garden-placements.spec.ts
  packages/datepickers/src/elements/Datepicker/utils/garden-placements.ts
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.tsx
  packages/datepickers/src/elements/DatepickerRange/components/End.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Start.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/utils/datepicker-range-reducer.ts
  packages/datepickers/src/index.ts
  packages/datepickers/src/styled/StyledMenuWrapper.ts
  packages/datepickers/src/types/index.ts
Labels: PR: Bug Fix :bug:

#1337 fix(notifications): refactor types and interfaces
  packages/notifications/.size-snapshot.json
  packages/notifications/demo/stories/ToastProviderStory.tsx
  packages/notifications/demo/stories/types.ts
  packages/notifications/src/elements/Alert.tsx
  packages/notifications/src/elements/Notification.tsx
  packages/notifications/src/elements/Well.tsx
  packages/notifications/src/elements/content/Title.tsx
  packages/notifications/src/elements/toaster/Toast.ts
  packages/notifications/src/elements/toaster/ToastProvider.tsx
  packages/notifications/src/elements/toaster/ToastSlot.tsx
  packages/notifications/src/elements/toaster/reducer.ts
  packages/notifications/src/elements/toaster/styled.ts
  packages/notifications/src/elements/toaster/useToast.ts
  packages/notifications/src/index.ts
  packages/notifications/src/styled/StyledAlert.spec.tsx
  packages/notifications/src/styled/StyledBase.ts
  packages/notifications/src/styled/StyledNotification.ts
  packages/notifications/src/styled/content/StyledClose.ts
  packages/notifications/src/styled/index.ts
  packages/notifications/src/types/index.ts
  packages/notifications/src/utils/icons.ts
  packages/notifications/src/utils/types.ts
  packages/notifications/src/utils/useNotificationsContext.ts
Labels: PR: Bug Fix :bug:

#1338 fix(loaders, pagination, tabs, tags): refactor types and interfaces
  packages/loaders/.size-snapshot.json
  packages/loaders/src/elements/Dots.tsx
  packages/loaders/src/elements/Inline.tsx
  packages/loaders/src/elements/Progress.tsx
  packages/loaders/src/elements/Skeleton.tsx
  packages/loaders/src/elements/Spinner.tsx
  packages/loaders/src/index.ts
  packages/loaders/src/styled/StyledInline.ts
  packages/loaders/src/styled/StyledLoadingPlaceholder.ts
  packages/loaders/src/styled/StyledProgress.ts
  packages/loaders/src/styled/index.ts
  packages/loaders/src/types/index.ts
  packages/pagination/src/elements/Pagination/Pagination.spec.tsx
  packages/pagination/src/elements/Pagination/Pagination.tsx
  packages/pagination/src/index.ts
  packages/pagination/src/types/index.ts
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/src/elements/TabPanel.tsx
  packages/tabs/src/elements/Tabs.tsx
  packages/tabs/src/index.ts
  packages/tabs/src/types/index.ts
  packages/tags/.size-snapshot.json
  packages/tags/src/elements/Tag.tsx
  packages/tags/src/index.ts
  packages/tags/src/styled/StyledTag.ts
  packages/tags/src/types/index.ts
Labels: PR: Bug Fix :bug:

#1340 chore(typography): refactor types and interfaces
  packages/typography/.size-snapshot.json
  packages/typography/src/elements/Blockquote.tsx
  packages/typography/src/elements/Code.tsx
  packages/typography/src/elements/CodeBlock.tsx
  packages/typography/src/elements/Ellipsis.tsx
  packages/typography/src/elements/LG.tsx
  packages/typography/src/elements/MD.tsx
  packages/typography/src/elements/Paragraph.tsx
  packages/typography/src/elements/SM.tsx
  packages/typography/src/elements/XL.tsx
  packages/typography/src/elements/XXL.tsx
  packages/typography/src/elements/XXXL.tsx
  packages/typography/src/elements/lists/OrderedList.tsx
  packages/typography/src/elements/lists/UnorderedList.tsx
  packages/typography/src/elements/span/Span.tsx
  packages/typography/src/index.ts
  packages/typography/src/styled/StyledBlockquote.ts
  packages/typography/src/styled/StyledCode.spec.tsx
  packages/typography/src/styled/StyledCode.ts
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.ts
  packages/typography/src/styled/StyledEllipsis.ts
  packages/typography/src/styled/StyledFont.spec.tsx
  packages/typography/src/styled/StyledFont.tsx
  packages/typography/src/styled/StyledList.ts
  packages/typography/src/styled/StyledListItem.ts
  packages/typography/src/styled/StyledParagraph.ts
  packages/typography/src/types/index.ts
  packages/typography/src/utils/useOrderedListContext.ts
  packages/typography/src/utils/useUnorderedListContext.ts
Labels: PR: Internal :seedling:

#1342 chore(demo): add design links
  packages/buttons/demo/toggleButton.stories.mdx
  packages/buttons/demo/toggleIconButton.stories.mdx
  packages/chrome/demo/sheet.stories.mdx
  packages/colorpickers/demo/colorSwatch.stories.mdx
  packages/colorpickers/demo/colorSwatchDialog.stories.mdx
  packages/forms/demo/fileList.stories.mdx
  packages/modals/demo/drawerModal.stories.mdx
  packages/typography/demo/blockquote.stories.mdx
  packages/typography/demo/code.stories.mdx
  packages/typography/demo/codeBlock.stories.mdx
Labels: PR: Docs :memo:

#1344 fix(accordions): hide inactive content from screen readers
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/stepper/components/Content.spec.tsx
  packages/accordions/src/elements/stepper/components/Content.tsx
Labels: PR: Bug Fix :bug:

#1341 chore: refactor template interface and add TypeScript documentation
  docs/development.md
  docs/documentation.md
  docs/typescript.md
  packages/.template/src/elements/{{capitalize component}}.tsx
  packages/.template/src/index.ts
  packages/.template/src/types/index.ts
  packages/grid/src/types/index.ts
  utils/scripts/new.js
Labels: PR: Docs :memo:

#1346 feat(accordions): pass icon props to default check icon
  packages/accordions/.size-snapshot.json
  packages/accordions/demo/stepper.stories.mdx
  packages/accordions/demo/stories/StepperStory.tsx
  packages/accordions/src/elements/stepper/components/Label.tsx
  packages/accordions/src/types/index.ts
Labels: PR: New Feature :rocket:

#1347 fix(accordions): add missing `Timeline` text styling
  packages/accordions/.size-snapshot.json
  packages/accordions/src/styled/timeline/StyledItem.ts
Labels: PR: Bug Fix :bug:
