Repository zendeskgarden/react-components, pull requests merged in 2022-09, with the labels that each got.

#1404 fix(avatars): correct status icon sizing with css bedrock
  packages/avatars/.size-snapshot.json
  packages/avatars/src/styled/StyledStatusIndicator.ts
Labels: PR: Bug Fix :bug:

#1403 feat(avatars): add status label
  packages/avatars/.size-snapshot.json
  packages/avatars/demo/stories/AvatarStory.tsx
  packages/avatars/src/elements/Avatar.spec.tsx
  packages/avatars/src/elements/Avatar.tsx
  packages/avatars/src/types/index.ts
Labels: PR: New Feature :rocket:

#1405 fix(dropdowns): remove nested controls violation from select
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Select/Select.tsx
Labels: PR: Bug Fix :bug:

#1409 feat(datepickers): add weekStartsOn prop on calendars
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
  packages/datepickers/src/elements/Datepicker/components/Calendar.tsx
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Month.tsx
  packages/datepickers/src/elements/DatepickerRange/utils/useDatepickerRangeContext.ts
  packages/datepickers/src/types/index.ts
  packages/datepickers/src/utils/calendar-utils.ts
Labels: PR: New Feature :rocket:

#1412 demo(accordions): add Figma designs for Timeline component
  packages/accordions/demo/stories/data.ts
  packages/accordions/demo/timeline.stories.mdx
Labels: PR: Internal :seedling:

#1411 docs: update contributing documentation and PR template
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Docs :memo:

#1410 feat(avatars): add status indicator component
  packages/avatars/.size-snapshot.json
  packages/avatars/README.md
  packages/avatars/demo/statusindicator.stories.mdx
  packages/avatars/demo/stories/StatusIndicatorStory.tsx
  packages/avatars/demo/~patterns/patterns.stories.mdx
  packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
  packages/avatars/src/elements/Avatar.tsx
  packages/avatars/src/elements/StatusIndicator.spec.tsx
  packages/avatars/src/elements/StatusIndicator.tsx
  packages/avatars/src/index.ts
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/src/styled/StyledStandaloneStatus.ts
  packages/avatars/src/styled/StyledStandaloneStatusCaption.ts
  packages/avatars/src/styled/StyledStandaloneStatusIndicator.ts
  packages/avatars/src/styled/StyledStatusIndicator.spec.tsx
  packages/avatars/src/styled/StyledStatusIndicator.ts
  packages/avatars/src/styled/StyledStatusIndicatorBase.ts
  packages/avatars/src/styled/index.ts
  packages/avatars/src/styled/utility.ts
  packages/avatars/src/types/index.ts
Labels: PR: New Feature :rocket:
