Repository zendeskgarden/react-components, pull requests merged in 2022-12, with the labels that each got.

#1465 fix(notifications): adds useText utility to encourage aria-label on Close component
  packages/notifications/.size-snapshot.json
  packages/notifications/demo/alert.stories.mdx
  packages/notifications/demo/notification.stories.mdx
  packages/notifications/demo/stories/AlertStory.tsx
  packages/notifications/demo/stories/NotificationStory.tsx
  packages/notifications/src/elements/content/Close.spec.tsx
  packages/notifications/src/elements/content/Close.tsx
Labels: PR: Bug Fix :bug:

#1468 chore(build): support node.js LTS (v18)
  .storybook/main.js
  package.json
  packages/accordions/.size-snapshot.json
  packages/avatars/.size-snapshot.json
  packages/breadcrumbs/.size-snapshot.json
  packages/buttons/.size-snapshot.json
  packages/chrome/.size-snapshot.json
  packages/colorpickers/.size-snapshot.json
  packages/datepickers/.size-snapshot.json
  packages/dropdowns/.size-snapshot.json
  packages/forms/.size-snapshot.json
  packages/grid/.size-snapshot.json
  packages/loaders/.size-snapshot.json
  packages/modals/.size-snapshot.json
  packages/notifications/.size-snapshot.json
  packages/pagination/.size-snapshot.json
  packages/tables/.size-snapshot.json
  packages/tabs/.size-snapshot.json
  packages/tags/.size-snapshot.json
  packages/theming/.size-snapshot.json
  packages/tooltips/.size-snapshot.json
  packages/typography/.size-snapshot.json
  packages/utilities/.size-snapshot.json
  utils/build/rollup.config.js
  yarn.lock
Labels: PR: Internal :seedling:

#1482 feat(tables): add isSticky prop to Head component
  packages/tables/.size-snapshot.json
  packages/tables/demo/stories/TableStory.tsx
  packages/tables/demo/table.stories.mdx
  packages/tables/src/elements/Head.tsx
  packages/tables/src/index.ts
  packages/tables/src/styled/StyledHead.spec.tsx
  packages/tables/src/styled/StyledHead.ts
  packages/tables/src/types/index.ts
Labels: PR: New Feature :rocket:

#1481 fix(notifications): lets GlobalAlert.Title flow correctly in RTL documents
  packages/notifications/.size-snapshot.json
  packages/notifications/src/elements/global-alert/GlobalAlert.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlert.ts
Labels: PR: Bug Fix :bug:
