Repository zendeskgarden/react-components, pull requests merged in 2022-06, with the labels that each got.

#1358 feat(avatars): extend status prop
  packages/avatars/.size-snapshot.json
  packages/avatars/demo/stories/AvatarStory.tsx
  packages/avatars/package.json
  packages/avatars/src/elements/Avatar.spec.tsx
  packages/avatars/src/elements/Avatar.tsx
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/src/styled/StyledStatusIndicator.spec.tsx
  packages/avatars/src/styled/StyledStatusIndicator.ts
  packages/avatars/src/styled/index.ts
  packages/avatars/src/styled/utility.ts
  packages/avatars/src/types/index.ts
  packages/avatars/yarn.lock
Labels: PR: New Feature :rocket:

#1373 fix(tables): remove redundant rendering of row component
  packages/tables/.size-snapshot.json
  packages/tables/src/elements/Row.tsx
Labels: PR: Bug Fix :bug:

#1371 feat(grid): add pane splitter button
  packages/grid/.size-snapshot.json
  packages/grid/README.md
  packages/grid/demo/paneProvider.stories.mdx
  packages/grid/demo/stories/PaneProviderStory.tsx
  packages/grid/demo/stories/data.ts
  packages/grid/demo/stories/types.ts
  packages/grid/demo/~patterns/stories/CardStory.tsx
  packages/grid/demo/~patterns/stories/types.ts
  packages/grid/package.json
  packages/grid/src/elements/pane/Pane.tsx
  packages/grid/src/elements/pane/PaneProvider.spec.tsx
  packages/grid/src/elements/pane/PaneProvider.tsx
  packages/grid/src/elements/pane/components/Splitter.tsx
  packages/grid/src/elements/pane/components/SplitterButton.spec.tsx
  packages/grid/src/elements/pane/components/SplitterButton.tsx
  packages/grid/src/index.ts
  packages/grid/src/styled/index.ts
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButton.ts
  packages/grid/src/types/index.ts
  packages/grid/src/utils/usePaneSplitterContext.ts
  packages/grid/yarn.lock
  yarn.lock
Labels: PR: New Feature :rocket:

#1372 chore(tests): upgrade to esbuild-jest
  .circleci/config.yml
  .gitignore
  package.json
  packages/dropdowns/src/elements/Combobox/Combobox.spec.tsx
  packages/forms/src/elements/MultiThumbRange.spec.tsx
  packages/loaders/src/elements/Dots.spec.tsx
  packages/loaders/src/elements/Spinner.spec.tsx
  utils/test/jest.config.js
  utils/test/jest.resolver.js
  utils/test/jest.setup.js
  utils/test/svg-mock.tsx
  yarn.lock
Labels: PR: Internal :seedling:

#1375 chore(git): add demo to gitignore
  .gitignore
Labels: PR: Internal :seedling:

#1374 chore(colorpickers): remove popper.js direct dependency
  packages/colorpickers/package.json
Labels: PR: Internal :seedling:
