Repository zendeskgarden/react-components, pull requests merged in 2022-10, with the labels that each got.

#1413 fix(avatars): `StatusIndicator` code structure
  packages/avatars/.size-snapshot.json
  packages/avatars/src/elements/StatusIndicator.tsx
Labels: PR: Bug Fix :bug:

#1415 fix(forms): add min-width to tile
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/tiles/StyledTile.ts
Labels: PR: Bug Fix :bug:

#1444 fix(grid): properly compose Pane.Splitter events
  packages/grid/.size-snapshot.json
  packages/grid/src/elements/pane/components/Splitter.spec.tsx
  packages/grid/src/elements/pane/components/Splitter.tsx
Labels: PR: Bug Fix :bug:

#1443 feat(progress): add useText helper with default value for ARIA label
  packages/loaders/.size-snapshot.json
  packages/loaders/demo/progress.stories.mdx
  packages/loaders/src/elements/Progress.spec.tsx
  packages/loaders/src/elements/Progress.tsx
Labels: PR: New Feature :rocket:

#1419 chore(deps): update testing library user events to v14
  package.json
  packages/accordions/src/elements/accordion/components/Header.spec.tsx
  packages/buttons/src/elements/ButtonGroup.spec.tsx
  packages/chrome/src/elements/sheet/Sheet.spec.tsx
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.spec.tsx
  packages/chrome/src/utils/useFocusableMount.spec.tsx
  packages/colorpickers/src/elements/ColorSwatch/index.spec.tsx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.spec.tsx
  packages/colorpickers/src/elements/Colorpicker/index.spec.tsx
  packages/colorpickers/src/elements/ColorpickerDialog/index.spec.tsx
  packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/DatepickerRange.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/components/End.spec.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Start.spec.tsx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
  packages/dropdowns/src/elements/Combobox/Combobox.spec.tsx
  packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
  packages/dropdowns/src/elements/Fields/Label.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/AddItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.spec.tsx
  packages/dropdowns/src/elements/Menu/Items/MediaItem.spec.tsx
  packages/dropdowns/src/elements/Menu/Menu.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Select/Select.spec.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
  packages/forms/src/elements/Input.spec.tsx
  packages/forms/src/elements/MediaInput.spec.tsx
  packages/forms/src/elements/MultiThumbRange.spec.tsx
  packages/forms/src/elements/Range.spec.tsx
  packages/forms/src/elements/Textarea.spec.tsx
  packages/forms/src/elements/faux-input/FauxInput.spec.tsx
  packages/forms/src/elements/file-list/components/Close.spec.tsx
  packages/forms/src/elements/file-list/components/Delete.spec.tsx
  packages/forms/src/elements/tiles/Tiles.spec.tsx
  packages/grid/src/elements/pane/components/Splitter.spec.tsx
  packages/modals/src/elements/DrawerModal/DrawerModal.spec.tsx
  packages/modals/src/elements/Modal.spec.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.spec.tsx
  packages/notifications/src/elements/toaster/ToastProvider.spec.tsx
  packages/notifications/src/elements/toaster/ToastSlot.spec.tsx
  packages/notifications/src/elements/toaster/useToast.spec.tsx
  packages/pagination/src/elements/Pagination/Pagination.spec.tsx
  packages/tables/src/elements/OverflowButton.spec.tsx
  packages/tables/src/elements/Row.spec.tsx
  packages/tabs/src/elements/Tabs.spec.tsx
  packages/tooltips/src/elements/Tooltip.spec.tsx
  yarn.lock
Labels: PR: Internal :seedling:

#1446 feat(modals): add tag prop to Modal, Drawer, and Tooltip Modal components
  packages/modals/.size-snapshot.json
  packages/modals/demo/drawerModal.stories.mdx
  packages/modals/demo/modal.stories.mdx
  packages/modals/demo/stories/DrawerModalStory.tsx
  packages/modals/demo/stories/ModalStory.tsx
  packages/modals/demo/stories/TooltipModalStory.tsx
  packages/modals/demo/tooltipModal.stories.mdx
  packages/modals/src/elements/DrawerModal/Header.spec.tsx
  packages/modals/src/elements/DrawerModal/Header.tsx
  packages/modals/src/elements/Header.spec.tsx
  packages/modals/src/elements/Header.tsx
  packages/modals/src/elements/TooltipModal/Title.spec.tsx
  packages/modals/src/elements/TooltipModal/Title.tsx
  packages/modals/src/types/index.ts
Labels: PR: New Feature :rocket:

#1447 fix(forms): field renders rtl and ltr
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/common/StyledField.ts
Labels: PR: Bug Fix :bug:
