Repository zendeskgarden/react-components, pull requests merged in 2022-11, with the labels that each got.

#1449 fix(tabs): remove duplicate disabled attribute from StyledTab component
  packages/tabs/.size-snapshot.json
  packages/tabs/src/elements/Tab.spec.tsx
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/src/styled/StyledTab.ts
Labels: PR: Bug Fix :bug:

#1451 fix(loaders): changed Dots and Spinner roles from progressbar to img
  packages/loaders/.size-snapshot.json
  packages/loaders/src/elements/Dots.spec.tsx
  packages/loaders/src/elements/Spinner.spec.tsx
  packages/loaders/src/styled/StyledSVG.ts
Labels: PR: Bug Fix :bug:

#1452 chore: upgrade storybook
  .circleci/config.yml
  package.json
  yarn.lock
Labels: PR: Internal :seedling:

#1453 feat(chrome): add aria-current attribute to NavItem component, when it's current
  packages/chrome/.size-snapshot.json
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/elements/nav/NavItem.tsx
Labels: PR: New Feature :rocket:

#1448 feat(anchor): add default alternative text to external anchor icon
  packages/buttons/.size-snapshot.json
  packages/buttons/demo/anchor.stories.mdx
  packages/buttons/src/elements/Anchor.spec.tsx
  packages/buttons/src/elements/Anchor.tsx
  packages/buttons/src/types/index.ts
Labels: PR: New Feature :rocket:

#1455 feat(grid): add `isFixed` prop along with a11y fixes
  packages/grid/.size-snapshot.json
  packages/grid/demo/stories/data.ts
  packages/grid/package.json
  packages/grid/src/elements/pane/PaneProvider.spec.tsx
  packages/grid/src/elements/pane/components/Splitter.spec.tsx
  packages/grid/src/elements/pane/components/Splitter.tsx
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/types/index.ts
  packages/grid/yarn.lock
Labels: PR: New Feature :rocket:

#1454 fix(chrome): scroll on subnav overflow
  packages/chrome/.size-snapshot.json
  packages/chrome/src/styled/subnav/StyledSubNav.ts
Labels: PR: Bug Fix :bug:

#1456 chore(jest): use swc as transformer
  package.json
  packages/forms/src/elements/MultiThumbRange.spec.tsx
  utils/test/jest.config.js
  yarn.lock
Labels: PR: Internal :seedling:

#1417 fix(accordions, forms): use document for resizing
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/accordion/components/Panel.tsx
  packages/accordions/src/elements/stepper/components/Content.tsx
  packages/forms/.size-snapshot.json
  packages/forms/src/elements/Textarea.tsx
Labels: PR: Bug Fix :bug:

#1450 feat(notifications): global alert component
  packages/notifications/.size-snapshot.json
  packages/notifications/demo/global-alert.stories.mdx
  packages/notifications/demo/stories/GlobalAlertStory.tsx
  packages/notifications/package.json
  packages/notifications/src/elements/global-alert/GlobalAlert.spec.tsx
  packages/notifications/src/elements/global-alert/GlobalAlert.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertButton.spec.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertButton.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertClose.spec.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertClose.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertContent.spec.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertContent.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertTitle.spec.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertTitle.tsx
  packages/notifications/src/elements/global-alert/utility.ts
  packages/notifications/src/index.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlert.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlert.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertButton.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertButton.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertClose.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertClose.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertContent.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertIcon.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertTitle.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertTitle.ts
  packages/notifications/src/styled/global-alert/index.ts
  packages/notifications/src/styled/index.ts
  packages/notifications/src/types/index.ts
  packages/notifications/yarn.lock
Labels: PR: New Feature :rocket:

#1459 chore(demo): prevent strict mode tool in production Storybook
  .storybook/preview.js
Labels: PR: Internal :seedling:

#1463 fix(accordions): relative type interface import
  packages/accordions/src/elements/timeline/components/Item.tsx
Labels: PR: Bug Fix :bug:
