Repository zendeskgarden/react-components, pull requests merged in 2022-01, with the labels that each got.

#1266 docs(grid): visualize with debug
  packages/grid/demo/grid.stories.mdx
Labels: PR: Docs :memo:

#1264 feat(forms): hide semantic Radio, Checkbox, and Toggle inputs more inclusively
  packages/forms/.size-snapshot.json
  packages/forms/src/styled/radio/StyledRadioInput.spec.tsx
  packages/forms/src/styled/radio/StyledRadioInput.ts
  packages/forms/src/styled/toggle/StyledToggleInput.ts
Labels: PR: New Feature :rocket:

#1277 fix(dropdowns): compose onKeyDown handler for multiselect
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
Labels: PR: Bug Fix :bug:
