Repository zendeskgarden/react-components, pull requests merged in 2022-02, with the labels that each got.

#1288 chore(renovate): remove post updates from config
  .github/renovate.json
Labels: PR: Internal :seedling:

#1289 fix(datepickers): add missing DatepickerRange subcomponent display names
  packages/datepickers/.size-snapshot.json
  packages/datepickers/src/elements/DatepickerRange/components/Calendar.tsx
  packages/datepickers/src/elements/DatepickerRange/components/End.tsx
  packages/datepickers/src/elements/DatepickerRange/components/Start.tsx
Labels: PR: Bug Fix :bug:

#1290 fix(datepickers): remove unused exports in order to generate subcomponent "extends" documentation
  packages/pagination/src/elements/CursorPagination/components/Last.tsx
  packages/pagination/src/elements/CursorPagination/components/Next.tsx
  packages/pagination/src/elements/CursorPagination/components/Previous.tsx
Labels: PR: Bug Fix :bug:

#1292 chore(chrome/sheet): remove dangling asterisk from type description
  packages/chrome/src/elements/sheet/Sheet.tsx
Labels: PR: Internal :seedling:

#1293 chore(stylelint): correct config and simplify css lint cmd
  .stylelintrc
  package.json
Labels: PR: Internal :seedling:

#1291 fix(accordions): API prop defaults
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/accordion/Accordion.tsx
  packages/accordions/src/elements/stepper/Stepper.tsx
Labels: PR: Bug Fix :bug:

#1299 feat(dropdowns): Add `appendToElement` property
  packages/dropdowns/.size-snapshot.json
  packages/dropdowns/demo/~patterns/patterns.stories.mdx
  packages/dropdowns/demo/~patterns/stories/MenuStory.tsx
  packages/dropdowns/src/elements/Menu/Menu.spec.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
Labels: PR: New Feature :rocket:

#1301 Update pointer and aria label for color chips
  packages/colorpickers/.size-snapshot.json
  packages/colorpickers/src/elements/ColorSwatch/index.tsx
  packages/colorpickers/src/styled/ColorSwatch/StyledSwatchButton.ts
Labels: PR: Bug Fix :bug:
