Repository zendeskgarden/react-components, pull requests merged in 2023-09, with the labels that each got.

#1618 fix(combobox): stabilize production SSR ID generation
  packages/dropdowns.next/package.json
  packages/dropdowns.next/yarn.lock
Labels: PR: Bug Fix :bug:

#1619 feat(modals): adds appendToNode prop to TooltipModal
  packages/modals/.size-snapshot.json
  packages/modals/src/elements/TooltipModal/TooltipModal.spec.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
  packages/modals/src/types/index.ts
Labels: PR: New Feature :rocket:

#1620 fix(grid): `Pane.Splitter` position styling regression
  packages/grid/.size-snapshot.json
  packages/grid/src/elements/pane/components/Splitter.spec.tsx
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButton.ts
Labels: PR: Bug Fix :bug:

#1621 fix(theming): improve kale-500 color contrast
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.ts
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
Labels: PR: Bug Fix :bug:

#1622 docs(TooltipModal): Match storybook example with website example for consistency
  packages/modals/demo/stories/TooltipModalStory.tsx
Labels: PR: Docs :memo:

#1624 fix(combobox): handle IME via controlled input
  packages/dropdowns.next/package.json
  packages/dropdowns.next/yarn.lock
Labels: PR: Bug Fix :bug:

#1623 feat(dropdowns.next): add refactored menu component
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/demo/menu.stories
  packages/dropdowns.next/demo/menu.stories.mdx
  packages/dropdowns.next/demo/stories/MenuStory
  packages/dropdowns.next/demo/stories/MenuStory.tsx
  packages/dropdowns.next/demo/stories/data.ts
  packages/dropdowns.next/demo/stories/types.ts
  packages/dropdowns.next/demo/~patterns/patterns.stories.mdx
  packages/dropdowns.next/demo/~patterns/stories/ListboxStory.tsx
  packages/dropdowns.next/demo/~patterns/stories/MenuAppendStory.tsx
  packages/dropdowns.next/demo/~patterns/stories/MenuButtonStory.tsx
  packages/dropdowns.next/demo/~patterns/stories/MenuNestedStory.tsx
  packages/dropdowns.next/demo/~patterns/stories/data.ts
  packages/dropdowns.next/package.json
  packages/dropdowns.next/src/context/useItemGroupContext.ts
  packages/dropdowns.next/src/context/useMenuContext.ts
  packages/dropdowns.next/src/elements/menu/Item.tsx
  packages/dropdowns.next/src/elements/menu/ItemGroup.tsx
  packages/dropdowns.next/src/elements/menu/Menu.spec.tsx
  packages/dropdowns.next/src/elements/menu/Menu.tsx
  packages/dropdowns.next/src/elements/menu/MenuList.tsx
  packages/dropdowns.next/src/elements/menu/Separator.tsx
  packages/dropdowns.next/src/elements/menu/utils.ts
  packages/dropdowns.next/src/index.ts
  packages/dropdowns.next/src/types/index.ts
  packages/dropdowns.next/src/views/combobox/StyledFloatingListbox.ts
  packages/dropdowns.next/src/views/index.ts
  packages/dropdowns.next/src/views/menu/StyledButton.ts
  packages/dropdowns.next/src/views/menu/StyledMenu.ts
  packages/dropdowns.next/src/views/menu/StyledSeparator.ts
  packages/dropdowns.next/yarn.lock
Labels: PR: New Feature :rocket:
