Repository zendeskgarden/react-components, pull requests merged in 2023-07, with the labels that each got.

#1564 fix(avatars): explicitly set box sizing for status indicator icon container
  packages/avatars/.size-snapshot.json
  packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
  packages/avatars/src/styled/StyledStandaloneStatusIndicator.ts
Labels: PR: Bug Fix :bug:

#1566 fix(build): ensure nested external dependencies are not bundled
  packages/chrome/.size-snapshot.json
  packages/datepickers/.size-snapshot.json
  packages/modals/.size-snapshot.json
  utils/build/rollup.config.js
Labels: PR: Bug Fix :bug:

#1571 chore(packages): use relative and module paths for imports
  packages/accordions/src/utils/useAccordionContext.ts
  packages/datepickers/src/elements/DatepickerRange/utils/useDatepickerRangeContext.ts
Labels: PR: Internal :seedling:

#1570 fix(accordions): allow dynamic height for stepper content
  packages/accordions/.size-snapshot.json
  packages/accordions/src/elements/stepper/components/Content.tsx
  packages/accordions/src/styled/stepper/StyledContent.ts
  packages/accordions/src/styled/stepper/StyledInnerContent.ts
Labels: PR: Bug Fix :bug:

#1574 fix(combobox): prevent combobox focus retention on multiselectable tag removal
  packages/dropdowns.next/package.json
  packages/dropdowns.next/yarn.lock
Labels: PR: Bug Fix :bug:

#1575 fix(combobox): keyboard interactions and value space rendering
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/package.json
  packages/dropdowns.next/src/views/combobox/StyledValue.ts
  packages/dropdowns.next/yarn.lock
Labels: PR: Bug Fix :bug:

#1576 refactor(buttons): button group react v18 uplift
  packages/buttons/.size-snapshot.json
  packages/buttons/package.json
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/ButtonGroup.spec.tsx
  packages/buttons/src/elements/ButtonGroup.tsx
  packages/buttons/yarn.lock
Labels: PR: Internal :seedling:

#1581 fix(combobox): ensure input focus reset
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/src/views/combobox/StyledInput.ts
Labels: PR: Bug Fix :bug:

#1583 chore(dropdowns): tag and document deprecated components
  packages/dropdowns/demo/autocomplete.stories.mdx
  packages/dropdowns/demo/combobox.stories.mdx
  packages/dropdowns/demo/multiselect.stories.mdx
  packages/dropdowns/demo/select.stories.mdx
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Combobox/Combobox.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
Labels: PR: Docs :memo:

#1584 chore(combobox): prevent `optionTagProps` state bloat
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/src/elements/combobox/Combobox.tsx
Labels: PR: Internal :seedling:

#1585 chore(dropdowns.next): rollback option tag props optimization
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/src/elements/combobox/Combobox.tsx
Labels: PR: Bug Fix :bug:
