Repository zendeskgarden/react-components, pull requests merged in 2023-06, with the labels that each got.

#1558 fix(chrome): consistent focus style for sub nav items
  packages/chrome/.size-snapshot.json
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
Labels: PR: Bug Fix :bug:

#1560 doc(adrs): add theming peer dependency ADR-001
  README.md
  docs/adrs/001-theming-peer-dependency.md
  docs/adrs/README.md
Labels: PR: Docs :memo:

#1559 feat: add refactored `Combobox` component
  README.md
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/README.md
  packages/dropdowns.next/demo/#readme.stories.mdx
  packages/dropdowns.next/demo/combobox.stories.mdx
  packages/dropdowns.next/demo/stories/ComboboxStory.tsx
  packages/dropdowns.next/demo/stories/data.ts
  packages/dropdowns.next/demo/stories/types.ts
  packages/dropdowns.next/demo/~patterns/patterns.stories.mdx
  packages/dropdowns.next/demo/~patterns/stories/ListboxStory.tsx
  packages/dropdowns.next/package.json
  packages/dropdowns.next/src/context/useComboboxContext.ts
  packages/dropdowns.next/src/context/useFieldContext.ts
  packages/dropdowns.next/src/context/useOptionContext.ts
  packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns.next/src/elements/combobox/Combobox.tsx
  packages/dropdowns.next/src/elements/combobox/Field.tsx
  packages/dropdowns.next/src/elements/combobox/Hint.tsx
  packages/dropdowns.next/src/elements/combobox/Label.tsx
  packages/dropdowns.next/src/elements/combobox/Listbox.tsx
  packages/dropdowns.next/src/elements/combobox/Message.tsx
  packages/dropdowns.next/src/elements/combobox/OptGroup.spec.tsx
  packages/dropdowns.next/src/elements/combobox/OptGroup.tsx
  packages/dropdowns.next/src/elements/combobox/Option.spec.tsx
  packages/dropdowns.next/src/elements/combobox/Option.tsx
  packages/dropdowns.next/src/elements/combobox/OptionMeta.tsx
  packages/dropdowns.next/src/elements/combobox/Tag.tsx
  packages/dropdowns.next/src/elements/combobox/TagAvatar.tsx
  packages/dropdowns.next/src/elements/combobox/utils.ts
  packages/dropdowns.next/src/index.ts
  packages/dropdowns.next/src/types/index.ts
  packages/dropdowns.next/src/views/combobox/StyledCombobox.ts
  packages/dropdowns.next/src/views/combobox/StyledContainer.ts
  packages/dropdowns.next/src/views/combobox/StyledField.ts
  packages/dropdowns.next/src/views/combobox/StyledFloating.ts
  packages/dropdowns.next/src/views/combobox/StyledHint.ts
  packages/dropdowns.next/src/views/combobox/StyledInput.ts
  packages/dropdowns.next/src/views/combobox/StyledInputGroup.ts
  packages/dropdowns.next/src/views/combobox/StyledInputIcon.ts
  packages/dropdowns.next/src/views/combobox/StyledLabel.ts
  packages/dropdowns.next/src/views/combobox/StyledListbox.ts
  packages/dropdowns.next/src/views/combobox/StyledMessage.ts
  packages/dropdowns.next/src/views/combobox/StyledOptGroup.ts
  packages/dropdowns.next/src/views/combobox/StyledOption.ts
  packages/dropdowns.next/src/views/combobox/StyledOptionContent.ts
  packages/dropdowns.next/src/views/combobox/StyledOptionIcon.ts
  packages/dropdowns.next/src/views/combobox/StyledOptionMeta.ts
  packages/dropdowns.next/src/views/combobox/StyledOptionTypeIcon.ts
  packages/dropdowns.next/src/views/combobox/StyledSeparator.ts
  packages/dropdowns.next/src/views/combobox/StyledTag.ts
  packages/dropdowns.next/src/views/combobox/StyledTagsButton.ts
  packages/dropdowns.next/src/views/combobox/StyledTrigger.ts
  packages/dropdowns.next/src/views/combobox/StyledValue.ts
  packages/dropdowns.next/src/views/index.ts
  packages/dropdowns.next/tsconfig.build.json
  packages/dropdowns.next/yarn.lock
  tsconfig.json
Labels: PR: New Feature :rocket:

#1561 fix(tables): persist overflow button visibility
  packages/tables/.size-snapshot.json
  packages/tables/src/elements/OverflowButton.spec.tsx
  packages/tables/src/styled/StyledOverflowButton.ts
Labels: PR: Bug Fix :bug:

#1562 fix(combobox): correct peer dependencies and label pixel shift
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/package.json
  packages/dropdowns.next/src/views/combobox/StyledLabel.ts
Labels: PR: Bug Fix :bug:
