Repository zendeskgarden/react-components, pull requests merged in 2023-05, with the labels that each got.

#1542 feat(theming): add focus styling utilities
  packages/theming/.size-snapshot.json
  packages/theming/package.json
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.spec.ts
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/focusStyles.spec.tsx
  packages/theming/src/utils/focusStyles.ts
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
  packages/theming/src/utils/getFocusBoxShadow.spec.ts
  packages/theming/src/utils/getFocusBoxShadow.ts
  packages/theming/src/utils/menuStyles.ts
  packages/theming/yarn.lock
Labels: PR: New Feature :rocket:

#1544 chore(drag-drop): adds figma link to drag and drop storybook
  packages/drag-drop/demo/draggable-list.stories.mdx
  packages/drag-drop/demo/draggable.stories.mdx
  packages/drag-drop/demo/dropzone.stories.mdx
Labels: PR: Docs :memo:

#1545 fix(theming): improve `getColor` memoization resolver performance
  packages/theming/.size-snapshot.json
  packages/theming/src/utils/getColor.ts
Labels: PR: Bug Fix :bug:

#1540 fix(avatars): suppress `statusLabel` useText warning when there is no configured status
  packages/avatars/.size-snapshot.json
  packages/avatars/package.json
  packages/avatars/src/elements/Avatar.tsx
Labels: PR: Bug Fix :bug:

#1546 fix(breadcrumbs): add global theme styles override
  packages/breadcrumbs/.size-snapshot.json
  packages/breadcrumbs/src/styled/StyledBreadcrumb.ts
  packages/breadcrumbs/src/styled/StyledBreadcrumbItem.ts
Labels: PR: Bug Fix :bug:

#1547 fix(forms): prevent `validationLabel` warning on `Message` when `validation` is undefined
  packages/forms/.size-snapshot.json
  packages/forms/package.json
  packages/forms/src/elements/common/Message.tsx
Labels: PR: Bug Fix :bug:

#1549 feat(theming): enhance focus utilities with additional parameter overrides
  packages/theming/.size-snapshot.json
  packages/theming/src/utils/focusStyles.spec.tsx
  packages/theming/src/utils/focusStyles.ts
  packages/theming/src/utils/getFocusBoxShadow.spec.ts
  packages/theming/src/utils/getFocusBoxShadow.ts
Labels: PR: New Feature :rocket:
