Repository zendeskgarden/react-components, pull requests merged in 2023-10, with the labels that each got.

#1625 chore(dropdowns): Add menu to readme, mark legacy dropdowns deprecated
  packages/dropdowns.next/README.md
  packages/dropdowns/demo/autocomplete.stories.mdx
  packages/dropdowns/demo/combobox.stories.mdx
  packages/dropdowns/demo/menu.stories.mdx
  packages/dropdowns/demo/multiselect.stories.mdx
  packages/dropdowns/demo/select.stories.mdx
  packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns/src/elements/Menu/Menu.tsx
  packages/dropdowns/src/elements/Trigger/Trigger.tsx
Labels: PR: Docs :memo:

#1627 chore(deps): bump container-menu to 0.2.2 in react-dropdowns.next
  packages/dropdowns.next/package.json
  packages/dropdowns.next/yarn.lock
Labels: PR: Internal :seedling:

#1628 feat(dropdowns.next): hides separator in label-less, first group child in Combobox/Menu
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/src/elements/combobox/OptGroup.spec.tsx
  packages/dropdowns.next/src/views/combobox/StyledListbox.ts
Labels: PR: New Feature :rocket:

#1630 chore(deps): bump container-menu to v0.3.0 in react-dropdowns.next
  packages/dropdowns.next/package.json
  packages/dropdowns.next/yarn.lock
Labels: PR: New Feature :rocket:

#1631 feat(dropdowns.next): adds rotating chevron to default menu button
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/src/elements/menu/Menu.spec.tsx
  packages/dropdowns.next/src/elements/menu/Menu.tsx
Labels: PR: New Feature :rocket:

#1642 fix(chrome): improve custom `Nav` color contrast
  packages/chrome/.size-snapshot.json
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/styled/nav/StyledNav.ts
  packages/chrome/src/styled/nav/StyledNavItem.ts
Labels: PR: Bug Fix :bug:

#1645 fix(dropdowns.next): allows buttonProps to flow into container-menu props
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/src/elements/menu/Menu.spec.tsx
  packages/dropdowns.next/src/elements/menu/Menu.tsx
Labels: PR: Bug Fix :bug:

#1649 chore: fix `lerna-version` command in tag script
  utils/scripts/tag.mjs
Labels: PR: Internal :seedling:

#1651 fix(accordions): prevent flex shrink on chevron
  packages/accordions/.size-snapshot.json
  packages/accordions/src/styled/accordion/StyledRotateIcon.ts
Labels: PR: Bug Fix :bug:

#1653 fix(combobox): prevent listbox close on scrollbar click
  packages/dropdowns.next/.size-snapshot.json
  packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns.next/src/elements/combobox/Listbox.tsx
Labels: PR: Bug Fix :bug:
