Repository zendeskgarden/react-components, pull requests merged in 2024-04, with the labels that each got.

#1771 feat(theming)!: remove focusVisibleRef prop and polyfill scoping element
  docs/migration.md
  package-lock.json
  packages/accordions/src/elements/accordion/components/Header.tsx
  packages/accordions/src/styled/accordion/StyledHeader.spec.tsx
  packages/accordions/src/styled/accordion/StyledHeader.ts
  packages/buttons/src/styled/StyledButton.ts
  packages/chrome/demo/stories/SheetStory.tsx
  packages/chrome/src/styled/header/StyledHeaderItem.ts
  packages/colorpickers/src/elements/ColorSwatch/index.tsx
  packages/colorpickers/src/styled/common/StyledRange.ts
  packages/dropdowns/src/views/combobox/StyledInputIcon.ts
  packages/forms/src/styled/input-group/StyledInputGroup.ts
  packages/forms/src/styled/radio/StyledRadioInput.ts
  packages/forms/src/styled/range/StyledRangeInput.ts
  packages/forms/src/styled/select/StyledSelect.ts
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButton.ts
  packages/modals/package.json
  packages/modals/src/elements/Drawer/Drawer.tsx
  packages/modals/src/elements/Modal.tsx
  packages/pagination/src/styled/OffsetPagination/StyledPageBase.ts
  packages/tabs/src/styled/StyledTab.ts
  packages/tabs/src/styled/StyledTabs.ts
  packages/theming/package.json
  packages/theming/src/elements/ThemeProvider.spec.tsx
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/src/types/index.ts
  packages/theming/src/utils/focusStyles.spec.tsx
  packages/theming/src/utils/focusStyles.ts
  utils/test/garden-test-utils.tsx
Labels: PR: Breaking Change :boom:

#1773 feat(dropdowns)!: removes object type from Option `value` prop
  package-lock.json
  packages/dropdowns/demo/stories/ComboboxStory.tsx
  packages/dropdowns/package.json
  packages/dropdowns/src/elements/combobox/Option.tsx
  packages/dropdowns/src/elements/combobox/Tag.tsx
  packages/dropdowns/src/elements/combobox/TagGroup.tsx
  packages/dropdowns/src/elements/combobox/utils.ts
  packages/dropdowns/src/types/index.ts
Labels: PR: Breaking Change :boom:

#1777 fix(dropdowns.next): prevent combobox `Option` and menu `Item` overflow
  packages/dropdowns.next/src/views/combobox/StyledOption.ts
Labels: PR: Bug Fix :bug:

#1778 fix(forms): `InputGroup` toggle button stacking
  packages/forms/demo/inputGroup.stories.mdx
  packages/forms/demo/stories/InputGroupStory.tsx
  packages/forms/src/styled/input-group/StyledInputGroup.ts
Labels: PR: Bug Fix :bug:

#1774 feat(chrome)!: removes `Sidebar` component
  docs/migration.md
  packages/chrome/demo/chrome.stories.mdx
  packages/chrome/demo/stories/ChromeStory.tsx
  packages/chrome/demo/stories/data.ts
  packages/chrome/demo/stories/types.ts
  packages/chrome/src/elements/body/Sidebar.spec.tsx
  packages/chrome/src/elements/body/Sidebar.tsx
  packages/chrome/src/index.ts
  packages/chrome/src/styled/body/StyledSidebar.ts
  packages/chrome/src/styled/index.ts
Labels: PR: Breaking Change :boom:

#1776 fix(grid): ensure `Pane.SplitterButton` is rendered as a sibling, rather than child, of `Pane.Splitter`
  packages/grid/src/elements/pane/components/Splitter.tsx
  packages/grid/src/elements/pane/components/SplitterButton.tsx
  packages/grid/src/styled/index.ts
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButton.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButtonContainer.ts
Labels: PR: Bug Fix :bug:

#1779 fix: update theming peer dependencies to ^9.0.0
  package-lock.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/drag-drop/package.json
  packages/dropdowns.legacy/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/typography/package.json
Labels: PR: Bug Fix :bug:

#1781 chore(next): updates from `main`
  .eslintrc.json
  .lintstagedrc
  docs/changelogs/v8.md
  package-lock.json
  package.json
  packages/dropdowns/src/views/combobox/StyledOption.ts
  packages/forms/demo/inputGroup.stories.mdx
  packages/forms/demo/stories/InputGroupStory.tsx
  packages/forms/src/styled/input-group/StyledInputGroup.ts
  packages/grid/src/elements/pane/components/Splitter.tsx
  packages/grid/src/elements/pane/components/SplitterButton.tsx
  packages/grid/src/styled/index.ts
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButton.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButtonContainer.ts
Labels: PR: Internal :seedling:

#1782 feat(theming): fill out color variables
  packages/theming/src/elements/ThemeProvider.spec.tsx
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/utils/getColor.spec.ts
Labels: PR: New Feature :rocket:

#1783 feat: preserve module structure to improve tree-shaking
  babel.config.js
  package-lock.json
  package.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/drag-drop/package.json
  packages/dropdowns.next/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/theming/package.json
  packages/tooltips/package.json
  packages/typography/package.json
  packages/utilities/package.json
  utils/build/rollup.config.js
Labels: PR: New Feature :rocket:

#1785 fix(theming)!: update utilities for refactored `getColor`
  docs/migration.md
  packages/buttons/src/styled/StyledButton.ts
  packages/chrome/src/styled/subnav/StyledSubNavItem.tsx
  packages/dropdowns/src/views/combobox/StyledTrigger.ts
  packages/forms/src/elements/input-group/InputGroup.spec.tsx
  packages/forms/src/styled/file-list/StyledFile.ts
  packages/forms/src/styled/file-upload/StyledFileUpload.ts
  packages/forms/src/styled/text/StyledTextFauxInput.ts
  packages/forms/src/styled/text/StyledTextInput.ts
  packages/forms/src/styled/tiles/StyledTile.ts
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/modals/src/styled/StyledClose.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlert.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertButton.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertClose.ts
  packages/theming/demo/stories/ArrowStylesStory.tsx
  packages/theming/demo/utilities.stories.mdx
  packages/theming/src/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/focusStyles.spec.tsx
  packages/theming/src/utils/focusStyles.ts
  packages/theming/src/utils/getColor.ts
  packages/theming/src/utils/getFocusBoxShadow.spec.ts
  packages/theming/src/utils/getFocusBoxShadow.ts
  packages/theming/src/utils/menuStyles.ts
Labels: PR: Breaking Change :boom:

#1784 feat(chrome)!: improves markup structure for `Nav` items
  docs/migration.md
  packages/avatars/demo/~patterns/stories/ChromeStory.tsx
  packages/chrome/README.md
  packages/chrome/demo/stories/ChromeStory.tsx
  packages/chrome/src/elements/nav/Nav.tsx
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/elements/nav/NavItem.tsx
  packages/chrome/src/elements/nav/NavList.tsx
  packages/chrome/src/styled/index.ts
  packages/chrome/src/styled/nav/StyledBaseNavItem.ts
  packages/chrome/src/styled/nav/StyledBrandmarkNavItem.ts
  packages/chrome/src/styled/nav/StyledLogoNavItem.ts
  packages/chrome/src/styled/nav/StyledNavButton.ts
  packages/chrome/src/styled/nav/StyledNavItemText.ts
  packages/chrome/src/styled/nav/StyledNavList.ts
  packages/chrome/src/styled/nav/StyledNavListItem.ts
  packages/chrome/src/utils/useNavListContext.ts
Labels: PR: Breaking Change :boom:

#1786 fix: update theming peer dependency to ^8.75.0
  package-lock.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/drag-drop/package.json
  packages/dropdowns.next/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Bug Fix :bug:

#1787 feat(chrome)!: removes Subnav component
  docs/migration.md
  package-lock.json
  packages/chrome/README.md
  packages/chrome/demo/chrome.stories.mdx
  packages/chrome/demo/stories/ChromeStory.tsx
  packages/chrome/demo/stories/SubNavCollapsibleItem.tsx
  packages/chrome/demo/stories/data.ts
  packages/chrome/demo/stories/types.ts
  packages/chrome/demo/subNavCollapsibleItem.stories.mdx
  packages/chrome/package.json
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.spec.tsx
  packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
  packages/chrome/src/elements/subnav/SubNav.spec.tsx
  packages/chrome/src/elements/subnav/SubNav.tsx
  packages/chrome/src/elements/subnav/SubNavItem.spec.tsx
  packages/chrome/src/elements/subnav/SubNavItem.tsx
  packages/chrome/src/elements/subnav/SubNavItemText.spec.tsx
  packages/chrome/src/elements/subnav/SubNavItemText.tsx
  packages/chrome/src/index.ts
  packages/chrome/src/styled/index.ts
  packages/chrome/src/styled/subnav/StyledSubNav.ts
  packages/chrome/src/styled/subnav/StyledSubNavItem.tsx
  packages/chrome/src/styled/subnav/StyledSubNavItemHeader.ts
  packages/chrome/src/styled/subnav/StyledSubNavItemIcon.tsx
  packages/chrome/src/styled/subnav/StyledSubNavItemText.ts
  packages/chrome/src/styled/subnav/StyledSubNavPanel.ts
  packages/chrome/src/types/index.ts
Labels: PR: Breaking Change :boom:

#1788 chore: update with `main`
  babel.config.js
  docs/changelogs/v8.md
  package-lock.json
  package.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/drag-drop/package.json
  packages/dropdowns.legacy/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/theming/package.json
  packages/tooltips/package.json
  packages/typography/package.json
  utils/build/rollup.config.js
Labels: PR: Internal :seedling:

#1789 fix(deps): use -next versions for react-theming peer dep
  package-lock.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/drag-drop/package.json
  packages/dropdowns.legacy/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Bug Fix :bug:

#1791 feat: adds styled icon base component
  packages/accordions/src/elements/accordion/components/Header.tsx
  packages/accordions/src/elements/timeline/components/Content.tsx
  packages/accordions/src/styled/accordion/StyledRotateIcon.spec.tsx
  packages/accordions/src/styled/accordion/StyledRotateIcon.ts
  packages/accordions/src/styled/timeline/StyledItemIcon.ts
  packages/theming/src/index.ts
  packages/theming/src/utils/StyledBaseIcon.ts
Labels: PR: New Feature :rocket:

#1790 fix(Notifications): improve screen-reader support
  packages/notifications/src/elements/Notification.spec.tsx
  packages/notifications/src/elements/Notification.tsx
Labels: PR: Bug Fix :bug:

#1792 feat: adds StyledBaseIcon to various icon components
  package-lock.json
  packages/buttons/src/elements/IconButton.tsx
  packages/buttons/src/elements/components/EndIcon.tsx
  packages/buttons/src/elements/components/StartIcon.tsx
  packages/buttons/src/styled/StyledIcon.spec.tsx
  packages/buttons/src/styled/StyledIcon.ts
  packages/dropdowns/src/elements/combobox/Combobox.tsx
  packages/dropdowns/src/elements/combobox/OptGroup.tsx
  packages/dropdowns/src/elements/combobox/Option.tsx
  packages/dropdowns/src/elements/menu/Item.tsx
  packages/dropdowns/src/elements/menu/ItemGroup.tsx
  packages/dropdowns/src/views/combobox/StyledInputIcon.ts
  packages/dropdowns/src/views/combobox/StyledOptionIcon.ts
  packages/dropdowns/src/views/combobox/StyledOptionTypeIcon.ts
  packages/forms/src/elements/faux-input/components/EndIcon.tsx
  packages/forms/src/elements/faux-input/components/StartIcon.tsx
  packages/forms/src/elements/file-list/components/File.tsx
  packages/forms/src/styled/file-list/StyledFileIcon.spec.tsx
  packages/forms/src/styled/file-list/StyledFileIcon.ts
  packages/forms/src/styled/text/StyledTextMediaFigure.spec.tsx
  packages/forms/src/styled/text/StyledTextMediaFigure.ts
  packages/notifications/src/elements/Alert.tsx
  packages/notifications/src/elements/Notification.tsx
  packages/notifications/src/elements/global-alert/GlobalAlert.tsx
  packages/notifications/src/styled/StyledIcon.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertIcon.ts
  packages/pagination/src/elements/CursorPagination/components/First.tsx
  packages/pagination/src/elements/CursorPagination/components/Last.tsx
  packages/pagination/src/elements/CursorPagination/components/Next.tsx
  packages/pagination/src/elements/CursorPagination/components/Previous.tsx
  packages/pagination/src/styled/CursorPagination/StyledIcon.spec.tsx
  packages/pagination/src/styled/CursorPagination/StyledIcon.ts
  packages/tags/src/styled/StyledAvatar.ts
  packages/typography/src/elements/span/StartIcon.tsx
  packages/typography/src/styled/StyledIcon.spec.tsx
  packages/typography/src/styled/StyledIcon.ts
Labels: PR: New Feature :rocket:

#1793 feat(theming): add new `getCheckeredBackground` utility
  packages/colorpickers/src/styled/ColorPicker/StyledAlphaRange.ts
  packages/colorpickers/src/styled/ColorPicker/StyledPreview.ts
  packages/colorpickers/src/styled/ColorPickerDialog/StyledButtonPreview.ts
  packages/colorpickers/src/styled/common/checkeredBackground.ts
  packages/theming/demo/stories/GetColorStory.tsx
  packages/theming/src/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/getCheckeredBackground.spec.ts
  packages/theming/src/utils/getCheckeredBackground.ts
  packages/theming/src/utils/getColor.ts
Labels: PR: New Feature :rocket:

#1796 chore(next): updates from `main`
  docs/changelogs/v8.md
  packages/notifications/src/elements/Notification.spec.tsx
  packages/notifications/src/elements/Notification.tsx
Labels: PR: Internal :seedling:

#1795 fix(theming): update palette color values
  packages/theming/demo/stories/PaletteStory.tsx
  packages/theming/demo/utilities.stories.mdx
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.ts
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
Labels: PR: Bug Fix :bug:

#1794 feat!: removes stale product colors from palette
  docs/migration.md
  packages/chrome/README.md
  packages/chrome/demo/stories/ChromeStory.tsx
  packages/chrome/src/elements/header/HeaderItem.spec.tsx
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
  packages/chrome/src/styled/nav/StyledLogoNavItem.ts
  packages/chrome/src/types/index.ts
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.ts
Labels: PR: Breaking Change :boom:

#1797 feat(theming): add system `opacity` values to the theme
  .github/PULL_REQUEST_TEMPLATE.md
  packages/theming/demo/stories/GetColorStory.tsx
  packages/theming/demo/utilities.stories.mdx
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
Labels: PR: New Feature :rocket:
