Repository zendeskgarden/react-components, pull requests merged in 2024-03, with the labels that each got.

#1728 fix: allows menu to position correctly in RTL
  package-lock.json
  packages/dropdowns.next/src/elements/menu/MenuList.tsx
Labels: PR: Bug Fix :bug:

#1729 feat(dropdowns)!: replaces label prop with legend in OptGroup
  docs/migration.md
  docs/migrations/v8.md
  package-lock.json
  packages/dropdowns/demo/stories/data.ts
  packages/dropdowns/src/elements/combobox/OptGroup.spec.tsx
  packages/dropdowns/src/elements/combobox/OptGroup.tsx
  packages/dropdowns/src/elements/combobox/utils.ts
  packages/dropdowns/src/types/index.ts
Labels: PR: Breaking Change :boom:

#1733 feat(tables): adds sub-component mapping
  docs/migration.md
  packages/tables/README.md
  packages/tables/demo/stories/TableStory.tsx
  packages/tables/demo/table.stories.mdx
  packages/tables/src/elements/Table.tsx
  packages/tables/src/index.ts
Labels: PR: New Feature :rocket:

#1735 fix(dropdowns): controlled `Combobox` input value regression
  package-lock.json
  packages/dropdowns.next/package.json
Labels: PR: Bug Fix :bug:

#1736 feat(chrome): adds sub-component mapping
  docs/migration.md
  packages/chrome/README.md
  packages/chrome/demo/chrome.stories.mdx
  packages/chrome/demo/stories/ChromeStory.tsx
  packages/chrome/demo/stories/SubNavCollapsibleItem.tsx
  packages/chrome/demo/subNavCollapsibleItem.stories.mdx
  packages/chrome/src/elements/footer/Footer.tsx
  packages/chrome/src/elements/header/Header.tsx
  packages/chrome/src/elements/nav/Nav.tsx
  packages/chrome/src/elements/subnav/SubNav.tsx
  packages/chrome/src/index.ts
Labels: PR: New Feature :rocket:

#1734 feat: adds sub-component mapping to tabs and tooltips
  docs/migration.md
  packages/tabs/README.md
  packages/tabs/demo/stories/TabsStory.tsx
  packages/tabs/demo/tabs.stories.mdx
  packages/tabs/src/elements/Tabs.spec.tsx
  packages/tabs/src/elements/Tabs.tsx
  packages/tabs/src/index.ts
  packages/tooltips/demo/stories/TooltipStory.tsx
  packages/tooltips/demo/tooltip.stories.mdx
  packages/tooltips/src/elements/Tooltip.spec.tsx
  packages/tooltips/src/elements/Tooltip.tsx
  packages/tooltips/src/index.ts
Labels: PR: New Feature :rocket:

#1737 fix(chrome): use correct names in chrome subcomponents
  packages/chrome/demo/chrome.stories.mdx
Labels: PR: Bug Fix :bug:

#1738 chore(next): updates from `main`
  docs/changelogs/v8.md
  package-lock.json
  packages/dropdowns/package.json
Labels: PR: Internal :seedling:

#1740 fix: bumps styled-components peer dep to 5.3.1
  docs/migration.md
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/drag-drop/package.json
  packages/dropdowns.legacy/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/theming/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Bug Fix :bug:

#1741 feat(grid): adds subcomponent mapping to Grid
  docs/migration.md
  packages/grid/README.md
  packages/grid/demo/grid.stories.mdx
  packages/grid/demo/stories/GridStory.tsx
  packages/grid/src/elements/Col.tsx
  packages/grid/src/elements/Grid.tsx
  packages/grid/src/elements/Row.tsx
Labels: PR: New Feature :rocket:

#1742 feat(forms): adds subcomponent mapping to Field
  docs/migration.md
  package-lock.json
  packages/chrome/demo/stories/SheetStory.tsx
  packages/colorpickers/src/elements/ColorPicker/index.tsx
  packages/datepickers/README.md
  packages/datepickers/demo/stories/DatePickerRangeStory.tsx
  packages/datepickers/demo/stories/DatePickerStory.tsx
  packages/forms/README.md
  packages/forms/demo/checkbox.stories.mdx
  packages/forms/demo/fauxInput.stories.mdx
  packages/forms/demo/fieldset.stories.mdx
  packages/forms/demo/fileUpload.stories.mdx
  packages/forms/demo/input.stories.mdx
  packages/forms/demo/inputGroup.stories.mdx
  packages/forms/demo/mediaInput.stories.mdx
  packages/forms/demo/radio.stories.mdx
  packages/forms/demo/range.stories.mdx
  packages/forms/demo/select.stories.mdx
  packages/forms/demo/stories/CheckboxStory.tsx
  packages/forms/demo/stories/FauxInputStory.tsx
  packages/forms/demo/stories/FieldStory.tsx
  packages/forms/demo/stories/FieldsetStory.tsx
  packages/forms/demo/stories/FileListStory.tsx
  packages/forms/demo/stories/FileStory.tsx
  packages/forms/demo/stories/FileUploadStory.tsx
  packages/forms/demo/stories/InputGroupStory.tsx
  packages/forms/demo/stories/InputStory.tsx
  packages/forms/demo/stories/MediaInputStory.tsx
  packages/forms/demo/stories/RadioStory.tsx
  packages/forms/demo/stories/RangeStory.tsx
  packages/forms/demo/stories/SelectStory.tsx
  packages/forms/demo/stories/TextareaStory.tsx
  packages/forms/demo/stories/TilesStory.tsx
  packages/forms/demo/stories/ToggleStory.tsx
  packages/forms/demo/stories/common.tsx
  packages/forms/demo/textarea.stories.mdx
  packages/forms/demo/toggle.stories.mdx
  packages/forms/src/elements/common/Field.tsx
  packages/forms/src/elements/common/Hint.tsx
  packages/forms/src/elements/common/Label.tsx
  packages/forms/src/elements/common/Message.tsx
  packages/tables/demo/stories/TableStory.tsx
Labels: PR: New Feature :rocket:

#1744 chore: updates Grid.Row and Grid.Col references in stories
  packages/avatars/demo/~patterns/stories/MenuStory.tsx
  packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
  packages/chrome/demo/stories/SheetStory.tsx
  packages/chrome/demo/stories/SubNavCollapsibleItem.tsx
  packages/colorpickers/demo/stories/ColorPickerDialogStory.tsx
  packages/colorpickers/demo/stories/ColorSwatchDialogStory.tsx
  packages/datepickers/demo/stories/DatePickerRangeStory.tsx
  packages/datepickers/demo/stories/DatePickerStory.tsx
  packages/dropdowns.legacy/demo/stories/DropdownStory.tsx
  packages/dropdowns.legacy/demo/~patterns/stories/MenuStory.tsx
  packages/dropdowns/demo/stories/ComboboxStory.tsx
  packages/dropdowns/demo/stories/MenuStory.tsx
  packages/dropdowns/demo/~patterns/stories/MenuButtonStory.tsx
  packages/dropdowns/demo/~patterns/stories/MenuNestedStory.tsx
  packages/forms/demo/stories/TilesStory.tsx
  packages/modals/demo/stories/TooltipModalStory.tsx
  packages/notifications/demo/stories/ToastStory.tsx
  packages/theming/demo/stories/MenuStylesStory.tsx
  packages/tooltips/demo/stories/TooltipStory.tsx
  packages/typography/demo/stories/data.ts
Labels: PR: Internal :seedling:

#1745 feat(dropdowns): adds subcomponent mapping to Field
  docs/migration.md
  packages/dropdowns/README.md
  packages/dropdowns/demo/combobox.stories.mdx
  packages/dropdowns/demo/stories/ComboboxStory.tsx
  packages/dropdowns/demo/~patterns/stories/ListboxStory.tsx
  packages/dropdowns/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns/src/elements/combobox/Field.tsx
  packages/dropdowns/src/elements/combobox/Hint.tsx
  packages/dropdowns/src/elements/combobox/Label.tsx
  packages/dropdowns/src/elements/combobox/Message.tsx
  packages/dropdowns/src/views/combobox/StyledHint.ts
  packages/dropdowns/src/views/combobox/StyledLabel.ts
  packages/dropdowns/src/views/combobox/StyledMessage.ts
  packages/typography/demo/stories/data.ts
Labels: PR: New Feature :rocket:

#1747 feat(theming)!: remove `focusVisibleRef` prop and polyfill scoping element
  docs/migration.md
  packages/chrome/demo/stories/SheetStory.tsx
  packages/theming/src/elements/ThemeProvider.spec.tsx
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/src/types/index.ts
  utils/test/garden-test-utils.tsx
Labels: PR: Breaking Change :boom:

#1748 feat(notifications): adds subcomponent mapping
  docs/migration.md
  packages/notifications/README.md
  packages/notifications/demo/alert.stories.mdx
  packages/notifications/demo/notification.stories.mdx
  packages/notifications/demo/stories/AlertStory.tsx
  packages/notifications/demo/stories/NotificationStory.tsx
  packages/notifications/demo/stories/WellStory.tsx
  packages/notifications/demo/well.stories.mdx
  packages/notifications/src/elements/Alert.tsx
  packages/notifications/src/elements/Notification.tsx
  packages/notifications/src/elements/Well.tsx
  packages/notifications/src/elements/content/Close.tsx
  packages/notifications/src/elements/content/Paragraph.tsx
  packages/notifications/src/elements/content/Title.tsx
Labels: PR: New Feature :rocket:

#1749 feat(theming)!: update `PALETTE` with redesigned 100-1200 shades
  .storybook/preview.js
  packages/accordions/src/styled/accordion/StyledButton.spec.tsx
  packages/accordions/src/styled/accordion/StyledHeader.spec.tsx
  packages/chrome/src/elements/subnav/SubNav.spec.tsx
  packages/chrome/src/elements/subnav/SubNavItem.spec.tsx
  packages/drag-drop/src/styled/draggable/StyledDraggable.spec.tsx
  packages/forms/src/elements/input-group/InputGroup.spec.tsx
  packages/forms/src/styled/file-list/StyledFileClose.spec.tsx
  packages/forms/src/styled/text/StyledTextInput.spec.tsx
  packages/forms/src/styled/text/StyledTextMediaInput.spec.tsx
  packages/loaders/src/elements/Skeleton.spec.tsx
  packages/tags/src/styled/StyledTag.ts
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.ts
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/utils/_getColor.spec.ts
Labels: PR: Breaking Change :boom:

#1750 feat(modals): adds subcomponent mapping to Modal
  docs/migration.md
  packages/modals/README.md
  packages/modals/demo/modal.stories.mdx
  packages/modals/demo/stories/ModalStory.tsx
  packages/modals/src/elements/Body.tsx
  packages/modals/src/elements/Close.tsx
  packages/modals/src/elements/Footer.tsx
  packages/modals/src/elements/FooterItem.tsx
  packages/modals/src/elements/Header.tsx
  packages/modals/src/elements/Modal.spec.tsx
  packages/modals/src/elements/Modal.tsx
  packages/modals/src/index.ts
Labels: PR: New Feature :rocket:

#1752 feat: updates icon component and prop types for cross-package consistency
  docs/migration.md
  package-lock.json
  packages/accordions/demo/stories/StepperStory.tsx
  packages/accordions/demo/stories/TimelineStory.tsx
  packages/accordions/src/types/index.ts
  packages/breadcrumbs/src/styled/StyledChevronIcon.tsx
  packages/chrome/src/elements/header/HeaderItemIcon.tsx
  packages/chrome/src/elements/nav/NavItemIcon.tsx
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/types/index.ts
  packages/typography/src/elements/span/Icon.tsx
  packages/typography/src/elements/span/StartIcon.tsx
Labels: PR: Breaking Change :boom:

#1760 chore(deps): update non-major shared dependencies from main
  package-lock.json
  package.json
Labels: PR: Internal :seedling:

#1759 feat: use strict mode as storybook default
  .storybook/main.js
  .storybook/preview.js
Labels: PR: New Feature :rocket:

#1755 feat(theming)!: add `variables` to theme `colors`
  docs/migration.md
  packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchLabel.ts
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/getColorV8.ts
Labels: PR: Breaking Change :boom:

#1762 feat(theming)!: update `PALETTE` with redesigned 100-1200 shades
  .storybook/preview.js
  docs/migration.md
  packages/accordions/src/styled/accordion/StyledButton.spec.tsx
  packages/accordions/src/styled/stepper/StyledIcon.spec.tsx
  packages/accordions/src/styled/stepper/StyledLabel.spec.tsx
  packages/buttons/src/styled/StyledButton.spec.tsx
  packages/buttons/src/styled/StyledIconButton.spec.tsx
  packages/buttons/src/styled/StyledSplitButton.spec.tsx
  packages/dropdowns.legacy/src/elements/Combobox/Combobox.spec.tsx
  packages/dropdowns.legacy/src/styled/items/StyledItem.spec.tsx
  packages/dropdowns/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns/src/elements/combobox/Option.spec.tsx
  packages/dropdowns/src/elements/menu/Menu.spec.tsx
  packages/forms/src/styled/file-list/StyledFile.spec.tsx
  packages/forms/src/styled/file-list/StyledFileClose.spec.tsx
  packages/forms/src/styled/file-list/StyledFileDelete.spec.tsx
  packages/forms/src/styled/text/StyledTextInput.spec.tsx
  packages/forms/src/styled/text/StyledTextMediaFigure.spec.tsx
  packages/forms/src/styled/text/StyledTextMediaInput.spec.tsx
  packages/loaders/src/elements/Progress.spec.tsx
  packages/modals/src/styled/StyledDrawerHeader.spec.tsx
  packages/modals/src/styled/StyledFooter.spec.tsx
  packages/modals/src/styled/StyledHeader.spec.tsx
  packages/notifications/src/elements/content/Title.spec.tsx
  packages/notifications/src/styled/StyledBase.spec.tsx
  packages/notifications/src/styled/StyledWell.spec.tsx
  packages/notifications/src/styled/content/StyledClose.spec.tsx
  packages/tables/src/elements/OverflowButton.spec.tsx
  packages/tags/src/elements/Tag.spec.tsx
  packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/palette/index.ts
  packages/theming/src/elements/palette/v8.ts
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/index.ts
  packages/theming/src/utils/focusStyles.spec.tsx
  packages/theming/src/utils/getColorV8.spec.ts
  packages/theming/src/utils/getColorV8.ts
  packages/theming/src/utils/getFocusBoxShadow.spec.ts
  packages/typography/src/elements/Code.spec.tsx
  packages/typography/src/elements/CodeBlock.spec.tsx
  packages/typography/src/elements/span/Span.spec.tsx
  packages/typography/src/styled/StyledCodeBlock.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
Labels: PR: Breaking Change :boom:

#1761 feat(chrome)!: detect Footer automatically with Context
  docs/migration.md
  packages/chrome/demo/stories/ChromeStory.tsx
  packages/chrome/src/elements/body/Body.tsx
  packages/chrome/src/elements/body/Content.spec.tsx
  packages/chrome/src/elements/body/Content.tsx
  packages/chrome/src/elements/footer/Footer.tsx
  packages/chrome/src/index.ts
  packages/chrome/src/types/index.ts
  packages/chrome/src/utils/useBodyContext.ts
Labels: PR: Breaking Change :boom:

#1763 feat: add refactored `getColor` utility
  .github/CONTRIBUTING.md
  .storybook/preview.js
  docs/migration.md
  package-lock.json
  packages/theming/demo/stories/GetColorStory.tsx
  packages/theming/demo/utilities.stories.mdx
  packages/theming/package.json
  packages/theming/src/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/focusStyles.spec.tsx
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
  packages/theming/src/utils/getColorV8.ts
  packages/theming/src/utils/getFocusBoxShadow.ts
Labels: PR: New Feature :rocket:
