Repository zendeskgarden/react-components, pull requests merged in 2024-08, with the labels that each got.

#1872 fix(dropdowns.next): `Combobox` with `isBare` option never shows horiz scrollbar to preserve styling
  packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns.next/src/views/combobox/StyledTrigger.ts
Labels: PR: Bug Fix :bug:

#1874 chore: sync `next` with `main`
  docs/changelogs/v8.md
  packages/dropdowns/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns/src/views/combobox/StyledTrigger.ts
Labels: PR: Internal :seedling:

#1882 fix(tooltips): renders correct arrow dimensions based on tooltip size
  packages/dropdowns.legacy/src/styled/menu/StyledMenu.ts
  packages/dropdowns/src/views/menu/StyledMenu.ts
  packages/theming/src/utils/arrowStyles.spec.tsx
  packages/theming/src/utils/arrowStyles.ts
  packages/tooltips/src/elements/Tooltip.spec.tsx
  packages/tooltips/src/styled/StyledTooltip.ts
Labels: PR: Bug Fix :bug:

#1883 fix: updates displayNames to match subcomponent properties
  packages/chrome/src/elements/footer/FooterItem.tsx
  packages/chrome/src/elements/header/HeaderItem.tsx
  packages/chrome/src/elements/header/HeaderItemIcon.tsx
  packages/chrome/src/elements/header/HeaderItemText.tsx
  packages/chrome/src/elements/header/HeaderItemWrapper.tsx
  packages/chrome/src/elements/nav/NavItem.tsx
  packages/chrome/src/elements/nav/NavItemIcon.tsx
  packages/chrome/src/elements/nav/NavItemText.tsx
  packages/dropdowns/src/elements/combobox/Hint.tsx
  packages/dropdowns/src/elements/combobox/Label.tsx
  packages/dropdowns/src/elements/combobox/Message.tsx
  packages/forms/src/elements/common/Hint.tsx
  packages/forms/src/elements/common/Label.tsx
  packages/forms/src/elements/common/Message.tsx
  packages/grid/src/elements/Col.tsx
  packages/grid/src/elements/Row.tsx
  packages/modals/src/elements/Body.tsx
  packages/modals/src/elements/Close.tsx
  packages/modals/src/elements/Footer.tsx
  packages/modals/src/elements/FooterItem.tsx
  packages/modals/src/elements/Header.tsx
  packages/notifications/src/elements/Close.spec.tsx
  packages/notifications/src/elements/Close.tsx
  packages/notifications/src/elements/Notification.tsx
  packages/notifications/src/elements/Paragraph.spec.tsx
  packages/notifications/src/elements/Paragraph.tsx
  packages/notifications/src/elements/Title.spec.tsx
  packages/notifications/src/elements/Title.tsx
  packages/notifications/src/elements/alert/Alert.spec.tsx
  packages/notifications/src/elements/alert/Alert.tsx
  packages/notifications/src/elements/alert/Close.spec.tsx
  packages/notifications/src/elements/alert/Close.tsx
  packages/notifications/src/elements/alert/Paragraph.spec.tsx
  packages/notifications/src/elements/alert/Paragraph.tsx
  packages/notifications/src/elements/alert/Title.spec.tsx
  packages/notifications/src/elements/alert/Title.tsx
  packages/notifications/src/elements/well/Paragraph.spec.tsx
  packages/notifications/src/elements/well/Paragraph.tsx
  packages/notifications/src/elements/well/Title.spec.tsx
  packages/notifications/src/elements/well/Title.tsx
  packages/notifications/src/elements/well/Well.spec.tsx
  packages/notifications/src/elements/well/Well.tsx
  packages/notifications/src/index.ts
  packages/pagination/src/elements/CursorPagination/CursorPagination.tsx
  packages/tables/src/elements/Body.tsx
  packages/tables/src/elements/Caption.tsx
  packages/tables/src/elements/Cell.tsx
  packages/tables/src/elements/GroupRow.tsx
  packages/tables/src/elements/Head.tsx
  packages/tables/src/elements/HeaderCell.tsx
  packages/tables/src/elements/HeaderRow.tsx
  packages/tables/src/elements/OverflowButton.tsx
  packages/tables/src/elements/Row.tsx
  packages/tables/src/elements/SortableCell.tsx
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/src/elements/TabList.tsx
  packages/tabs/src/elements/TabPanel.tsx
  packages/tooltips/src/elements/Paragraph.tsx
  packages/tooltips/src/elements/Title.tsx
Labels: PR: Bug Fix :bug:

#1884 fix(chrome): update Nav.List displayName
  packages/chrome/src/elements/nav/NavList.tsx
Labels: PR: Internal :seedling:

#1885 feat: allow color-related props to receive color variable keys in addition to hex values
  packages/accordions/demo/stories/TimelineStory.tsx
  packages/accordions/src/styled/timeline/StyledItemIcon.ts
  packages/accordions/src/types/index.ts
  packages/avatars/demo/stories/AvatarStory.tsx
  packages/avatars/demo/~patterns/stories/MenuStory.tsx
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/src/types/index.ts
  packages/tags/src/types/index.ts
  packages/typography/demo/code.stories.mdx
  packages/typography/src/elements/span/Span.spec.tsx
  packages/typography/src/styled/StyledFont.tsx
  packages/typography/src/types/index.ts
Labels: PR: New Feature :rocket:

#1887 chore(theming): add `withTheme` removal to migration guide
  docs/migration.md
Labels: PR: Docs :memo:

#1886 fix(dropdowns.next): adds missing role to ItemGroup
  packages/dropdowns.next/src/elements/menu/ItemGroup.tsx
Labels: PR: Bug Fix :bug:

#1888 fix(forms): ensure `Message` validation icon has a role of "img"
  packages/forms/src/elements/common/Message.spec.tsx
  packages/forms/src/styled/common/StyledMessageIcon.ts
Labels: PR: Bug Fix :bug:

#1891 chore(theming): remove `PALETTE_V8` export
  packages/modals/src/styled/StyledFooter.spec.tsx
  packages/modals/src/styled/StyledFooter.ts
  packages/theming/src/index.ts
Labels: PR: Internal :seedling:

#1892 chore(modals)!: rename `TooltipModal` to `TooltipDialog`
  docs/migration.md
  packages/colorpickers/src/elements/ColorPickerDialog/index.tsx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
  packages/colorpickers/src/styled/ColorPickerDialog/StyledTooltipBody.ts
  packages/colorpickers/src/styled/ColorPickerDialog/StyledTooltipDialog.ts
  packages/colorpickers/src/styled/index.ts
  packages/colorpickers/src/types/index.ts
  packages/modals/README.md
  packages/modals/demo/stories/TooltipDialogStory.tsx
  packages/modals/demo/stories/data.ts
  packages/modals/demo/tooltipDialog.stories.mdx
  packages/modals/demo/tooltipModal.stories.mdx
  packages/modals/src/elements/TooltipDialog/Body.spec.tsx
  packages/modals/src/elements/TooltipDialog/Body.tsx
  packages/modals/src/elements/TooltipDialog/Close.spec.tsx
  packages/modals/src/elements/TooltipDialog/Close.tsx
  packages/modals/src/elements/TooltipDialog/Footer.tsx
  packages/modals/src/elements/TooltipDialog/FooterItem.tsx
  packages/modals/src/elements/TooltipDialog/Title.spec.tsx
  packages/modals/src/elements/TooltipDialog/Title.tsx
  packages/modals/src/elements/TooltipDialog/TooltipDialog.spec.tsx
  packages/modals/src/elements/TooltipDialog/TooltipDialog.tsx
  packages/modals/src/index.ts
  packages/modals/src/styled/StyledTooltipDialog.ts
  packages/modals/src/styled/StyledTooltipDialogBackdrop.ts
  packages/modals/src/styled/StyledTooltipDialogBody.ts
  packages/modals/src/styled/StyledTooltipDialogClose.ts
  packages/modals/src/styled/StyledTooltipDialogFooter.ts
  packages/modals/src/styled/StyledTooltipDialogFooterItem.ts
  packages/modals/src/styled/StyledTooltipDialogTitle.ts
  packages/modals/src/styled/StyledTooltipWrapper.ts
  packages/modals/src/styled/index.ts
  packages/modals/src/types/index.ts
  packages/modals/src/utils/useTooltipDialogContext.spec.tsx
  packages/modals/src/utils/useTooltipDialogContext.tsx
Labels: PR: Breaking Change :boom:

#1893 fix: React peer dependency ranges
  package-lock.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/draggable/package.json
  packages/dropdowns.legacy/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/theming/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Bug Fix :bug:

#1896 chore: configure `v8` branch for maintenance
  .github/workflows/ci.yaml
  lerna.json
Labels: PR: Internal :seedling:

#1900 docs: enhance migration guide
  docs/migration.md
Labels: PR: Docs :memo:

#1897 fix(avatars): use default background surfaceColor with statuses
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/styled/StyledAvatar.ts
Labels: PR: Bug Fix :bug:

#1902 fix(tooltips): fix arrow position when using `end-bottom` placement
  packages/theming/src/utils/arrowStyles.ts
  packages/tooltips/src/styled/StyledTooltip.ts
Labels: PR: Bug Fix :bug:

#1903 fix: ensure `tag` script releases to the correct default branch
  .github/workflows/ci.yaml
  utils/scripts/tag.mjs
Labels: PR: Internal :seedling:

#1901 fix(avatars): rectify `StatusIndicator` sizing and position
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/src/styled/StyledStatusIndicator.spec.tsx
  packages/avatars/src/styled/StyledStatusIndicator.ts
  packages/avatars/src/styled/StyledStatusIndicatorBase.ts
Labels: PR: Bug Fix :bug:

#1904 fix(tabs): add border-color transition for smoother animation
  packages/tabs/src/styled/StyledTabList.ts
Labels: PR: Bug Fix :bug:

#1907 fix(tags): ensure prop sheet refers to internal website URL
  packages/tags/src/types/index.ts
Labels: PR: Docs :memo:

#1908 fix(tabs): border styling
  packages/tabs/src/styled/StyledTab.ts
Labels: PR: Bug Fix :bug:
