Repository zendeskgarden/react-components, pull requests merged in 2024-11, with the labels that each got.

#1963 refactor(draggable, modals, typography): use transient props where appropriate
  packages/draggable/src/elements/draggable-list/DraggableList.tsx
  packages/draggable/src/elements/draggable-list/components/DropIndicator.tsx
  packages/draggable/src/elements/draggable-list/components/Item.tsx
  packages/draggable/src/elements/draggable/Draggable.tsx
  packages/draggable/src/elements/dropzone/Dropzone.tsx
  packages/draggable/src/elements/dropzone/components/Icon.tsx
  packages/draggable/src/styled/draggable-list/StyledDraggableList.ts
  packages/draggable/src/styled/draggable-list/StyledDropIndicator.ts
  packages/draggable/src/styled/draggable-list/StyledItem.ts
  packages/draggable/src/styled/draggable/StyledDraggable.spec.tsx
  packages/draggable/src/styled/draggable/StyledDraggable.ts
  packages/draggable/src/styled/dropzone/StyledDropzone.ts
  packages/draggable/src/styled/dropzone/StyledIcon.spec.tsx
  packages/draggable/src/styled/dropzone/StyledIcon.ts
  packages/modals/src/elements/Drawer/Drawer.tsx
  packages/modals/src/elements/Drawer/Header.tsx
  packages/modals/src/elements/Header.tsx
  packages/modals/src/elements/Modal.tsx
  packages/modals/src/elements/TooltipDialog/TooltipDialog.tsx
  packages/modals/src/styled/StyledBackdrop.spec.tsx
  packages/modals/src/styled/StyledBackdrop.ts
  packages/modals/src/styled/StyledDrawerHeader.spec.tsx
  packages/modals/src/styled/StyledDrawerHeader.ts
  packages/modals/src/styled/StyledHeader.spec.tsx
  packages/modals/src/styled/StyledHeader.ts
  packages/modals/src/styled/StyledModal.spec.tsx
  packages/modals/src/styled/StyledModal.ts
  packages/modals/src/styled/StyledTooltipDialog.ts
  packages/modals/src/styled/StyledTooltipWrapper.ts
  packages/typography/src/elements/Code.tsx
  packages/typography/src/elements/CodeBlock.tsx
  packages/typography/src/elements/LG.tsx
  packages/typography/src/elements/MD.tsx
  packages/typography/src/elements/SM.tsx
  packages/typography/src/elements/XL.tsx
  packages/typography/src/elements/XXL.tsx
  packages/typography/src/elements/XXXL.tsx
  packages/typography/src/elements/lists/OrderedList.tsx
  packages/typography/src/elements/lists/OrderedListItem.tsx
  packages/typography/src/elements/lists/UnorderedList.tsx
  packages/typography/src/elements/lists/UnorderedListItem.tsx
  packages/typography/src/elements/span/Span.tsx
  packages/typography/src/styled/StyledCode.ts
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.ts
  packages/typography/src/styled/StyledFont.spec.tsx
  packages/typography/src/styled/StyledFont.tsx
  packages/typography/src/styled/StyledList.spec.tsx
  packages/typography/src/styled/StyledList.ts
  packages/typography/src/styled/StyledListItem.spec.tsx
  packages/typography/src/styled/StyledListItem.ts
Labels: PR: Internal :seedling:

#1969 fix(grid): use `auto` tooltip positioning for `Pane.SplitterButton`
  packages/grid/src/elements/pane/components/SplitterButton.tsx
Labels: PR: Bug Fix :bug:

#1970 fix(theming): swap `hasOwn` for `hasOwnProperty` call in `getColor`
  packages/theming/src/utils/getColor.ts
Labels: PR: Bug Fix :bug:

#1968 refactor(colorpickers, grid, loaders, notifications, tags tooltips): use transient props where appropriate
  packages/.template/src/styled/Styled{{capitalize component}}.ts
  packages/avatars/src/elements/Avatar.tsx
  packages/chrome/src/styled/body/StyledMain.tsx
  packages/colorpickers/src/elements/ColorPicker/ColorWell.tsx
  packages/colorpickers/src/styled/ColorPicker/StyledColorWellThumb.ts
  packages/colorpickers/src/styled/ColorPicker/StyledHexField.ts
  packages/datepickers/src/styled/StyledHeaderPaddle.ts
  packages/dropdowns.legacy/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns.legacy/src/elements/Menu/Items/HeaderIcon.tsx
  packages/dropdowns.legacy/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns.legacy/src/elements/Select/Select.tsx
  packages/dropdowns.legacy/src/elements/Trigger/Trigger.tsx
  packages/dropdowns.legacy/src/styled/items/header/StyledHeaderIcon.ts
  packages/dropdowns.legacy/src/styled/multiselect/StyledMultiselectInput.ts
  packages/dropdowns.legacy/src/styled/multiselect/StyledMultiselectMoreAnchor.ts
  packages/dropdowns.legacy/src/styled/select/StyledInput.ts
  packages/dropdowns/src/elements/combobox/Option.tsx
  packages/forms/src/elements/common/Message.tsx
  packages/grid/src/elements/Col.tsx
  packages/grid/src/elements/Grid.tsx
  packages/grid/src/elements/Row.tsx
  packages/grid/src/elements/pane/components/Splitter.tsx
  packages/grid/src/elements/pane/components/SplitterButton.tsx
  packages/grid/src/styled/StyledCol.spec.tsx
  packages/grid/src/styled/StyledCol.ts
  packages/grid/src/styled/StyledGrid.spec.tsx
  packages/grid/src/styled/StyledGrid.ts
  packages/grid/src/styled/StyledRow.spec.tsx
  packages/grid/src/styled/StyledRow.ts
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButton.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButtonContainer.ts
  packages/loaders/src/elements/Dots.tsx
  packages/loaders/src/elements/Inline.tsx
  packages/loaders/src/elements/Progress.tsx
  packages/loaders/src/elements/Spinner.tsx
  packages/loaders/src/styled/StyledDots.ts
  packages/loaders/src/styled/StyledInline.ts
  packages/loaders/src/styled/StyledProgress.ts
  packages/loaders/src/styled/StyledSVG.spec.tsx
  packages/loaders/src/styled/StyledSVG.ts
  packages/loaders/src/styled/StyledSpinnerCircle.spec.tsx
  packages/loaders/src/styled/StyledSpinnerCircle.ts
  packages/modals/src/elements/Footer.tsx
  packages/modals/src/styled/StyledFooter.spec.tsx
  packages/modals/src/styled/StyledFooter.ts
  packages/notifications/src/elements/toaster/ToastSlot.tsx
  packages/notifications/src/elements/toaster/styled.ts
  packages/pagination/src/styled/OffsetPagination/StyledList.ts
  packages/pagination/src/styled/OffsetPagination/StyledPageBase.ts
  packages/tables/src/elements/SortableCell.tsx
  packages/tags/src/elements/Tag.tsx
  packages/tags/src/styled/StyledTag.spec.tsx
  packages/tags/src/styled/StyledTag.ts
  packages/theming/src/utils/focusStyles.ts
  packages/theming/src/utils/menuStyles.ts
  packages/tooltips/src/elements/Tooltip.tsx
  packages/tooltips/src/styled/StyledTooltip.ts
  packages/tooltips/src/styled/StyledTooltipWrapper.ts
Labels: PR: Internal :seedling:

#1971 feat(dropdowns): add `hasSelection` prop for use with `<Option type="next">`
  packages/dropdowns/demo/menu.stories.mdx
  packages/dropdowns/demo/stories/MenuStory.tsx
  packages/dropdowns/demo/stories/data.ts
  packages/dropdowns/demo/stories/types.ts
  packages/dropdowns/demo/~patterns/patterns.stories.mdx
  packages/dropdowns/demo/~patterns/stories/MenuAppendStory.tsx
  packages/dropdowns/demo/~patterns/stories/MenuButtonStory.tsx
  packages/dropdowns/demo/~patterns/stories/MenuNestedStory.tsx
  packages/dropdowns/demo/~patterns/stories/NestedStory.tsx
  packages/dropdowns/demo/~patterns/stories/PortalStory.tsx
  packages/dropdowns/demo/~patterns/stories/data.ts
  packages/dropdowns/demo/~patterns/stories/types.ts
  packages/dropdowns/src/elements/combobox/Option.spec.tsx
  packages/dropdowns/src/elements/combobox/Option.tsx
  packages/dropdowns/src/types/index.ts
  packages/dropdowns/src/views/combobox/StyledField.ts
  packages/dropdowns/src/views/combobox/StyledOptionSelectionIcon.ts
  packages/dropdowns/src/views/index.ts
Labels: PR: New Feature :rocket:

#1980 chore: adjust renovate schedule
  .github/renovate.json
  README.md
Labels: PR: Internal :seedling:
