Repository zendeskgarden/react-components, pull requests merged in 2024-09, with the labels that each got.

#1911 fix(tabs): allow focus ring to resize based on content
  packages/tabs/src/styled/StyledTab.ts
Labels: PR: Bug Fix :bug:

#1915 fix(typography): revert `react-prism-renderer` to v1
  package-lock.json
  packages/typography/package.json
  packages/typography/src/elements/CodeBlock.tsx
Labels: PR: Bug Fix :bug:

#1916 fix(typography): set `CodeBlock` background to `background.recessed`
  packages/typography/src/styled/StyledCodeBlock.ts
Labels: PR: Bug Fix :bug:

#1914 docs: add removal of `theme` default prop ADR
  docs/adrs/002-theme-default-prop-removal.md
  docs/adrs/README.md
Labels: PR: Internal :seedling:

#1918 fix(dropdowns): prevents menus focus focusing items early during animation
  packages/dropdowns/src/elements/menu/MenuList.tsx
  packages/theming/src/utils/menuStyles.ts
Labels: PR: Bug Fix :bug:

#1917 fix(tooltips): ensure correct padding for `TooltipDialog`'s inner elements if `Close` btn exists
  packages/modals/src/styled/StyledTooltipDialog.ts
  packages/modals/src/styled/StyledTooltipDialogTitle.ts
Labels: PR: Bug Fix :bug:

#1920 fix(chrome): prevent focus on closed `Sheet`
  packages/chrome/src/elements/sheet/Sheet.spec.tsx
  packages/chrome/src/elements/sheet/Sheet.tsx
  packages/chrome/src/styled/sheet/StyledSheet.ts
Labels: PR: Bug Fix :bug:

#1922 docs: adds verbosity to initial v9 migration steps
  docs/migration.md
Labels: PR: Docs :memo:

#1926 feat(loaders): allow color props to receive color variable keys in addition to hex values
  packages/loaders/src/elements/Dots.spec.tsx
  packages/loaders/src/elements/Inline.spec.tsx
  packages/loaders/src/elements/Progress.spec.tsx
  packages/loaders/src/styled/StyledInline.ts
  packages/loaders/src/styled/StyledProgress.ts
  packages/loaders/src/styled/StyledSVG.spec.tsx
  packages/loaders/src/styled/StyledSVG.ts
  packages/loaders/src/types/index.ts
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
Labels: PR: New Feature :rocket:

#1927 fix(colorpickers): prevent arrow from positioning over a `ColorSwatchDialog` tooltip
  packages/avatars/demo/avatar.stories.mdx
  packages/colorpickers/src/elements/ColorSwatch/index.tsx
Labels: PR: Bug Fix :bug:

#1929 chore: v9 QA sweep
  docs/changelogs/v6.md
  docs/changelogs/v7.md
  docs/changelogs/v8.md
  docs/migration.md
  docs/migrations/v6.md
  docs/migrations/v7.md
  packages/colorpickers/src/elements/ColorPickerDialog/index.tsx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
  packages/modals/src/elements/TooltipDialog/TooltipDialog.tsx
  packages/modals/src/types/index.ts
  packages/theming/demo/stories/GetColorStory.tsx
Labels: PR: Bug Fix :bug:

#1932 chore(breadcrumbs): remove `Anchor` underline in demo
  packages/breadcrumbs/demo/stories/BreadcrumbStory.tsx
Labels: PR: Internal :seedling:

#1930 fix(dropdowns): ensure focus is returned to menu trigger before calling `onChange`
  docs/migration.md
  package-lock.json
  packages/dropdowns/package.json
  packages/dropdowns/src/elements/menu/Menu.spec.tsx
  packages/dropdowns/src/elements/menu/Menu.tsx
  packages/dropdowns/src/types/index.ts
Labels: PR: Bug Fix :bug:

#1933 docs: add missing `restoreFocus` prop description in `Menu`'s StoryBook page
  packages/dropdowns/src/elements/menu/Menu.tsx
Labels: PR: Internal :seedling:

#1936 fix(theming): align `success`, `warning`, and `danger` border color variables with design
  packages/notifications/src/styled/StyledBase.spec.tsx
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
Labels: PR: Bug Fix :bug:

#1935 chore: rename `.markdownlintrc` to `.markdownlint.json` for VSCode extension compatibility
  .markdownlint.json
Labels: PR: Internal :seedling:

#1934 ci: restore Coveralls PR comments
  .github/workflows/ci.yaml
  package-lock.json
  package.json
Labels: PR: Internal :seedling:

#1938 fix(theming)!: remove `background.primary` color variable
  packages/avatars/demo/~patterns/stories/MenuStory.tsx
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/types/index.ts
  packages/theming/demo/stories/ArrowStylesStory.tsx
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
Labels: PR: Internal :seedling:
