Repository zendeskgarden/react-components, pull requests merged in 2024-10, with the labels that each got.

#1939 fix(tables): replace invalid `<div>` from Table `OverflowButton` w/ `<span>`
  packages/tables/src/styled/StyledOverflowButton.ts
Labels: PR: Bug Fix :bug:

#1948 refactor(chrome): use transient props where appropriate
  packages/chrome/src/elements/SkipNav.tsx
  packages/chrome/src/elements/body/Content.tsx
  packages/chrome/src/elements/header/Header.tsx
  packages/chrome/src/elements/header/HeaderItem.tsx
  packages/chrome/src/elements/header/HeaderItemText.tsx
  packages/chrome/src/elements/nav/Nav.tsx
  packages/chrome/src/elements/nav/NavItem.tsx
  packages/chrome/src/elements/nav/NavItemText.tsx
  packages/chrome/src/elements/sheet/Sheet.tsx
  packages/chrome/src/elements/sheet/components/Footer.tsx
  packages/chrome/src/elements/sheet/components/Header.tsx
  packages/chrome/src/styled/StyledSkipNav.ts
  packages/chrome/src/styled/body/StyledContent.tsx
  packages/chrome/src/styled/header/StyledBaseHeaderItem.ts
  packages/chrome/src/styled/header/StyledHeader.ts
  packages/chrome/src/styled/header/StyledHeaderItem.ts
  packages/chrome/src/styled/header/StyledHeaderItemText.ts
  packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
  packages/chrome/src/styled/nav/StyledLogoNavItem.ts
  packages/chrome/src/styled/nav/StyledNav.ts
  packages/chrome/src/styled/nav/StyledNavButton.ts
  packages/chrome/src/styled/nav/StyledNavItemText.ts
  packages/chrome/src/styled/sheet/StyledSheet.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheet.ts
  packages/chrome/src/styled/sheet/StyledSheetFooter.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetFooter.ts
  packages/chrome/src/styled/sheet/StyledSheetHeader.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetHeader.ts
  packages/chrome/src/styled/sheet/StyledSheetWrapper.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetWrapper.ts
Labels: PR: Internal :seedling:

#1949 refactor(buttons): use transient props where appropriate
  packages/buttons/src/elements/Anchor.tsx
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/ChevronButton.tsx
  packages/buttons/src/elements/IconButton.tsx
  packages/buttons/src/styled/StyledAnchor.spec.tsx
  packages/buttons/src/styled/StyledAnchor.ts
  packages/buttons/src/styled/StyledButton.spec.tsx
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledIconButton.spec.tsx
  packages/buttons/src/styled/StyledIconButton.ts
Labels: PR: Internal :seedling:

#1952 refactor(forms): use transient props where appropriate
  packages/forms/src/elements/Checkbox.tsx
  packages/forms/src/elements/FileUpload.tsx
  packages/forms/src/elements/Input.tsx
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/elements/Radio.tsx
  packages/forms/src/elements/Range.tsx
  packages/forms/src/elements/Select.tsx
  packages/forms/src/elements/Textarea.tsx
  packages/forms/src/elements/Toggle.tsx
  packages/forms/src/elements/common/Fieldset.tsx
  packages/forms/src/elements/common/Label.tsx
  packages/forms/src/elements/common/Legend.tsx
  packages/forms/src/elements/common/Message.tsx
  packages/forms/src/elements/faux-input/FauxInput.tsx
  packages/forms/src/elements/file-list/components/File.tsx
  packages/forms/src/elements/input-group/InputGroup.spec.tsx
  packages/forms/src/elements/input-group/InputGroup.tsx
  packages/forms/src/elements/tiles/components/Description.tsx
  packages/forms/src/elements/tiles/components/Icon.tsx
  packages/forms/src/elements/tiles/components/Label.tsx
  packages/forms/src/styled/common/StyledFieldset.ts
  packages/forms/src/styled/common/StyledLabel.spec.tsx
  packages/forms/src/styled/common/StyledLabel.ts
  packages/forms/src/styled/common/StyledLegend.ts
  packages/forms/src/styled/common/StyledMessage.spec.tsx
  packages/forms/src/styled/common/StyledMessage.ts
  packages/forms/src/styled/file-list/StyledFile.spec.tsx
  packages/forms/src/styled/file-list/StyledFile.ts
  packages/forms/src/styled/file-upload/StyledFileUpload.ts
  packages/forms/src/styled/input-group/StyledInputGroup.ts
  packages/forms/src/styled/radio/StyledRadioInput.spec.tsx
  packages/forms/src/styled/radio/StyledRadioInput.ts
  packages/forms/src/styled/radio/StyledRadioLabel.ts
  packages/forms/src/styled/range/StyledRangeInput.spec.tsx
  packages/forms/src/styled/range/StyledRangeInput.ts
  packages/forms/src/styled/select/StyledSelect.spec.tsx
  packages/forms/src/styled/select/StyledSelect.ts
  packages/forms/src/styled/select/StyledSelectWrapper.ts
  packages/forms/src/styled/text/StyledTextArea.spec.tsx
  packages/forms/src/styled/text/StyledTextFauxInput.spec.tsx
  packages/forms/src/styled/text/StyledTextFauxInput.ts
  packages/forms/src/styled/text/StyledTextInput.spec.tsx
  packages/forms/src/styled/text/StyledTextInput.tsx
  packages/forms/src/styled/text/StyledTextMediaInput.ts
  packages/forms/src/styled/text/StyledTextarea.ts
  packages/forms/src/styled/tiles/StyledTileDescription.ts
  packages/forms/src/styled/tiles/StyledTileIcon.ts
  packages/forms/src/styled/tiles/StyledTileLabel.ts
Labels: PR: Internal :seedling:

#1955 feat(datepickers): provide `appendToNode` prop for handling `DatePicker` calendar rendering
  packages/datepickers/demo/datePicker.stories.mdx
  packages/datepickers/demo/~patterns/patterns.stories.mdx
  packages/datepickers/demo/~patterns/stories/CalendarStory.tsx
  packages/datepickers/src/elements/DatePicker/DatePicker.spec.tsx
  packages/datepickers/src/elements/DatePicker/DatePicker.tsx
  packages/datepickers/src/types/index.ts
Labels: PR: New Feature :rocket:

#1957 refactor(dropdowns.legacy): use transient props where appropriate
  packages/dropdowns.legacy/src/elements/Menu/Items/AddItem.tsx
  packages/dropdowns.legacy/src/elements/Menu/Items/HeaderItem.tsx
  packages/dropdowns.legacy/src/elements/Menu/Items/Item.tsx
  packages/dropdowns.legacy/src/elements/Menu/Items/ItemMeta.tsx
  packages/dropdowns.legacy/src/elements/Menu/Items/MediaBody.tsx
  packages/dropdowns.legacy/src/elements/Menu/Items/MediaFigure.tsx
  packages/dropdowns.legacy/src/elements/Menu/Items/NextItem.tsx
  packages/dropdowns.legacy/src/elements/Menu/Items/PreviousItem.tsx
  packages/dropdowns.legacy/src/elements/Menu/Menu.tsx
  packages/dropdowns.legacy/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns.legacy/src/styled/items/StyledItem.spec.tsx
  packages/dropdowns.legacy/src/styled/items/StyledItem.ts
  packages/dropdowns.legacy/src/styled/items/StyledItemIcon.ts
  packages/dropdowns.legacy/src/styled/items/StyledItemMeta.ts
  packages/dropdowns.legacy/src/styled/items/StyledNextIcon.tsx
  packages/dropdowns.legacy/src/styled/items/StyledPreviousIcon.tsx
  packages/dropdowns.legacy/src/styled/items/header/StyledHeaderItem.ts
  packages/dropdowns.legacy/src/styled/items/media/StyledMediaBody.ts
  packages/dropdowns.legacy/src/styled/items/media/StyledMediaFigure.ts
  packages/dropdowns.legacy/src/styled/menu/StyledMenu.ts
  packages/dropdowns.legacy/src/styled/menu/StyledMenuWrapper.ts
  packages/dropdowns.legacy/src/styled/multiselect/StyledMultiselectItemsContainer.ts
  packages/dropdowns.legacy/src/styled/multiselect/StyledMultiselectMoreAnchor.ts
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/elements/faux-input/FauxInput.tsx
  packages/forms/src/types/index.ts
Labels: PR: Internal :seedling:

#1960 fix(theming): `getColor` memoization peformance
  packages/theming/demo/~patterns/patterns.stories.mdx
  packages/theming/demo/~patterns/stories/GetColorStory.tsx
  packages/theming/demo/~patterns/stories/GetColorV8Story.tsx
  packages/theming/src/utils/getColor.ts
  packages/theming/src/utils/getColorV8.ts
Labels: PR: Bug Fix :bug:

#1961 refactor(dropdowns): use transient props where appropriate
  packages/dropdowns/src/elements/combobox/Combobox.tsx
  packages/dropdowns/src/elements/combobox/Listbox.tsx
  packages/dropdowns/src/elements/combobox/OptGroup.tsx
  packages/dropdowns/src/elements/combobox/Option.tsx
  packages/dropdowns/src/elements/combobox/OptionMeta.tsx
  packages/dropdowns/src/elements/menu/Item.tsx
  packages/dropdowns/src/elements/menu/ItemGroup.tsx
  packages/dropdowns/src/elements/menu/ItemMeta.tsx
  packages/dropdowns/src/elements/menu/MenuList.tsx
  packages/dropdowns/src/views/combobox/StyledCombobox.ts
  packages/dropdowns/src/views/combobox/StyledFloatingListbox.ts
  packages/dropdowns/src/views/combobox/StyledInput.ts
  packages/dropdowns/src/views/combobox/StyledListbox.ts
  packages/dropdowns/src/views/combobox/StyledOptGroup.ts
  packages/dropdowns/src/views/combobox/StyledOption.ts
  packages/dropdowns/src/views/combobox/StyledOptionMeta.ts
  packages/dropdowns/src/views/combobox/StyledTagsButton.ts
  packages/dropdowns/src/views/combobox/StyledTrigger.ts
  packages/dropdowns/src/views/combobox/StyledValue.ts
  packages/dropdowns/src/views/menu/StyledMenu.ts
Labels: PR: Internal :seedling:

#1965 deps: point to correct `react-theming` peerDependency
  package-lock.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/draggable/package.json
  packages/dropdowns.legacy/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Internal :seedling:

#1966 fix(theming): harden `getColor` memoization key generation
  docs/migration.md
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
  packages/theming/src/utils/getColorV8.spec.ts
  packages/theming/src/utils/getColorV8.ts
Labels: PR: Bug Fix :bug:
