Repository zendeskgarden/react-components, pull requests merged in 2024-02, with the labels that each got.

#1696 chore(docs): split up CHANGELOG by major version
  CHANGELOG.md
  docs/changelogs/v6.md
  docs/changelogs/v7.md
  docs/migration.md
Labels: PR: Docs :memo:

#1697 chore: fix config to support `next` prerelease
  .circleci/config.yml
  lerna.json
  utils/scripts/tag.mjs
Labels: PR: Internal :seedling:

#1701 chore(scripts): fix `tag` to release on `next` branch
  package.json
  utils/scripts/tag.mjs
Labels: PR: Internal :seedling:

#1699 fix(combobox): prevent disabled combobox from swapping static/input values on click
  packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns.next/src/elements/combobox/Combobox.tsx
Labels: PR: Bug Fix :bug:

#1700 feat: removes @zendeskgarden/react-utilities
  docs/migration.md
  docs/migrations/v8.md
  package-lock.json
  packages/utilities/.size-snapshot.json
  packages/utilities/README.md
  packages/utilities/package.json
  packages/utilities/src/index.js
  packages/utilities/src/utils/hasType.example.md
  packages/utilities/src/utils/hasType.js
  packages/utilities/src/utils/hasType.spec.js
  packages/utilities/src/utils/requiredParam.js
  packages/utilities/src/utils/requiredParam.spec.js
  tsconfig.json
Labels: PR: Breaking Change :boom:

#1702 feat: removes isRtl and getDocument helpers from @zendeskgarden/react-theming
  docs/migration.md
  packages/theming/README.md
  packages/theming/src/index.ts
  packages/theming/src/utils/getDocument.spec.ts
  packages/theming/src/utils/getDocument.ts
  packages/theming/src/utils/isRtl.spec.ts
  packages/theming/src/utils/isRtl.ts
  packages/theming/src/utils/withTheme.spec.tsx
  packages/theming/src/utils/withTheme.ts
Labels: PR: Breaking Change :boom:

#1703 feat: bump peer dep styled-components to v5.1.0 minimum
  docs/migration.md
  package-lock.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/drag-drop/package.json
  packages/dropdowns/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tags/package.json
  packages/theming/package.json
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Breaking Change :boom:

#1704 feat(theming): add arrow/menu position and floating placement utilities
  package-lock.json
  packages/theming/package.json
  packages/theming/src/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/getArrowPosition.spec.ts
  packages/theming/src/utils/getArrowPosition.ts
  packages/theming/src/utils/getFloatingPlacements.spec.ts
  packages/theming/src/utils/getFloatingPlacements.ts
  packages/theming/src/utils/getMenuPosition.spec.ts
  packages/theming/src/utils/getMenuPosition.ts
Labels: PR: New Feature :rocket:

#1705 fix(combobox): prevent controlled input cursor jump
  package-lock.json
  packages/dropdowns.next/package.json
Labels: PR: Bug Fix :bug:

#1706 chore: fix corrupt `package-lock.json`
  package-lock.json
Labels: PR: Bug Fix :bug:

#1707 fix: reverts dependency bump react-merge-refs v2
  package-lock.json
  packages/buttons/package.json
  packages/buttons/src/elements/Button.tsx
  packages/chrome/package.json
  packages/chrome/src/elements/sheet/Sheet.tsx
  packages/dropdowns.next/package.json
  packages/dropdowns.next/src/elements/combobox/Option.tsx
  packages/dropdowns.next/src/elements/menu/Item.tsx
  packages/dropdowns.next/src/elements/menu/Menu.tsx
  packages/dropdowns/package.json
  packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns/src/elements/Combobox/Combobox.tsx
  packages/dropdowns/src/elements/Fields/Field.tsx
  packages/dropdowns/src/elements/Menu/Items/Item.tsx
  packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns/src/elements/Select/Select.tsx
  packages/forms/package.json
  packages/forms/src/elements/MediaInput.tsx
  packages/forms/src/elements/Range.tsx
  packages/forms/src/elements/Textarea.tsx
  packages/forms/src/elements/tiles/components/Label.tsx
  packages/grid/package.json
  packages/grid/src/elements/pane/Pane.tsx
  packages/grid/src/elements/pane/components/Splitter.tsx
  packages/modals/package.json
  packages/modals/src/elements/DrawerModal/DrawerModal.tsx
  packages/modals/src/elements/Modal.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
  packages/tabs/package.json
  packages/tabs/src/elements/Tab.tsx
  packages/tooltips/package.json
  packages/tooltips/src/elements/Tooltip.tsx
  utils/test/jest.config.js
Labels: PR: Bug Fix :bug:

#1711 feat(colorpickers)!: refactor `ColorSwatch` with improved accessibility backed by a native input (radio or checkbox) group
  docs/migration.md
  package-lock.json
  packages/colorpickers/demo/colorPickerDialog.stories.mdx
  packages/colorpickers/demo/colorSwatch.stories.mdx
  packages/colorpickers/demo/colorSwatchDialog.stories.mdx
  packages/colorpickers/package.json
  packages/colorpickers/src/elements/ColorSwatch/index.spec.tsx
  packages/colorpickers/src/elements/ColorSwatch/index.tsx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.spec.tsx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
  packages/colorpickers/src/styled/ColorSwatch/StyledCheckIcon.spec.tsx
  packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatch.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchInput.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchLabel.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledIcon.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledSwatchButton.ts
  packages/colorpickers/src/styled/index.ts
  packages/colorpickers/src/types/index.ts
Labels: PR: Breaking Change :boom:

#1709 chore!: replace Popper with Floating UI
  docs/migration.md
  package-lock.json
  packages/colorpickers/demo/colorPickerDialog.stories.mdx
  packages/colorpickers/demo/colorSwatchDialog.stories.mdx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
  packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
  packages/colorpickers/src/types/index.ts
  packages/datepickers/demo/datepicker.stories.mdx
  packages/datepickers/package.json
  packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
  packages/datepickers/src/elements/Datepicker/Datepicker.tsx
  packages/datepickers/src/elements/Datepicker/components/Input.tsx
  packages/datepickers/src/elements/Datepicker/utils/garden-placements.spec.ts
  packages/datepickers/src/elements/Datepicker/utils/garden-placements.ts
  packages/datepickers/src/index.ts
  packages/datepickers/src/styled/StyledMenuWrapper.ts
  packages/datepickers/src/types/index.ts
  packages/dropdowns.next/src/elements/menu/MenuList.tsx
  packages/dropdowns.next/src/elements/menu/utils.ts
  packages/dropdowns.next/src/types/index.ts
  packages/modals/package.json
  packages/modals/src/elements/TooltipModal/TooltipModal.spec.tsx
  packages/modals/src/elements/TooltipModal/TooltipModal.tsx
  packages/modals/src/styled/StyledTooltipModal.ts
  packages/modals/src/styled/StyledTooltipWrapper.ts
  packages/modals/src/types/index.ts
  packages/modals/src/utils/gardenPlacements.tsx
  packages/theming/src/utils/getArrowPosition.spec.ts
  packages/theming/src/utils/getArrowPosition.ts
  packages/theming/src/utils/getFloatingPlacements.ts
  packages/theming/src/utils/menuStyles.ts
  packages/tooltips/demo/tooltip.stories.mdx
  packages/tooltips/package.json
  packages/tooltips/src/elements/Tooltip.tsx
  packages/tooltips/src/elements/utils.ts
  packages/tooltips/src/styled/StyledTooltip.ts
  packages/tooltips/src/styled/StyledTooltipWrapper.ts
  packages/tooltips/src/types/index.ts
  packages/tooltips/src/utils/gardenPlacements.spec.ts
  packages/tooltips/src/utils/gardenPlacements.ts
Labels: PR: Breaking Change :boom:

#1716 feat!: renames Datepicker components to DatePicker
  docs/migration.md
  packages/datepickers/README.md
  packages/datepickers/demo/datePicker.stories.mdx
  packages/datepickers/demo/datePickerRange.stories.mdx
  packages/datepickers/demo/stories/DatePickerRangeStory.tsx
  packages/datepickers/demo/stories/DatePickerStory.tsx
  packages/datepickers/src/elements/DatePicker/DatePicker.spec.tsx
  packages/datepickers/src/elements/DatePicker/DatePicker.tsx
  packages/datepickers/src/elements/DatePicker/components/Calendar.tsx
  packages/datepickers/src/elements/DatePicker/components/Input.tsx
  packages/datepickers/src/elements/DatePicker/components/MonthSelector.tsx
  packages/datepickers/src/elements/DatePicker/utils/date-picker-reducer.ts
  packages/datepickers/src/elements/DatePicker/utils/useDatePickerContext.ts
  packages/datepickers/src/elements/DatePickerRange/DatePickerRange.spec.tsx
  packages/datepickers/src/elements/DatePickerRange/DatePickerRange.tsx
  packages/datepickers/src/elements/DatePickerRange/components/Calendar.tsx
  packages/datepickers/src/elements/DatePickerRange/components/End.spec.tsx
  packages/datepickers/src/elements/DatePickerRange/components/End.tsx
  packages/datepickers/src/elements/DatePickerRange/components/Month.tsx
  packages/datepickers/src/elements/DatePickerRange/components/Start.spec.tsx
  packages/datepickers/src/elements/DatePickerRange/components/Start.tsx
  packages/datepickers/src/elements/DatePickerRange/utils/date-picker-range-reducer.ts
  packages/datepickers/src/elements/DatePickerRange/utils/useDatePickerRangeContext.ts
  packages/datepickers/src/elements/Datepicker/utils/useDatepickerContext.ts
  packages/datepickers/src/index.ts
  packages/datepickers/src/styled/StyledDatePicker.ts
  packages/datepickers/src/styled/StyledRangeCalendar.ts
  packages/datepickers/src/styled/index.ts
  packages/datepickers/src/types/index.ts
  packages/datepickers/src/utils/calendar-utils.ts
Labels: PR: Breaking Change :boom:

#1718 chore(next): updates from `main`
  docs/changelogs/v8.md
  package-lock.json
Labels: PR: Internal :seedling:

#1719 feat!: renames Colorpicker(Dialog) to colorPicker(Dialog)
  docs/migration.md
  packages/colorpickers/README.md
  packages/colorpickers/demo/colorPicker.stories.mdx
  packages/colorpickers/demo/colorPickerDialog.stories.mdx
  packages/colorpickers/demo/stories/ColorPickerDialogStory.tsx
  packages/colorpickers/src/elements/ColorPicker/ColorWell.spec.tsx
  packages/colorpickers/src/elements/ColorPicker/ColorWell.tsx
  packages/colorpickers/src/elements/ColorPicker/index.spec.tsx
  packages/colorpickers/src/elements/ColorPicker/index.tsx
  packages/colorpickers/src/elements/ColorPicker/reducer.ts
  packages/colorpickers/src/elements/ColorPickerDialog/index.spec.tsx
  packages/colorpickers/src/elements/ColorPickerDialog/index.tsx
  packages/colorpickers/src/index.ts
  packages/colorpickers/src/styled/ColorPicker/StyledAlphaRange.ts
  packages/colorpickers/src/styled/ColorPicker/StyledColorPicker.ts
  packages/colorpickers/src/styled/ColorPicker/StyledColorWell.ts
  packages/colorpickers/src/styled/ColorPicker/StyledColorWellThumb.ts
  packages/colorpickers/src/styled/ColorPicker/StyledHexField.ts
  packages/colorpickers/src/styled/ColorPicker/StyledHueRange.ts
  packages/colorpickers/src/styled/ColorPicker/StyledInput.ts
  packages/colorpickers/src/styled/ColorPicker/StyledInputGroup.ts
  packages/colorpickers/src/styled/ColorPicker/StyledLabel.ts
  packages/colorpickers/src/styled/ColorPicker/StyledPreview.ts
  packages/colorpickers/src/styled/ColorPicker/StyledRGBAField.spec.tsx
  packages/colorpickers/src/styled/ColorPicker/StyledRGBAField.ts
  packages/colorpickers/src/styled/ColorPicker/StyledSliderGroup.ts
  packages/colorpickers/src/styled/ColorPicker/StyledSliders.spec.tsx
  packages/colorpickers/src/styled/ColorPicker/StyledSliders.ts
  packages/colorpickers/src/styled/ColorPickerDialog/StyledButton.ts
  packages/colorpickers/src/styled/ColorPickerDialog/StyledButtonPreview.ts
  packages/colorpickers/src/styled/ColorPickerDialog/StyledTooltipBody.ts
  packages/colorpickers/src/styled/ColorPickerDialog/StyledTooltipModal.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchLabel.ts
  packages/colorpickers/src/styled/index.ts
  packages/colorpickers/src/types/index.ts
Labels: PR: Breaking Change :boom:

#1720 chore!: remove `ButtonGroup` and `MultiThumbRange` components
  docs/migration.md
  package-lock.json
  packages/buttons/README.md
  packages/buttons/demo/buttonGroup.stories.mdx
  packages/buttons/demo/stories/ButtonGroupStory.tsx
  packages/buttons/demo/stories/data.ts
  packages/buttons/demo/stories/types.ts
  packages/buttons/package.json
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/elements/ButtonGroup.spec.tsx
  packages/buttons/src/elements/ButtonGroup.tsx
  packages/buttons/src/elements/SplitButton.tsx
  packages/buttons/src/index.ts
  packages/buttons/src/styled/StyledButton.spec.tsx
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledSplitButton.spec.tsx
  packages/buttons/src/styled/StyledSplitButton.ts
  packages/buttons/src/styled/index.ts
  packages/buttons/src/types/index.ts
  packages/buttons/src/utils/useButtonGroupContext.ts
  packages/forms/demo/multiThumbRange.stories.mdx
  packages/forms/demo/stories/MultiThumbRangeStory.tsx
  packages/forms/package.json
  packages/forms/src/elements/MultiThumbRange.spec.tsx
  packages/forms/src/elements/MultiThumbRange.tsx
  packages/forms/src/elements/common/Field.tsx
  packages/forms/src/elements/common/Label.tsx
  packages/forms/src/index.ts
  packages/forms/src/styled/index.ts
  packages/forms/src/styled/range/StyledSlider.spec.tsx
  packages/forms/src/styled/range/StyledSlider.ts
  packages/forms/src/styled/range/StyledSliderThumb.spec.tsx
  packages/forms/src/styled/range/StyledSliderThumb.ts
  packages/forms/src/styled/range/StyledSliderTrack.spec.tsx
  packages/forms/src/styled/range/StyledSliderTrack.ts
  packages/forms/src/styled/range/StyledSliderTrackRail.spec.tsx
  packages/forms/src/styled/range/StyledSliderTrackRail.ts
  packages/forms/src/types/index.ts
  packages/forms/src/utils/useFieldContext.ts
Labels: PR: Breaking Change :boom:

#1721 chore: add Storybook tool for dark mode
  .storybook/main.js
  .storybook/preview.js
  packages/theming/src/elements/ThemeProvider.tsx
  packages/theming/src/types/index.ts
Labels: PR: Internal :seedling:

#1725 feat!: renames and prunes type/constant exports from packages
  docs/migration.md
  packages/accordions/src/elements/timeline/components/Item.tsx
  packages/accordions/src/index.ts
  packages/avatars/src/index.ts
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/index.ts
  packages/chrome/demo/stories/ChromeStory.tsx
  packages/chrome/src/elements/header/HeaderItem.spec.tsx
  packages/chrome/src/elements/header/HeaderItem.tsx
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/elements/nav/NavItem.tsx
  packages/chrome/src/index.ts
  packages/chrome/src/types/index.ts
  packages/dropdowns.legacy/src/utils/garden-placements.ts
  packages/dropdowns.legacy/src/utils/gardenPlacements.spec.ts
  packages/dropdowns/src/views/combobox/StyledFloatingListbox.ts
  packages/dropdowns/src/views/menu/StyledMenu.ts
  packages/forms/src/elements/common/Field.tsx
  packages/forms/src/elements/faux-input/FauxInput.tsx
  packages/forms/src/index.ts
  packages/grid/src/index.ts
  packages/modals/src/index.ts
  packages/notifications/src/index.ts
  packages/pagination/src/index.ts
  packages/theming/demo/stories/ArrowStylesStory.tsx
  packages/theming/demo/stories/MenuStylesStory.tsx
  packages/theming/src/index.ts
Labels: PR: Breaking Change :boom:

#1726 fix(colorpickers): `ColorSwatch` focus styling
  packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchInput.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchLabel.ts
Labels: PR: Bug Fix :bug:

#1727 fix: updates constant imports in grid story and lingering dropdowns.next references
  package-lock.json
  packages/dropdowns.legacy/demo/autocomplete.stories.mdx
  packages/dropdowns.legacy/demo/combobox.stories.mdx
  packages/dropdowns.legacy/demo/menu.stories.mdx
  packages/dropdowns.legacy/demo/multiselect.stories.mdx
  packages/dropdowns.legacy/demo/select.stories.mdx
  packages/dropdowns.legacy/src/elements/Autocomplete/Autocomplete.tsx
  packages/dropdowns.legacy/src/elements/Combobox/Combobox.tsx
  packages/dropdowns.legacy/src/elements/Dropdown/Dropdown.tsx
  packages/dropdowns.legacy/src/elements/Menu/Menu.tsx
  packages/dropdowns.legacy/src/elements/Multiselect/Multiselect.tsx
  packages/dropdowns.legacy/src/elements/Select/Select.tsx
  packages/dropdowns.legacy/src/elements/Trigger/Trigger.tsx
  packages/grid/demo/grid.stories.mdx
Labels: PR: Bug Fix :bug:
