Repository zendeskgarden/react-components, pull requests merged in 2024-07, with the labels that each got.

#1836 ci: migrate from CircleCI to Github Actions
  .circleci/config.yml
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  package-lock.json
  package.json
  utils/build/styled.d.ts
  utils/scripts/deploy.mjs
Labels: PR: Internal :seedling:

#1846 feat(pagination): new light/dark mode colors
  packages/pagination/src/styled/OffsetPagination/StyledGapListItem.ts
  packages/pagination/src/styled/OffsetPagination/StyledList.ts
  packages/pagination/src/styled/OffsetPagination/StyledPageBase.spec.tsx
  packages/pagination/src/styled/OffsetPagination/StyledPageBase.ts
Labels: PR: New Feature :rocket:

#1847 chore: sync changes since `v8.76.4` from `main`
  .circleci/config.yml
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  docs/changelogs/v8.md
  package-lock.json
  package.json
  utils/build/styled.d.ts
  utils/scripts/deploy.mjs
Labels: PR: Internal :seedling:

#1848 feat(breadcrumbs): adds light/dark mode colors
  packages/breadcrumbs/src/elements/Breadcrumb.spec.tsx
  packages/breadcrumbs/src/elements/Breadcrumb.tsx
  packages/breadcrumbs/src/styled/StyledBreadcrumbItem.spec.tsx
  packages/breadcrumbs/src/styled/StyledBreadcrumbItem.ts
  packages/breadcrumbs/src/styled/StyledChevronIcon.tsx
Labels: PR: New Feature :rocket:

#1849 feat(chrome): new light/dark mode colors
  packages/chrome/demo/chrome.stories.mdx
  packages/chrome/demo/stories/ChromeStory.tsx
  packages/chrome/package.json
  packages/chrome/src/elements/Chrome.spec.tsx
  packages/chrome/src/elements/Chrome.tsx
  packages/chrome/src/elements/header/HeaderItem.spec.tsx
  packages/chrome/src/elements/header/HeaderItemIcon.tsx
  packages/chrome/src/elements/nav/Nav.tsx
  packages/chrome/src/elements/nav/NavItem.spec.tsx
  packages/chrome/src/elements/nav/NavItem.tsx
  packages/chrome/src/elements/nav/NavItemIcon.tsx
  packages/chrome/src/styled/StyledSkipNav.ts
  packages/chrome/src/styled/StyledSkipNavIcon.ts
  packages/chrome/src/styled/body/StyledBody.ts
  packages/chrome/src/styled/body/StyledContent.tsx
  packages/chrome/src/styled/body/StyledMain.tsx
  packages/chrome/src/styled/footer/StyledFooter.ts
  packages/chrome/src/styled/header/StyledBaseHeaderItem.ts
  packages/chrome/src/styled/header/StyledHeader.ts
  packages/chrome/src/styled/header/StyledHeaderItem.ts
  packages/chrome/src/styled/header/StyledHeaderItemIcon.ts
  packages/chrome/src/styled/header/StyledHeaderItemText.ts
  packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
  packages/chrome/src/styled/nav/StyledBaseNavItem.ts
  packages/chrome/src/styled/nav/StyledBrandmarkNavItem.ts
  packages/chrome/src/styled/nav/StyledLogoNavItem.ts
  packages/chrome/src/styled/nav/StyledNav.ts
  packages/chrome/src/styled/nav/StyledNavButton.ts
  packages/chrome/src/styled/nav/StyledNavItemIcon.ts
  packages/chrome/src/styled/nav/StyledNavItemText.ts
  packages/chrome/src/styled/sheet/StyledSheet.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheet.ts
  packages/chrome/src/styled/sheet/StyledSheetClose.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetClose.ts
  packages/chrome/src/styled/sheet/StyledSheetDescription.ts
  packages/chrome/src/styled/sheet/StyledSheetFooter.ts
  packages/chrome/src/styled/sheet/StyledSheetFooterItem.ts
  packages/chrome/src/styled/sheet/StyledSheetHeader.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetHeader.ts
  packages/chrome/src/styled/sheet/StyledSheetTitle.ts
  packages/chrome/src/styled/sheet/StyledSheetWrapper.spec.tsx
  packages/chrome/src/styled/sheet/StyledSheetWrapper.ts
  packages/chrome/src/styled/utils.ts
  packages/chrome/src/utils/useChromeContext.ts
Labels: PR: New Feature :rocket:

#1855 chore(next): updates from `main`
  .circleci/config.yml
  README.md
Labels: PR: Internal :seedling:

#1856 ci: fix missing staging deploy status by associating deploy ref to correct SHA
  package-lock.json
  package.json
  utils/scripts/deploy.mjs
Labels: PR: Internal :seedling:

#1858 chore: sync `next` with `main`
  package-lock.json
  package.json
  utils/scripts/deploy.mjs
Labels: PR: Internal :seedling:

#1852 feat(avatars): adds light/dark mode colors
  packages/avatars/demo/stories/AvatarStory.tsx
  packages/avatars/demo/~patterns/stories/MenuStory.tsx
  packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
  packages/avatars/package.json
  packages/avatars/src/elements/Avatar.spec.tsx
  packages/avatars/src/elements/Avatar.tsx
  packages/avatars/src/elements/StatusIndicator.tsx
  packages/avatars/src/styled/StyledAvatar.spec.tsx
  packages/avatars/src/styled/StyledAvatar.ts
  packages/avatars/src/styled/StyledStandaloneStatusIndicator.ts
  packages/avatars/src/styled/StyledStatusIndicator.spec.tsx
  packages/avatars/src/styled/StyledStatusIndicator.ts
  packages/avatars/src/styled/StyledStatusIndicatorBase.ts
  packages/avatars/src/styled/utility.ts
Labels: PR: New Feature :rocket:

#1863 ci: let known `[bots]` deploy to staging
  .github/workflows/ci.yaml
Labels: PR: Internal :seedling:

#1865 chore: sync `next` with `main`
  .github/workflows/ci.yaml
  package-lock.json
  package.json
Labels: PR: Internal :seedling:

#1866 fix(tooltips): increase arrow size for small / med tooltips
  packages/tooltips/src/styled/StyledTooltip.ts
Labels: PR: Bug Fix :bug:

#1864 feat(typography)!: recolor `CodeBlock` and migrate to `prism-react-renderer` v2
  docs/migration.md
  package-lock.json
  packages/typography/demo/stories/data.ts
  packages/typography/package.json
  packages/typography/src/elements/CodeBlock.spec.tsx
  packages/typography/src/elements/CodeBlock.tsx
  packages/typography/src/styled/StyledCodeBlock.spec.tsx
  packages/typography/src/styled/StyledCodeBlock.ts
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.ts
  packages/typography/src/styled/StyledCodeBlockToken.ts
  packages/typography/src/types/index.ts
Labels: PR: Breaking Change :boom:

#1868 feat(draggable)!: renames drag-drop package to draggable
  README.md
  docs/migration.md
  package-lock.json
  packages/draggable/.size-snapshot.json
  packages/draggable/README.md
  packages/draggable/demo/draggable-list.stories.mdx
  packages/draggable/demo/draggable.stories.mdx
  packages/draggable/demo/dropzone.stories.mdx
  packages/draggable/demo/stories/DraggableListStory.tsx
  packages/draggable/demo/stories/DraggableStory.tsx
  packages/draggable/demo/stories/DropzoneStory.tsx
  packages/draggable/demo/stories/data.ts
  packages/draggable/demo/~patterns/patterns.stories.mdx
  packages/draggable/demo/~patterns/stories/DragAndDropStory.tsx
  packages/draggable/demo/~patterns/stories/components.tsx
  packages/draggable/demo/~patterns/stories/data.ts
  packages/draggable/demo/~patterns/stories/types.ts
  packages/draggable/demo/~patterns/stories/utils.ts
  packages/draggable/package.json
  packages/draggable/src/elements/draggable-list/DraggableList.spec.tsx
  packages/draggable/src/elements/draggable-list/DraggableList.tsx
  packages/draggable/src/elements/draggable-list/components/DropIndicator.tsx
  packages/draggable/src/elements/draggable-list/components/Item.tsx
  packages/draggable/src/elements/draggable/Draggable.spec.tsx
  packages/draggable/src/elements/draggable/Draggable.tsx
  packages/draggable/src/elements/draggable/components/Content.spec.tsx
  packages/draggable/src/elements/draggable/components/Content.tsx
  packages/draggable/src/elements/draggable/components/Grip.spec.tsx
  packages/draggable/src/elements/draggable/components/Grip.tsx
  packages/draggable/src/elements/dropzone/Dropzone.spec.tsx
  packages/draggable/src/elements/dropzone/Dropzone.tsx
  packages/draggable/src/elements/dropzone/components/Icon.tsx
  packages/draggable/src/elements/dropzone/components/Message.tsx
  packages/draggable/src/index.ts
  packages/draggable/src/styled/draggable-list/StyledDraggableList.spec.tsx
  packages/draggable/src/styled/draggable-list/StyledDraggableList.ts
  packages/draggable/src/styled/draggable-list/StyledDropIndicator.ts
  packages/draggable/src/styled/draggable-list/StyledItem.ts
  packages/draggable/src/styled/draggable/StyledContent.ts
  packages/draggable/src/styled/draggable/StyledDraggable.spec.tsx
  packages/draggable/src/styled/draggable/StyledDraggable.ts
  packages/draggable/src/styled/draggable/StyledGrip.spec.tsx
  packages/draggable/src/styled/draggable/StyledGrip.ts
  packages/draggable/src/styled/dropzone/StyledDropzone.ts
  packages/draggable/src/styled/dropzone/StyledIcon.spec.tsx
  packages/draggable/src/styled/dropzone/StyledIcon.ts
  packages/draggable/src/styled/dropzone/StyledMessage.ts
  packages/draggable/src/styled/index.ts
  packages/draggable/src/types/index.ts
  packages/draggable/src/utils/useDraggableListContext.ts
  packages/draggable/src/utils/useDropzoneContext.ts
  packages/draggable/tsconfig.build.json
  tsconfig.json
Labels: PR: Breaking Change :boom:

#1869 fix(typography): `CodeBlock` colors
  packages/typography/src/elements/CodeBlock.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
  packages/typography/src/styled/StyledCodeBlockLine.ts
  packages/typography/src/styled/StyledCodeBlockToken.ts
Labels: PR: Bug Fix :bug:

#1862 feat(colorpickers): adds light/dark mode colors
  packages/colorpickers/demo/stories/data.ts
  packages/colorpickers/src/elements/ColorPicker/ColorWell.tsx
  packages/colorpickers/src/elements/ColorPicker/index.tsx
  packages/colorpickers/src/elements/ColorPickerDialog/index.tsx
  packages/colorpickers/src/elements/ColorSwatch/index.tsx
  packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
  packages/colorpickers/src/styled/ColorPicker/StyledAlphaRange.ts
  packages/colorpickers/src/styled/ColorPicker/StyledColorPicker.ts
  packages/colorpickers/src/styled/ColorPicker/StyledColorWell.ts
  packages/colorpickers/src/styled/ColorPicker/StyledColorWellThumb.ts
  packages/colorpickers/src/styled/ColorPicker/StyledHueRange.ts
  packages/colorpickers/src/styled/ColorPicker/StyledPreview.ts
  packages/colorpickers/src/styled/ColorPicker/StyledSliders.ts
  packages/colorpickers/src/styled/ColorPickerDialog/StyledButtonPreview.ts
  packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchLabel.ts
  packages/colorpickers/src/styled/common/StyledRange.spec.tsx
  packages/colorpickers/src/styled/common/StyledRange.ts
  packages/colorpickers/src/styled/types.ts
Labels: PR: New Feature :rocket:

#1870 feat(theming): adds shadow variables to theme + updates styled components
  packages/chrome/src/styled/StyledSkipNav.ts
  packages/chrome/src/styled/header/StyledHeader.ts
  packages/draggable/src/styled/draggable/StyledDraggable.ts
  packages/forms/src/styled/range/StyledRangeInput.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButtonContainer.ts
  packages/modals/src/styled/StyledDrawer.ts
  packages/modals/src/styled/StyledModal.ts
  packages/notifications/src/styled/StyledBase.ts
  packages/theming/demo/stories/ArrowStylesStory.tsx
  packages/theming/src/elements/ThemeProvider.spec.tsx
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/types/index.ts
  packages/theming/src/utils/menuStyles.ts
  packages/tooltips/src/styled/StyledTooltip.ts
Labels: PR: New Feature :rocket:

#1867 feat(dropdowns.legacy): new light/dark mode colors
  packages/dropdowns.legacy/src/elements/Combobox/Combobox.spec.tsx
  packages/dropdowns.legacy/src/styled/items/StyledAddItem.ts
  packages/dropdowns.legacy/src/styled/items/StyledItem.spec.tsx
  packages/dropdowns.legacy/src/styled/items/StyledItem.ts
  packages/dropdowns.legacy/src/styled/items/StyledItemIcon.ts
  packages/dropdowns.legacy/src/styled/items/StyledItemMeta.ts
  packages/dropdowns.legacy/src/styled/items/StyledNextIcon.tsx
  packages/dropdowns.legacy/src/styled/items/StyledPreviousIcon.tsx
  packages/dropdowns.legacy/src/styled/items/header/StyledHeaderIcon.ts
  packages/dropdowns.legacy/src/styled/menu/StyledSeparator.ts
  packages/dropdowns.legacy/src/styled/multiselect/StyledMultiselectMoreAnchor.ts
Labels: PR: New Feature :rocket:

#1871 feat(buttons): underline `Anchor` by default
  docs/migration.md
  package-lock.json
  packages/buttons/demo/anchor.stories.mdx
  packages/buttons/src/elements/Anchor.spec.tsx
  packages/buttons/src/elements/Anchor.tsx
  packages/buttons/src/elements/Button.spec.tsx
  packages/buttons/src/elements/Button.tsx
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/types/index.ts
Labels: PR: Bug Fix :bug:

#1873 feat: applies color-scheme to align garden and system themes
  packages/chrome/src/styled/body/StyledContent.tsx
  packages/chrome/src/styled/sheet/StyledSheetBody.ts
  packages/dropdowns/src/views/combobox/StyledTrigger.ts
  packages/grid/src/styled/StyledGrid.ts
  packages/grid/src/styled/pane/StyledPaneContent.ts
  packages/modals/src/styled/StyledBody.ts
  packages/modals/src/styled/StyledDrawerBody.ts
  packages/modals/src/styled/StyledTooltipModalBody.ts
  packages/tabs/src/styled/StyledTabList.ts
  packages/tabs/src/styled/StyledTabPanel.ts
  packages/theming/src/utils/menuStyles.ts
Labels: PR: New Feature :rocket:
