Repository zendeskgarden/react-components, pull requests merged in 2024-05, with the labels that each got.

#1799 fix(forms): updates Message to receive margin when intermediaries are present
  packages/datepickers/demo/datepicker.stories.mdx
  packages/datepickers/demo/stories/DatepickerStory.tsx
  packages/forms/src/styled/text/StyledTextInput.ts
Labels: PR: Bug Fix :bug:

#1801 chore(next): update from `main@8.76.2`
  CHANGELOG.md
  docs/changelogs/v8.md
  package-lock.json
  packages/datepickers/demo/datePicker.stories.mdx
  packages/datepickers/demo/stories/DatePickerStory.tsx
  packages/forms/src/styled/text/StyledTextInput.ts
Labels: PR: Internal :seedling:

#1802 chore(CHANGELOG): remove extra lines
  CHANGELOG.md
Labels: PR: Internal :seedling:

#1803 chore(storybook): add global dark/light color variables control
  .storybook/preview.js
  packages/theming/demo/utilities.stories.mdx
  packages/theming/src/utils/getColor.ts
Labels: PR: Internal :seedling:

#1806 feat(theming): enhance `getColor` to accept rgba and literal color variables
  packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
  packages/theming/src/elements/theme/index.ts
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
Labels: PR: New Feature :rocket:

#1807 feat(buttons): new light/dark mode colors
  packages/buttons/src/styled/StyledAnchor.spec.tsx
  packages/buttons/src/styled/StyledButton.spec.tsx
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledIconButton.spec.tsx
  packages/buttons/src/styled/StyledIconButton.ts
  packages/buttons/src/styled/StyledSplitButton.spec.tsx
Labels: PR: New Feature :rocket:

#1805 feat(drag-drop): adds light/dark mode colors
  package-lock.json
  packages/drag-drop/demo/~patterns/stories/components.tsx
  packages/drag-drop/package.json
  packages/drag-drop/src/elements/dropzone/Dropzone.spec.tsx
  packages/drag-drop/src/styled/draggable-list/StyledDropIndicator.ts
  packages/drag-drop/src/styled/draggable/StyledDraggable.spec.tsx
  packages/drag-drop/src/styled/draggable/StyledDraggable.ts
  packages/drag-drop/src/styled/draggable/StyledGrip.ts
  packages/drag-drop/src/styled/dropzone/StyledDropzone.ts
Labels: PR: New Feature :rocket:

#1804 fix(Buttons): correctly support overriding default `data-garden-id` attribute
  packages/buttons/src/elements/Button.spec.tsx
  packages/buttons/src/styled/StyledAnchor.spec.tsx
  packages/buttons/src/styled/StyledAnchor.ts
  packages/buttons/src/styled/StyledButton.ts
  packages/buttons/src/styled/StyledIcon.spec.tsx
  packages/buttons/src/styled/StyledIconButton.spec.tsx
  packages/buttons/src/styled/StyledIconButton.ts
  packages/buttons/src/styled/index.ts
  packages/colorpickers/src/elements/ColorSwatchDialog/index.spec.tsx
  packages/colorpickers/src/styled/ColorPickerDialog/StyledButton.ts
  packages/dropdowns/src/elements/menu/Menu.spec.tsx
  packages/dropdowns/src/elements/menu/Menu.tsx
  packages/dropdowns/src/views/index.ts
  packages/dropdowns/src/views/menu/StyledButton.ts
  packages/grid/src/elements/pane/components/SplitterButton.spec.tsx
  packages/grid/src/styled/pane/StyledPaneSplitterButton.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertButton.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertButton.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertClose.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertClose.ts
Labels: PR: Internal :seedling:

#1808 feat(Modal): new light/dark mode colors
  package-lock.json
  packages/modals/package.json
  packages/modals/src/styled/StyledBackdrop.spec.tsx
  packages/modals/src/styled/StyledBackdrop.ts
  packages/modals/src/styled/StyledBody.ts
  packages/modals/src/styled/StyledClose.spec.tsx
  packages/modals/src/styled/StyledClose.ts
  packages/modals/src/styled/StyledDrawerClose.spec.tsx
  packages/modals/src/styled/StyledDrawerHeader.spec.tsx
  packages/modals/src/styled/StyledHeader.spec.tsx
  packages/modals/src/styled/StyledHeader.ts
  packages/modals/src/styled/StyledModal.ts
Labels: PR: New Feature :rocket:

#1813 fix(modals): increase `box-shadow` opacity in dark mode
  packages/modals/src/styled/StyledModal.ts
Labels: PR: Bug Fix :bug:

#1815 fix(buttons): update `IconButton` foreground color
  packages/buttons/src/styled/StyledIconButton.spec.tsx
  packages/buttons/src/styled/StyledIconButton.ts
Labels: PR: Bug Fix :bug:

#1809 feat(tags): new light/dark mode colors
  packages/tags/src/elements/Tag.spec.tsx
  packages/tags/src/styled/StyledClose.ts
  packages/tags/src/styled/StyledTag.spec.tsx
  packages/tags/src/styled/StyledTag.ts
  packages/tags/src/types/index.ts
Labels: PR: New Feature :rocket:

#1814 fix: refine `arrowStyles` CSS to avoid overcast issues with drop shadows
  packages/dropdowns.legacy/src/styled/menu/StyledMenu.ts
  packages/dropdowns/src/views/menu/StyledMenu.ts
  packages/theming/demo/stories/ArrowStylesStory.tsx
  packages/theming/src/utils/arrowStyles.spec.tsx
  packages/theming/src/utils/arrowStyles.ts
Labels: PR: Bug Fix :bug:

#1811 feat(tooltips): new light/dark mode colors
  packages/tooltips/src/elements/Tooltip.spec.tsx
  packages/tooltips/src/styled/StyledTooltip.ts
Labels: PR: New Feature :rocket:
