Repository zendeskgarden/react-components, pull requests merged in 2024-06, with the labels that each got.

#1831 chore(menu): removes duplicate use of menu context in items
  packages/dropdowns.next/src/elements/menu/Item.tsx
Labels: PR: Internal :seedling:

#1819 test: add `getRenderFn` utility
  packages/tooltips/src/elements/Tooltip.spec.tsx
  utils/test/garden-test-utils.tsx
Labels: PR: Internal :seedling:

#1830 fix(tabs): prevent `isVertical` styling cascade
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/src/elements/TabList.tsx
  packages/tabs/src/elements/TabPanel.tsx
  packages/tabs/src/elements/Tabs.tsx
  packages/tabs/src/styled/StyledTab.ts
  packages/tabs/src/styled/StyledTabList.ts
  packages/tabs/src/styled/StyledTabPanel.ts
  packages/tabs/src/styled/StyledTabs.ts
  packages/tabs/src/utils/useTabsContext.ts
Labels: PR: Bug Fix :bug:

#1816 feat(dropdowns): new light/dark mode colors
  package-lock.json
  packages/dropdowns/demo/~patterns/stories/ListboxStory.tsx
  packages/dropdowns/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns/src/elements/combobox/Option.spec.tsx
  packages/dropdowns/src/elements/combobox/Option.tsx
  packages/dropdowns/src/elements/menu/Item.tsx
  packages/dropdowns/src/elements/menu/Menu.spec.tsx
  packages/dropdowns/src/views/combobox/StyledInput.ts
  packages/dropdowns/src/views/combobox/StyledInputIcon.ts
  packages/dropdowns/src/views/combobox/StyledListboxSeparator.ts
  packages/dropdowns/src/views/combobox/StyledOption.ts
  packages/dropdowns/src/views/combobox/StyledOptionIcon.ts
  packages/dropdowns/src/views/combobox/StyledOptionMeta.ts
  packages/dropdowns/src/views/combobox/StyledOptionTypeIcon.ts
  packages/dropdowns/src/views/combobox/StyledTag.ts
  packages/dropdowns/src/views/combobox/StyledTagsButton.ts
  packages/dropdowns/src/views/combobox/StyledTrigger.ts
  packages/dropdowns/src/views/combobox/StyledValue.ts
  packages/forms/src/styled/common/StyledHint.ts
  packages/forms/src/styled/common/StyledLabel.ts
  packages/forms/src/styled/common/StyledMessage.spec.tsx
  packages/forms/src/styled/common/StyledMessage.ts
  packages/theming/src/utils/menuStyles.ts
Labels: PR: New Feature :rocket:

#1832 refactor(theming): improves custom color scale generation
  package-lock.json
  packages/theming/package.json
  packages/theming/src/utils/getColor.spec.ts
  packages/theming/src/utils/getColor.ts
Labels: PR: Internal :seedling:

#1818 feat(loaders): new light/dark mode colors
  packages/loaders/demo/stories/SkeletonStory.tsx
  packages/loaders/src/elements/Progress.spec.tsx
  packages/loaders/src/elements/Skeleton.spec.tsx
  packages/loaders/src/elements/Skeleton.tsx
  packages/loaders/src/styled/StyledInline.ts
  packages/loaders/src/styled/StyledProgress.ts
  packages/loaders/src/styled/StyledSVG.spec.tsx
  packages/loaders/src/styled/StyledSkeleton.ts
  packages/loaders/src/styled/index.spec.tsx
Labels: PR: New Feature :rocket:

#1820 feat(typography): new light/dark mode colors (excluding CodeBlock)
  .storybook/preview.js
  packages/typography/src/elements/Code.spec.tsx
  packages/typography/src/elements/span/Span.spec.tsx
  packages/typography/src/styled/StyledBlockquote.ts
  packages/typography/src/styled/StyledCode.spec.tsx
  packages/typography/src/styled/StyledCode.ts
  packages/typography/src/styled/StyledFont.tsx
Labels: PR: New Feature :rocket:

#1834 fix(deps): sync `main` to `next`
  docs/changelogs/v8.md
  package-lock.json
  package.json
  packages/.template/package.json
  packages/accordions/package.json
  packages/avatars/package.json
  packages/breadcrumbs/package.json
  packages/buttons/package.json
  packages/chrome/package.json
  packages/colorpickers/package.json
  packages/datepickers/package.json
  packages/drag-drop/package.json
  packages/dropdowns.legacy/package.json
  packages/dropdowns/package.json
  packages/dropdowns/src/elements/menu/Item.tsx
  packages/forms/package.json
  packages/forms/src/elements/common/Label.tsx
  packages/grid/package.json
  packages/loaders/package.json
  packages/modals/package.json
  packages/notifications/package.json
  packages/pagination/package.json
  packages/tables/package.json
  packages/tabs/package.json
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/src/elements/TabList.tsx
  packages/tabs/src/elements/TabPanel.tsx
  packages/tabs/src/elements/Tabs.tsx
  packages/tabs/src/styled/StyledTab.ts
  packages/tabs/src/styled/StyledTabList.ts
  packages/tabs/src/styled/StyledTabPanel.ts
  packages/tabs/src/styled/StyledTabs.ts
  packages/tabs/src/utils/useTabsContext.ts
  packages/tags/package.json
  packages/theming/package.json
  packages/theming/src/utils/getColor.ts
  packages/tooltips/package.json
  packages/typography/package.json
Labels: PR: Internal :seedling:

#1835 fix: package and package-lock JSON
  package-lock.json
  package.json
Labels: PR: Bug Fix :bug:

#1833 feat(tables): new light/dark mode colors
  docs/migration.md
  package-lock.json
  packages/tables/package.json
  packages/tables/src/elements/Cell.tsx
  packages/tables/src/elements/GroupRow.tsx
  packages/tables/src/elements/Head.tsx
  packages/tables/src/elements/HeaderCell.tsx
  packages/tables/src/elements/HeaderRow.tsx
  packages/tables/src/elements/OverflowButton.spec.tsx
  packages/tables/src/elements/OverflowButton.tsx
  packages/tables/src/elements/Row.spec.tsx
  packages/tables/src/elements/Row.tsx
  packages/tables/src/elements/SortableCell.tsx
  packages/tables/src/elements/Table.tsx
  packages/tables/src/styled/StyledBaseRow.ts
  packages/tables/src/styled/StyledCell.ts
  packages/tables/src/styled/StyledGroupRow.ts
  packages/tables/src/styled/StyledHead.spec.tsx
  packages/tables/src/styled/StyledHead.ts
  packages/tables/src/styled/StyledHeaderCell.ts
  packages/tables/src/styled/StyledHeaderRow.ts
  packages/tables/src/styled/StyledOverflowButton.ts
  packages/tables/src/styled/StyledRow.ts
  packages/tables/src/styled/StyledSortableButton.ts
  packages/tables/src/styled/StyledTable.ts
  packages/tables/src/styled/index.ts
  packages/tables/src/styled/style-utils.ts
Labels: PR: New Feature :rocket:

#1839 feat(grid): new light/dark mode colors
  packages/grid/demo/grid.stories.mdx
  packages/grid/src/styled/StyledCol.ts
  packages/grid/src/styled/StyledGrid.ts
  packages/grid/src/styled/StyledRow.ts
  packages/grid/src/styled/pane/StyledPaneSplitter.ts
  packages/grid/src/styled/pane/StyledPaneSplitterButtonContainer.ts
Labels: PR: New Feature :rocket:

#1840 feat(modals): new light/dark mode colors for `TooltipModal` and `Drawer`
  packages/modals/demo/stories/TooltipModalStory.tsx
  packages/modals/src/elements/TooltipModal/Close.tsx
  packages/modals/src/styled/StyledDrawer.spec.tsx
  packages/modals/src/styled/StyledDrawer.ts
  packages/modals/src/styled/StyledDrawerFooter.ts
  packages/modals/src/styled/StyledModal.ts
  packages/modals/src/styled/StyledTooltipModalBody.ts
  packages/modals/src/styled/StyledTooltipModalClose.ts
  packages/modals/src/styled/StyledTooltipModalTitle.ts
Labels: PR: New Feature :rocket:

#1843 feat(tabs): new light/dark mode colors
  packages/tabs/src/elements/Tab.tsx
  packages/tabs/src/elements/TabList.tsx
  packages/tabs/src/elements/TabPanel.tsx
  packages/tabs/src/elements/Tabs.tsx
  packages/tabs/src/styled/StyledTab.ts
  packages/tabs/src/styled/StyledTabList.ts
  packages/tabs/src/styled/StyledTabPanel.ts
  packages/tabs/src/styled/StyledTabs.ts
Labels: PR: New Feature :rocket:

#1842 feat(notifications): new light/dark mode colors
  packages/notifications/src/elements/Alert.tsx
  packages/notifications/src/elements/Notification.tsx
  packages/notifications/src/elements/Well.tsx
  packages/notifications/src/elements/content/Close.tsx
  packages/notifications/src/elements/content/Title.spec.tsx
  packages/notifications/src/elements/content/Title.tsx
  packages/notifications/src/elements/global-alert/GlobalAlert.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertButton.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertClose.tsx
  packages/notifications/src/elements/global-alert/GlobalAlertTitle.tsx
  packages/notifications/src/styled/StyledAlert.spec.tsx
  packages/notifications/src/styled/StyledAlert.ts
  packages/notifications/src/styled/StyledBase.spec.tsx
  packages/notifications/src/styled/StyledBase.ts
  packages/notifications/src/styled/StyledIcon.spec.tsx
  packages/notifications/src/styled/StyledIcon.ts
  packages/notifications/src/styled/StyledNotification.spec.tsx
  packages/notifications/src/styled/StyledNotification.ts
  packages/notifications/src/styled/StyledWell.spec.tsx
  packages/notifications/src/styled/StyledWell.ts
  packages/notifications/src/styled/content/StyledClose.spec.tsx
  packages/notifications/src/styled/content/StyledClose.ts
  packages/notifications/src/styled/content/StyledParagraph.ts
  packages/notifications/src/styled/content/StyledTitle.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlert.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlert.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertButton.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertButton.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertClose.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertClose.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertContent.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertIcon.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertIcon.ts
  packages/notifications/src/styled/global-alert/StyledGlobalAlertTitle.spec.tsx
  packages/notifications/src/styled/global-alert/StyledGlobalAlertTitle.ts
  packages/notifications/src/utils/icons.ts
  packages/notifications/src/utils/useGlobalAlertContext.ts
  packages/notifications/src/utils/useNotificationsContext.ts
Labels: PR: New Feature :rocket:

#1845 chore: sync latest `main` with `next`
  package-lock.json
Labels: PR: Internal :seedling:
