Repository zendeskgarden/react-components, pull requests merged in 2024-12, with the labels that each got.

#1981 fix(chrome): provide missing `useId` container dependency for `Sheet` component
  package-lock.json
  packages/chrome/package.json
  packages/chrome/src/elements/sheet/Sheet.tsx
  packages/chrome/src/types/index.ts
Labels: PR: Bug Fix :bug:

#1982 fix(accordions): set `inert` for hidden `Stepper` content
  packages/accordions/src/elements/stepper/components/Content.spec.tsx
  packages/accordions/src/elements/stepper/components/Content.tsx
  packages/accordions/src/styled/stepper/StyledInnerContent.ts
Labels: PR: Bug Fix :bug:

#1983 chore(dropdowns): fix multiselectable combobox tags
  packages/dropdowns/demo/stories/ComboboxStory.tsx
Labels: PR: Internal :seedling:

#1986 feat(theming): add componentStyles utility
  docs/api.md
  packages/theming/src/index.ts
  packages/theming/src/utils/componentStyles.spec.ts
  packages/theming/src/utils/componentStyles.ts
  packages/theming/src/utils/retrieveComponentStyles.ts
Labels: PR: New Feature :rocket:

#1987 fix(Combobox): improve screen reader experience for Select-Only combobox w NVDA
  packages/dropdowns/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns/src/elements/combobox/Listbox.tsx
Labels: PR: Bug Fix :bug:

#1988 fix(Combobox): improve screen reader experience for Select-Only combobox w NVDA
  packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
  packages/dropdowns.next/src/elements/combobox/Listbox.tsx
Labels: PR: Bug Fix :bug:

#1990 chore: set `dist-tag` to `v8`
  lerna.json
Labels: PR: Internal :seedling:
